### ISSUE TITLE
Error when create client from Plan or page start 

### ISSUE THREAD

**Issue by phuclc** [it-projects-llc/odoo-saas-tools#117]
@yelizariev: When I create client from Plan or page start then has occurred error:

![error_saas_portal](https://cloud.githubusercontent.com/assets/13634606/12138830/6b82ed90-b48e-11e5-9905-b1f87e574851.png)
I am using 9.0-dev branch. Please review it again. Thank you very much :+1:

**Comment by yelizariev** [comment]
Could you repeat and send full log

**Comment by ghost** [comment]
@yelizariev: Yes. Thanks for your support.
**Case1**: Select Plan -> Click `Create Client` button -> set DB Name -> Create -> Error

```
  File "/opt/odoo9/odoo/addons/saas_portal_sale/models/saas_portal.py", line 18, in create_new_database
    support_team_id=support_team_id)
  File "/opt/odoo9/odoo/openerp/api.py", line 236, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo9/odoo/addons/saas_portal/models/saas_portal.py", line 265, in create_new_database
    client.send_params_to_client_db()
  File "/opt/odoo9/odoo/openerp/api.py", line 236, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo9/odoo/addons/saas_portal/models/saas_portal.py", line 597, in send_params_to_client_db
    self.env['saas.config'].do_upgrade_database(payload, record.id)
  File "/opt/odoo9/odoo/openerp/api.py", line 236, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo9/odoo/addons/saas_portal/models/wizard.py", line 90, in do_upgrade_database
    raise Warning(msg)
Warning: Status Code - 500
Reason - INTERNAL SERVER ERROR
URL - http://s1.vietnamerp.net:80/saas_server/upgrade_database?access_token=jUKe5cDL8k7md0mp6Nw9GXrwkZDCN0&expires_in=3600&token_type=Bearer&state=%7B%22data%22%3A+%7B%22params%22%3A+%5B%7B%22hidden%22%3A+true%2C+%22value%22%3A+false%2C+%22key%22%3A+%22saas_client.max_users%22%7D%2C+%7B%22hidden%22%3A+true%2C+%22value%22%3A+%222016-01-06+16%3A57%3A04%22%2C+%22key%22%3A+%22saas_client.expiration_datetime%22%7D%2C+%7B%22hidden%22%3A+true%2C+%22value%22%3A+0%2C+%22key%22%3A+%22saas_client.total_storage_limit%22%7D%5D%7D%7D&redirect_uri=http%3A%2F%2Fs1.vietnamerp.net%3A80%2Fweb&response_type=token&client_id=83ae97c2-b496-11e5-9209-0018510a5e06&scope=userinfo+force_login+trial+skiptheuse
```

**Case 2**: From http://vietnamerp.net/page/start -> Input subdomain -> Create -> Error

```
invalid literal for int() with base 10: 'undefined'
```

Current url: http://vietnamerp.net/saas_portal/add_new_client?lang=en_US&dbname=xyza&tz=+0700&hosting=&app=&plan_id=undefined. 
If I modify plan_id=3(http://vietnamerp.net/saas_portal/add_new_client?lang=en_US&dbname=xyza&tz=+0700&hosting=&app=&plan_id=3) then error: 

```
Status Code - 500
Reason - INTERNAL SERVER ERROR
URL - http://s1.vietnamerp.net:80/saas_server/upgrade_database?access_token=3BPyEdVdl4hh0PQMCc215QJYU0fey2&expires_in=3600&token_type=Bearer&state=%7B%22data%22%3A+%7B%22params%22%3A+%5B%7B%22hidden%22%3A+true%2C+%22value%22%3A+false%2C+%22key%22%3A+%22saas_client.max_users%22%7D%2C+%7B%22hidden%22%3A+true%2C+%22value%22%3A+%222016-01-06+17%3A07%3A26%22%2C+%22key%22%3A+%22saas_client.expiration_datetime%22%7D%2C+%7B%22hidden%22%3A+true%2C+%22value%22%3A+0%2C+%22key%22%3A+%22saas_client.total_storage_limit%22%7D%5D%7D%7D&redirect_uri=http%3A%2F%2Fs1.vietnamerp.net%3A80%2Fweb&response_type=token&client_id=f61f53f4-b497-11e5-bca9-0018510a5e06&scope=userinfo+force_login+trial+skiptheuse
```

Can you support me? Thank you very much! :tropical_drink:

**Comment by wadelu** [comment]
I also facing same error while create DB by portal as following error:

Traceback (most recent call last):
  File "/home/odoo/odoo/addons/website/models/ir_http.py", line 243, in _handle_exception
    response = super(ir_http, self)._handle_exception(exception)
  File "/home/odoo/odoo/openerp/addons/base/ir/ir_http.py", line 157, in _handle_exception
    return request._handle_exception(exception)
  File "/home/odoo/odoo/openerp/http.py", line 781, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/home/odoo/odoo/openerp/addons/base/ir/ir_http.py", line 182, in _dispatch
    result = request.dispatch()
  File "/home/odoo/odoo/openerp/http.py", line 840, in dispatch
    r = self._call_function(*_self.params)
  File "/home/odoo/odoo/openerp/http.py", line 316, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/home/odoo/odoo/openerp/service/model.py", line 118, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/home/odoo/odoo/openerp/http.py", line 309, in checked_call
    result = self.endpoint(_a, *_kw)
  File "/home/odoo/odoo/openerp/http.py", line 959, in __call__
    return self.method(_args, *_kw)
  File "/home/odoo/odoo/openerp/http.py", line 509, in response_wrap
    response = f(_args, *_kw)
  File "/home/odoo/odoo-addons/odoo-saas-tools/saas_portal_sale/controllers/main.py", line 27, in add_new_client
    return super(SaasPortalSale, self).add_new_client(**post)
  File "/home/odoo/odoo/openerp/http.py", line 509, in response_wrap
    response = f(_args, *_kw)
  File "/home/odoo/odoo-addons/odoo-saas-tools/saas_portal/controllers/main.py", line 37, in add_new_client
    res = plan.create_new_database(dbname=dbname, user_id=user_id, partner_id=partner_id)
  File "/home/odoo/odoo/openerp/api.py", line 248, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/home/odoo/odoo-addons/odoo-saas-tools/saas_portal/models/saas_portal.py", line 191, in create_new_database
    return self._create_new_database(**kwargs)
  File "/home/odoo/odoo/openerp/api.py", line 248, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/home/odoo/odoo-addons/odoo-saas-tools/saas_portal_sale/models/saas_portal.py", line 23, in _create_new_database
    async=async)
  File "/home/odoo/odoo/openerp/api.py", line 248, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/home/odoo/odoo-addons/odoo-saas-tools/saas_portal/models/saas_portal.py", line 201, in _create_new_database
    server.action_sync_server()
  File "/home/odoo/odoo/openerp/api.py", line 248, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/home/odoo/odoo/openerp/api.py", line 425, in new_api
    result = [method(rec, _args, *_kwargs) for rec in self]
  File "/home/odoo/odoo-addons/odoo-saas-tools/saas_portal/models/saas_portal.py", line 114, in action_sync_server
    raise Warning('Reason: %s \n Message: %s' % (res.reason, res.content))
Warning: Reason: Not Found 

Would you please kindly help to check? Thank you very much!
