### ISSUE TITLE
error when installing saas_portal

### ISSUE THREAD

**Issue by talazoft** [it-projects-llc/odoo-saas-tools#137]
Hi, when I'm install saas_portal it gives me this error

Traceback (most recent call last):
  File "/opt/odoo_saas/openerp/http.py", line 537, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo_saas/openerp/http.py", line 574, in dispatch
    result = self._call_function(*_self.params)
  File "/opt/odoo_saas/openerp/http.py", line 310, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/opt/odoo_saas/openerp/service/model.py", line 118, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/opt/odoo_saas/openerp/http.py", line 307, in checked_call
    return self.endpoint(_a, *_kw)
  File "/opt/odoo_saas/openerp/http.py", line 803, in __call__
    return self.method(_args, *_kw)
  File "/opt/odoo_saas/openerp/http.py", line 403, in response_wrap
    response = f(_args, *_kw)
  File "/opt/odoo_saas/addons/web/controllers/main.py", line 948, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo_saas/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "/opt/odoo_saas/openerp/api.py", line 268, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo_saas/openerp/addons/base/module/module.py", line 447, in button_immediate_install
    return self._button_immediate_function(cr, uid, ids, self.button_install, context=context)
  File "/opt/odoo_saas/openerp/api.py", line 268, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo_saas/openerp/addons/base/module/module.py", line 495, in _button_immediate_function
    registry = openerp.modules.registry.RegistryManager.new(cr.dbname, update_module=True)
  File "/opt/odoo_saas/openerp/modules/registry.py", line 370, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo_saas/openerp/modules/loading.py", line 355, in load_modules
    loaded_modules, update_module)
  File "/opt/odoo_saas/openerp/modules/loading.py", line 255, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/opt/odoo_saas/openerp/modules/loading.py", line 176, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/opt/odoo_saas/openerp/modules/loading.py", line 118, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/opt/odoo_saas/openerp/tools/convert.py", line 901, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/opt/odoo_saas/openerp/tools/convert.py", line 987, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/opt/odoo_saas/openerp/tools/convert.py", line 853, in parse
    self._tags[rec.tag](self.cr, rec, n, mode=mode)
  File "/opt/odoo_saas/openerp/tools/convert.py", line 693, in _tag_record
    model = self.pool[rec_model]
  File "/opt/odoo_saas/openerp/modules/registry.py", line 102, in __getitem__
    return self.models[model_name]
ParseError: "mail.template" while parsing /opt/odoo_saas/odoo-saas-tools/saas_portal/data/mail_template_data.xml:3, near
<record id="email_template_create_saas" model="mail.template">
            <field name="name">Send SaaS credentials to the buyer of the SaaS</field>
            <field name="email_from">${(object.user_id.email or '')|safe}</field>
            <field name="subject">Credentials:</field>
            <field name="partner_to">${object.partner_id.id}</field>
            <field name="model_id" ref="saas_portal.model_saas_portal_client"/>
            <field name="auto_delete" eval="True"/>
            <field name="lang">${object.partner_id.lang}</field>
            <field name="body_html">

```
        &lt;p&gt;Web:
        &lt;a href="http://${object.name}"&gt;http://${object.name}&lt;/a&gt;
        &lt;/p&gt;

        </field>
    </record>
```

Thanks before

**Comment by yelizariev** [comment]
@talazoft Seems like your error message is not correctly formated and some text is lost. Use `insert quote` or `insert code` buttons
