### ISSUE TITLE
Error on database backup

### ISSUE THREAD

**Issue by dansalsero** [it-projects-llc/odoo-saas-tools#227]
This error shows when doing a database backup from saas client meny, button DB backup

**Comment by dansalsero** [comment]
File "/usr/local/src/odoo/openerp/api.py", line 248, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/usr/local/src/odoo-addons/odoo-saas-tools/saas_portal/models/saas_portal.py", line 414, in _backup
    if data['status'] != 'success':
TypeError: list indices must be integers, not str

**Comment by yelizariev** [comment]
@iledarn 
please fix this block 

```
    data = simplejson.loads(res.text)
    if data['status'] != 'success':
        warning = data[0].get('message', 'Could not backup database; please check your logs')
        raise Warning(warning)
```

to get more logs in such cases

E.g.

```
    data = simplejson.loads(res.text)
    if not  isinstance(data, dict):
         raise Warning(data)
    if data['status'] != 'success':
        warning = data[0].get('message', 'Could not backup database; please check your logs')
        raise Warning(warning)
```

**Comment by yelizariev** [comment]
@dansalsero we will need new log message after such update to figure out with your issue

**Comment by dansalsero** [comment]
Hi, I'l like to hepl, but I don't understand what do I have to do...

**Comment by yelizariev** [comment]
@dansalsero if you can provide odoo logs (i.e. logs from odoo instances, not from a browser) it can help

**Comment by dansalsero** [comment]
Hi, @iledarn helped me to install saas_server, but I don't know where can I get the log on this install as it's not on the regular files I had used before. 

Can you please tell me where can I find the logs?

**Comment by dansalsero** [comment]
This are the logs on my database.

I have a missing dependency:

2016-03-15 20:33:05,003 6294 CRITICAL ? openerp.addons.saas_server_backup_ftp.models.res_config: saas_server_backup_ftp requires the python library pysftp which is not$

Which seems to be the problem:

Traceback (most recent call last):
  File "/usr/local/src/odoo-addons/odoo-saas-tools/saas_server/models/saas_server.py", line 356, in backup_database
    database_obj._transport_backup(dump_db, filename=filename)
  File "/usr/local/src/odoo/openerp/api.py", line 248, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/usr/local/src/odoo-addons/odoo-saas-tools/saas_server_backup_ftp/models/saas_server.py", line 22, in _transport_backup
    srv = pysftp.Connection(host=server, username=username, password=password)
NameError: global name 'pysftp' is not defined

And:

```
result = method(recs, *args, **kwargs)
```

  File "/usr/local/src/odoo-addons/odoo-saas-tools/saas_portal_backup/models/saas_portal.py", line 14, in action_backup
    self._backup()
  File "/usr/local/src/odoo/openerp/api.py", line 248, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/usr/local/src/odoo-addons/odoo-saas-tools/saas_portal/models/saas_portal.py", line 414, in _backup
    if data['status'] != 'success':
TypeError: list indices must be integers, not str

But pysftp is installed:

Requirement already satisfied (use --upgrade to upgrade): pysftp in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied (use --upgrade to upgrade): paramiko>=1.7.7 in /usr/local/lib/python2.7/dist-packages (from pysftp)
Cleaning up...

Thanks a lot.

Daniel.

**Comment by iledarn** [comment]
@dansalsero 
I have updated _backup in saas_portal. So you can now get more error logs on the issue

**Comment by dansalsero** [comment]
@iledarn thanks a lot.

I'll try to update the modules to see if I can get it to work.

Daniel.
