### ISSUE TITLE
create_template failed

### ISSUE THREAD

**Issue by wadelu** [it-projects-llc/odoo-saas-tools#231]
portal DB and server DB created successfully, but create template failed with error as following: not found the URL listed,

/saas_server/new_database?access                                                                                                              _token=J2j88JGAFzhS5rMWQUnwL1RYeJ3bRR&expires_in=3600&token_type=Bearer&state=%7B%22lang%22%3A+false%2C+%22tz%22%3A+fals                                                                                                              e%2C+%22d%22%3A+%22template1.anue.top%22%2C+%22demo%22%3A+0%2C+%22is_template_db%22%3A+1%2C+%22addons%22%3A+%5B%5D%7D&re                                                                                                              direct_uri=http%3A%2F%2Fserver1.anue.top%3A80%2Fsaas_server%2Fnew_database&response_type=token&client_id=6b5bcdf8-e8d9-1                                                                                                              1e5-b8b0-525400781ea0&scope=userinfo+force_login+trial+skiptheuse

`saas.py >>> Dropping  database template1.anue.top

saas.py >>> Result: DROP DATABASE

saas.py >>> EXEC: , rm -rf /home/odoo/.local/share/Odoo/filestore/template1.anue.top

saas.py >>> auth, ('anue.top', <ServerProxy for anue.top/xmlrpc/2/object>, 1, '12345678')

saas.py >>> RPC Execute, saas_portal.plan, create_template, [[1]], {}
2016-03-13 05:07:01,380 6551 INFO anue.top requests.packages.urllib3.connectionpool: Starting new HTTP connection (1): s                                                                                                              erver1.anue.top
2016-03-13 05:07:02,288 6552 WARNING ? openerp.addons.saas_server_backup_s3.models.saas_client: SAAS Sysadmin Bacnkup Ag                                                                                                              ent S3 performs better with large files if you have FileChunkIO installed
2016-03-13 05:07:02,305 6552 INFO ? openerp.http: HTTP Configuring static files
2016-03-13 05:07:02,320 6552 INFO ? openerp.http: Generating nondb routing
2016-03-13 05:07:02,338 6552 INFO ? werkzeug: 127.0.0.1 - - [13/Mar/2016 05:07:02] "GET /saas_server/new_database?access                                                                                                              _token=J2j88JGAFzhS5rMWQUnwL1RYeJ3bRR&expires_in=3600&token_type=Bearer&state=%7B%22lang%22%3A+false%2C+%22tz%22%3A+fals                                                                                                              e%2C+%22d%22%3A+%22template1.anue.top%22%2C+%22demo%22%3A+0%2C+%22is_template_db%22%3A+1%2C+%22addons%22%3A+%5B%5D%7D&re                                                                                                              direct_uri=http%3A%2F%2Fserver1.anue.top%3A80%2Fsaas_server%2Fnew_database&response_type=token&client_id=6b5bcdf8-e8d9-1                                                                                                              1e5-b8b0-525400781ea0&scope=userinfo+force_login+trial+skiptheuse HTTP/1.0" 404 -
2016-03-13 05:07:02,343 6551 ERROR anue.top openerp.http: Reason: Not Found
 Message: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>404 Not Found</title>

<h1>Not Found</h1>

<p>The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try ag                                                                                                              ain.</p>

Traceback (most recent call last):
  File "/home/odoo/odoo/openerp/http.py", line 114, in dispatch_rpc
    result = dispatch(method, params)
  File "/home/odoo/odoo/openerp/service/model.py", line 37, in dispatch
    res = fn(db, uid, _params)
  File "/home/odoo/odoo/openerp/service/model.py", line 173, in execute_kw
    return execute(db, uid, obj, method, *args, *_kw or {})
  File "/home/odoo/odoo/openerp/service/model.py", line 118, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/home/odoo/odoo/openerp/service/model.py", line 181, in execute
    res = execute_cr(cr, uid, obj, method, _args, *_kw)
  File "/home/odoo/odoo/openerp/service/model.py", line 170, in execute_cr
    return getattr(object, method)(cr, uid, _args, *_kw)
  File "/home/odoo/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/odoo/odoo/openerp/api.py", line 381, in old_api
    result = method(recs, _args, *_kwargs)
  File "/home/odoo/odoo-addons/odoo-saas-tools/saas_portal/models/saas_portal.py", line 334, in create_template
    raise Warning('Reason: %s \n Message: %s' % (res.reason, res.content))
Warning: Reason: Not Found
 Message: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>404 Not Found</title>

<h1>Not Found</h1>

<p>The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try ag       `

**Comment by yelizariev** [comment]
Do you have corresponded records in /etc/hosts ?

**Comment by wadelu** [comment]
Y, actually create portal DB and Server DB both succeed. 
Does the DB filter parameter will impact this? I sued sub-domain mode.

**Comment by yelizariev** [comment]
you must be careful about db-filter. 
Currently saas.py  work only with `--db-filter=%h`

**Comment by erkesado** [comment]
How is it solved? I have same problem.

**Comment by yelizariev** [comment]
Please check this instruction and about confiruation requirements https://github.com/yelizariev/odoo-saas-tools/blob/9.0/docs/odoo-configuration.rst

**Comment by yelizariev** [comment]
I make a blog post about similar problems https://it-projects-llc.github.io/odoo-saas-tools/blog/reason-not-found
