### ISSUE TITLE
Error while sync server and creating template db

### ISSUE THREAD

**Issue by jack-solutions** [it-projects-llc/odoo-saas-tools#26]
I'm getting error while sync server and creating template db.
I've used db-filter=%d.
create two database:
portal-> domain: portal.odoo.local
server->domain: server.odoo.local
I've installed all the required modules according to database.(either server or portal) and
change the config form Apache to nginx.(as per last issue:  issue in step 6: Create plan #14 )
my odoo log: 

Odoo Server Error
Traceback (most recent call last):
  File "/home/mrugank/odoo-dev/odoo/openerp/http.py", line 537, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/mrugank/odoo-dev/odoo/openerp/http.py", line 574, in dispatch
    result = self._call_function(*_self.params)
  File "/home/mrugank/odoo-dev/odoo/openerp/http.py", line 310, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/home/mrugank/odoo-dev/odoo/openerp/service/model.py", line 113, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/home/mrugank/odoo-dev/odoo/openerp/http.py", line 307, in checked_call
    return self.endpoint(_a, *_kw)
  File "/home/mrugank/odoo-dev/odoo/openerp/http.py", line 803, in __call__
    return self.method(_args, *_kw)
  File "/home/mrugank/odoo-dev/odoo/openerp/http.py", line 403, in response_wrap
    response = f(_args, *_kw)
  File "/home/mrugank/odoo-dev/odoo/addons/web/controllers/main.py", line 948, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/mrugank/odoo-dev/odoo/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "/home/mrugank/odoo-dev/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/mrugank/odoo-dev/odoo/openerp/api.py", line 363, in old_api
    result = method(recs, _args, *_kwargs)
  File "/home/mrugank/odoo-dev/working_saas/odoo-saas/saas_portal/models/saas_portal.py", line 286, in create_template
    res = requests.get(url, verify=(plan.server_id.request_scheme == 'https' and plan.server_id.verify_ssl))
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 55, in get
    return request('get', url, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 44, in request
    return session.request(method=method, url=url, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 455, in request
    resp = self.send(prep, *_send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 558, in send
    r = adapter.send(request, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 378, in send
    raise ConnectionError(e)
ConnectionError: HTTPConnectionPool(host='server', port=80): Max retries exceeded with url: /saas_server/new_database?access_token=0T3M5u1L8C8q1EYslD5tPN5hwV3IEZ&expires_in=3600&token_type=Bearer&state=%7B%22lang%22%3A+%22en_US%22%2C+%22tz%22%3A+%22Asia%2FCalcutta%22%2C+%22d%22%3A+%22template%22%2C+%22demo%22%3A+1%2C+%22is_template_db%22%3A+1%2C+%22addons%22%3A+%5B%5D%7D&redirect_uri=http%3A%2F%2Fserver%3A80%2Fsaas_server%2Fnew_database&response_type=token&client_id=ba45bd2a-594b-11e5-84a5-00e04c049539&scope=userinfo+force_login+trial+skiptheuse (Caused by <class 'socket.gaierror'>: [Errno -2] Name or service not known)

Is this module compatible with db-filter : %d.
because in portal database under settings/Configuration/SaaS Portal Setting I've specified Base SaaS domain as portal.odoo.local(in your example it was odoo.local).

**Comment by saltonmassally** [comment]
@jack-solutions  please see https://github.com/yelizariev/odoo-saas-tools/blob/8.0/README.md especially the first part of it:
- set dbfilter in config file or run odoo with --db-filter parameter, e.g. ^%h$
- execute command (see readme) to allow create databases with dots in name

To answer your question I don't think it is compatible with %d

**Comment by jack-solutions** [comment]
okay.
Thank you. 
so, we have to use %h as db filter which enable filtration on domains instead of sub domain(%d).

**Comment by sathwiksunderreddy** [comment]
Hi
I'm Getting this error when creating templatedb
Traceback (most recent call last):
  File "D:\New odoo\odoo-8.0-20170403\openerp\http.py", line 544, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "D:\New odoo\odoo-8.0-20170403\openerp\http.py", line 581, in dispatch
    result = self._call_function(**self.params)
  File "D:\New odoo\odoo-8.0-20170403\openerp\http.py", line 317, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "D:\New odoo\odoo-8.0-20170403\openerp\service\model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "D:\New odoo\odoo-8.0-20170403\openerp\http.py", line 314, in checked_call
    return self.endpoint(*a, **kw)
  File "D:\New odoo\odoo-8.0-20170403\openerp\http.py", line 810, in __call__
    return self.method(*args, **kw)
  File "D:\New odoo\odoo-8.0-20170403\openerp\http.py", line 410, in response_wrap
    response = f(*args, **kw)
  File "D:\New odoo\odoo-8.0-20170403\openerp\addons\web\controllers\main.py", line 948, in call_button
    action = self._call_kw(model, method, args, {})
  File "D:\New odoo\odoo-8.0-20170403\openerp\addons\web\controllers\main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "D:\New odoo\odoo-8.0-20170403\openerp\api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "D:\New odoo\odoo-8.0-20170403\openerp\api.py", line 399, in old_api
    result = method(recs, *args, **kwargs)
  File "D:\New odoo\odoo-8.0-20170403\openerp\addons\saas_portal\models\saas_portal.py", line 344, in create_template_button
    res = self.create_template()
  File "D:\New odoo\odoo-8.0-20170403\openerp\api.py", line 266, in wrapper
    return new_api(self, *args, **kwargs)
  File "D:\New odoo\odoo-8.0-20170403\openerp\addons\saas_portal\models\saas_portal.py", line 365, in create_template
    raise Warning('Error on request: %s\nReason: %s \n Message: %s' % (req.url, res.reason, res.content))
Warning: Error on request: http://s1.odoo.local:80/saas_server/new_database
Reason: NOT FOUND 
 Message: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>404 Not Found</title>
<h1>Not Found</h1>
<p>The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.</p>

and when I am trying to set --db-filter=%h$

Its rendering the database manager page always

I am unable to get the odoo login page even its reloading to same page when i click Back to login

I am using a Windows system to configure Saas

Please help me

Thanks in Advance

**Comment by sathwiksunderreddy** [comment]
Hi
I am unable to login when I am using the --db-filter as ^%d or ^%h

can you please help me out @jack-solutions
