### ISSUE TITLE
Login via SaaS Portal - Access Denied

### ISSUE THREAD

**Issue by erkesado** [it-projects-llc/odoo-saas-tools#271]
Login via SaaS Portal is not working on SaaS Server. Since oauth is not working on SaaS Server, I can't Create Template DB for any plan on that SaaS Server. It is working OK locally. But it is not working on the internet with real domain name. When I Login via SaaS Portal on SaaS Server, it tries to login via oauth but connection is timed out. 

Here is the log:
2016-05-05 08:11:10,102 1567 ERROR server.saas.skysys.mn openerp.addons.auth_oauth.controllers.main: OAuth2: <urlopen error [Errno 110] Connection timed out>
Traceback (most recent call last):
  File "/home/skysys/odoo-prd/odoo/addons/auth_oauth/controllers/main.py", line 143, in signin
    credentials = u.auth_oauth(cr, SUPERUSER_ID, provider, kw, context=context)
  File "/home/skysys/odoo-prd/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/skysys/odoo-prd/odoo/addons/auth_oauth/res_users.py", line 101, in auth_oauth
    validation = self._auth_oauth_validate(cr, uid, provider, access_token, context=context)
  File "/home/skysys/odoo-prd/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/skysys/odoo-prd/odoo/addons/auth_oauth/res_users.py", line 41, in _auth_oauth_validate
    validation = self._auth_oauth_rpc(cr, uid, p.validation_endpoint, access_token, context=context)
  File "/home/skysys/odoo-prd/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/skysys/odoo-prd/odoo/addons/auth_oauth/res_users.py", line 34, in _auth_oauth_rpc
    f = urllib2.urlopen(url)
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1214, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1184, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 110] Connection timed out>
2016-05-05 08:11:10,108 1567 INFO server.saas.skysys.mn werkzeug: 127.0.0.1 - - [05/May/2016 08:11:10] "GET /auth_oauth/signin?access_token=COtMyloPSIwqSsKJJJ3ovXdCdu2fiS&token_type=Bearer&state=%7B%22p%22%3A+4%2C+%22r%22%3A+%22http%253A%252F%252Fserver.saas.skysys.mn%252Fweb%22%2C+%22d%22%3A+%22server.saas.skysys.mn%22%7D&expires_in=3600&scope=userinfo HTTP/1.0" 303 -

**Comment by erkesado** [comment]
It gets stuck at:
/auth_oauth/signin#access_token=04X20Eb0cB6K3aNFlYvz5R9fLCIDIK&token_type=Bearer&state=%7B%22p%22%3A+4%2C+%22r%22%3A+%22http%253A%252F%252Fserver.saas.skysys.mn%252Fweb%22%2C+%22d%22%3A+%22server.saas.skysys.mn%22%7D&expires_in=3600&scope=userinfo

And then connection is timed out.

**Comment by yelizariev** [comment]
try to set workers=3

**Comment by erkesado** [comment]
Setting workers > 0 does not help. I still get the error 'Connection timed out' when oauth provider redirects to http://server.example.com/auth_oauth/signin?xxxxxxx. On my local PC, it is just working fine when workers = 0. I guess auth_oauth is not responding to /auth_oauth/signin/xxxxx request. Basically, auth_oauth is not working. Any ideas?

**Comment by erkesado** [comment]
@yelizariev,

In this issue, https://github.com/yelizariev/odoo-saas-tools/issues/14, jack-solutions had similar problem which is 'Access Denied' when logging in via SaaS Portal. The issue was apache configuration. He changed apache config and error was gone. I configured nginx as exactly as your instruction. Can it be my nginx configuration? Here is my nginx config:

server {
    listen 80 default_server;

```
proxy_set_header Host $host;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $scheme;

proxy_read_timeout 600s;
proxy_send_timeout 600s;    

access_log /var/log/nginx/odoo-access.log;
error_log /var/log/nginx/odoo-error.log;

location /longpolling {
    proxy_pass http://127.0.0.1:8072;
}

location / {
    proxy_pass http://127.0.0.1:8069;
}
```

}

**Comment by erkesado** [comment]
@yelizariev 

I figured out the issue. On the traceback, the problem occurs at `odoo/addons/auth_oauth/res_users.py`. 
I debugged `auth_oauth/res_users.py` with pdb. It gets stuck at the following line:
`File "/home/skysys/odoo-prd/odoo/addons/auth_oauth/res_users.py", line 34, in _auth_oauth_rpc`
`f = urllib2.urlopen(url)`
When it tries to open `url`, it gets stuck and connection is timed out. I printed the value of `url`. 
It is something like this: [http://example.com/oauth2/tokeninfo?access_token=rnj5KzfalT8ieyAv59nz5ev3uBPMhD](url)

Let's assume that [example.com](url) is SaaS Portal and [server.example.com](url) is SaaS Server.
Since SaaS Portal and SaaS Server are on the same machine, `url` should not be [http://example.com/oauth2/tokeninfo?access_token=rnj5KzfalT8ieyAv59nz5ev3uBPMhD](url).
But it should be [http://127.0.0.1/oauth2/tokeninfo?access_token=rnj5KzfalT8ieyAv59nz5ev3uBPMhD](url).
Therefore, I added the following entries to `/etc/hosts` file:
`127.0.0.1       example.com`
`127.0.0.1       server.example.com`
It fixed the issue. And now I can Login via SaaS Portal from SaaS Server. I can Create Template DB for any plans. 

Even though the above entries to the `/etc/hosts` file fixed my issue, there might be better solutions. Maybe I have to do some networking configurations such as DNS or something else. 
These networking topics are out of my scope and I hope that someone might suggest better solutions.

@all
Nice to have you guys

**Comment by yelizariev** [comment]
@erkesado we know about this issue and fixed it for 9.0

You can port that updates if you use 8.0 #/259

**Comment by yelizariev** [comment]
Actually, it's fixed only for sync_server part. While it's not fixed fix for oauth part see #264

**Comment by yelizariev** [comment]
note that your workaround with records in /etc/hosts could brake sync server method, if you use https

**Comment by sathwiksunderreddy** [comment]
Hi,
Iam using Saas Module, I am able to create server, plans and Templatedb but when doing SYNC of server it is throwing an error

can anyone help with this
The error log is:
Odoo Server Error
Traceback (most recent call last):
  File "/home/admin/odoo-8.0/openerp/http.py", line 544, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/admin/odoo-8.0/openerp/http.py", line 581, in dispatch
    result = self._call_function(**self.params)
  File "/home/admin/odoo-8.0/openerp/http.py", line 317, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/admin/odoo-8.0/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/admin/odoo-8.0/openerp/http.py", line 314, in checked_call
    return self.endpoint(*a, **kw)
  File "/home/admin/odoo-8.0/openerp/http.py", line 810, in __call__
    return self.method(*args, **kw)
  File "/home/admin/odoo-8.0/openerp/http.py", line 410, in response_wrap
    response = f(*args, **kw)
  File "/home/admin/odoo-8.0/addons/web/controllers/main.py", line 948, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/admin/odoo-8.0/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/home/admin/odoo-8.0/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/admin/odoo-8.0/openerp/api.py", line 439, in old_api
    result = new_api(recs, *args, **kwargs)
  File "/home/admin/odoo-8.0/openerp/api.py", line 443, in new_api
    result = [method(rec, *args, **kwargs) for rec in self]
  File "/home/admin/odoo-8.0/addons/saas_portal/models/saas_portal.py", line 127, in action_sync_server
    raise Warning('Reason: %s \n Message: %s' % (res.reason, res.content))
Warning: Reason: Connection Timed Out 
 Message: <HEAD><TITLE>Connection Timed Out</TITLE></HEAD>
<BODY BGCOLOR="white" FGCOLOR="black">
<FONT FACE="Helvetica,Arial"><B>
 Connection Timed Out</B></FONT>


</BODY>

**Comment by 360org** [comment]
Check your nginx configuration

Chau Le Van
W360S Corp
Sent from my iPhone

On Mar 14, 2017, at 18:50, sathwiksunderreddy <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,
Iam using Saas Module, I am able to create server, plans and Templatedb but when doing SYNC of server it is throwing an error

can anyone help with this
The error log is:
Odoo Server Error
Traceback (most recent call last):
File "/home/admin/odoo-8.0/openerp/http.py", line 544, in _handle_exception
return super(JsonRequest, self)._handle_exception(exception)
File "/home/admin/odoo-8.0/openerp/http.py", line 581, in dispatch
result = self._call_function(**self.params)
File "/home/admin/odoo-8.0/openerp/http.py", line 317, in _call_function
return checked_call(self.db, *args, **kwargs)
File "/home/admin/odoo-8.0/openerp/service/model.py", line 118, in wrapper
return f(dbname, *args, **kwargs)
File "/home/admin/odoo-8.0/openerp/http.py", line 314, in checked_call
return self.endpoint(*a, **kw)
File "/home/admin/odoo-8.0/openerp/http.py", line 810, in call
return self.method(*args, **kw)
File "/home/admin/odoo-8.0/openerp/http.py", line 410, in response_wrap
response = f(*args, **kw)
File "/home/admin/odoo-8.0/addons/web/controllers/main.py", line 948, in call_button
action = self._call_kw(model, method, args, {})
File "/home/admin/odoo-8.0/addons/web/controllers/main.py", line 936, in _call_kw
return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
File "/home/admin/odoo-8.0/openerp/api.py", line 268, in wrapper
return old_api(self, *args, **kwargs)
File "/home/admin/odoo-8.0/openerp/api.py", line 439, in old_api
result = new_api(recs, *args, **kwargs)
File "/home/admin/odoo-8.0/openerp/api.py", line 443, in new_api
result = [method(rec, *args, **kwargs) for rec in self]
File "/home/admin/odoo-8.0/addons/saas_portal/models/saas_portal.py", line 127, in action_sync_server
raise Warning('Reason: %s \n Message: %s' % (res.reason, res.content))
Warning: Reason: Connection Timed Out
Message: Connection Timed Out

Connection Timed Out
