### ISSUE TITLE
problem installing

### ISSUE THREAD

**Issue by augustynr** [it-projects-llc/odoo-saas-tools#275]
Hi  I have installed the odoo on ubuntu 14.04 using standard 
wget -O - https://nightly.odoo.com/odoo.key | apt-key add -
# echo "deb http://nightly.odoo.com/9.0/nightly/deb/ ./" >> /etc/apt/sources.list
# apt-get update && apt-get install odoo -y

I have downloaded saas tools uncompressed it and tried to run:
python saas.py --portal-create --server-create --plan-create --run --odoo-script=/usr/lib/python2.7/dist-packages/openerp --odoo-config=/etc/odoo/openerp-server.conf 

but I get following error:
saas.py >>> Read odoo config, /etc/odoo/openerp-server.conf

saas.py >>> Dropping  database saas-portal-9.local
Traceback (most recent call last):
  File "saas.py", line 448, in <module>
    main()
  File "saas.py", line 123, in main
    createdb(args.get('portal_db_name'), ['auth_signup', 'saas_portal', 'saas_portal_start', 'saas_portal_sale_online'])
  File "saas.py", line 167, in createdb
    pg_dropdb(dbname)
  File "saas.py", line 322, in pg_dropdb
    with local_pgadmin_cursor() as local_cr:
  File "/usr/lib/python2.7/contextlib.py", line 17, in **enter**
    return self.gen.next()
  File "saas.py", line 337, in local_pgadmin_cursor
    cnx = psycopg2.connect("dbname=postgres")
  File "/usr/lib/python2.7/dist-packages/psycopg2/**init**.py", line 179, in connect
    connection_factory=connection_factory, async=async)
psycopg2.OperationalError: FATAL:  role "root" does not exist

How would I resolve it?
Is there a set of instructions on how to install it?

**Comment by yelizariev** [comment]
@iledarn please assist

**Comment by iledarn** [comment]
@augustynr ,

The script was created to start by ordinary users i.e. not root.
Exit root then create postgres role for your ubuntu user. 
sudo su - postgres -c "createuser -s $USER"
Start the script again

Or you may start it like this from root (put your ubuntu user instead of yourubuntuuser):
 sudo su - yourubuntuuser -s /bin/bash -c  "python saas.py \
  --odoo-script=/usr/local/src/odoo/openerp-server \
  --odoo-config=/etc/odoo/odoo-server.conf \
  --portal-create --server-create --plan-create --run

**Comment by yelizariev** [comment]
@iledarn we have to update saas.py to handle such problem automatically. Moreover, he have to add support for remote db, i.e. read all db_\* params from config file and use it
- [ ] saas.py: use db_\* from config file

**Comment by augustynr** [comment]
Hi,
I have added the user as per your instruction though I run into more problems.
Odoo runs as odoo user. So my user cannot read /etc/odoo/openerp-server.conf
When I added user to odoo group it started to run but got another permission problem
sh: 1: /usr/lib/python2.7/dist-packages/openerp: Permission denied
That directory is owned by root.

sudo su - robert -s /bin/bash -c "python /home/robert/odoo-saas-tools-9.0/saas.py --portal-create --server-create --plan-create --run --odoo-script=/usr/lib/python2.7/dist-packages/openerp --odoo-config=/etc/odoo/openerp-server.conf"

saas.py >>> Read odoo config, /etc/odoo/openerp-server.conf

saas.py >>> Dropping  database saas-portal-9.local

saas.py >>> Result: DROP DATABASE

saas.py >>> Creating empty database saas-portal-9.local

saas.py >>> Result: CREATE DATABASE

saas.py >>> EXEC: , /usr/lib/python2.7/dist-packages/openerp --xmlrpc-port=8069 --config=/etc/odoo/openerp-server.conf -d saas-portal-9.local -i auth_signup,saas_portal,saas_portal_start,saas_portal_sale_online --without-demo=all --stop-after-init
sh: 1: /usr/lib/python2.7/dist-packages/openerp: Permission denied

saas.py >>> Dropping  database server-1.saas-portal-9.local

saas.py >>> Result: DROP DATABASE

saas.py >>> Creating empty database server-1.saas-portal-9.local

saas.py >>> Result: CREATE DATABASE

saas.py >>> EXEC: , /usr/lib/python2.7/dist-packages/openerp --xmlrpc-port=8069 --config=/etc/odoo/openerp-server.conf -d server-1.saas-portal-9.local -i saas_server --without-demo=all --stop-after-init
sh: 1: /usr/lib/python2.7/dist-packages/openerp: Permission denied

saas.py >>> Spawn, /usr/lib/python2.7/dist-packages/openerp --xmlrpc-port=8069 --config=/etc/odoo/openerp-server.conf

saas.py >>> Spawn pid: 8965

saas.py >>> Waiting for port, 127.0.0.1, 8069
Traceback (most recent call last):
  File "/home/robert/odoo-saas-tools-9.0/saas.py", line 448, in <module>
    main()
  File "/home/robert/odoo-saas-tools-9.0/saas.py", line 130, in main
    pid = spawn_cmd(cmd)
  File "/home/robert/odoo-saas-tools-9.0/saas.py", line 388, in spawn_cmd
    shell=shell)
  File "/usr/lib/python2.7/subprocess.py", line 710, in **init**
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1318, in _execute_child
Traceback (most recent call last):
  File "/home/robert/odoo-saas-tools-9.0/saas.py", line 136, in main
    os.close(errpipe_read)
OSError: [Errno 9] Bad file descriptor
    rpc_init_db(args.get('portal_db_name'), new_admin_password=args.get('admin_password'))
  File "/home/robert/odoo-saas-tools-9.0/saas.py", line 222, in rpc_init_db
    auth = rpc_auth(dbname)
  File "/home/robert/odoo-saas-tools-9.0/saas.py", line 203, in rpc_auth
    admin_uid = common.authenticate(dbname, admin_username, admin_password, {})
  File "/usr/lib/python2.7/xmlrpclib.py", line 1233, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1587, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1273, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1301, in single_request
    self.send_content(h, request_body)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1448, in send_content
    connection.endheaders(request_body)
  File "/usr/lib/python2.7/httplib.py", line 975, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 835, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 797, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 778, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 571, in create_connection
    raise err
error: [Errno 111] Connection refused

saas.py >>> KILL, 8965

**Comment by augustynr** [comment]
How do you install odoo for this to work right away?
Maybe that wold be easier ....

**Comment by iledarn** [comment]
@augustynr ,

I didn't know that you had 'odoo' user, usually we don't install odoo from *.deb.
Do the following (from root):

::

 # su - postgres
 # dropdb saas-portal-9.local
 # dropdb server-1.saas-portal-9.local
 # exit

Edit your /etc/hosts:
add the lines 
127.0.0.1 saas-portal-9.local
127.0.0.1 server-1.saas-portal-9.local
127.0.0.1 template-1.saas-portal-9.local
127.0.0.1 client-001.saas-portal-9.local
127.0.0.1 client-002.saas-portal-9.local
...

Then start saas.py again like this (from path where saas.py lays):

::

 # sudo su - odoo -s /bin/bash -c "python saas.py \
 --odoo-script=/usr/local/src/odoo/openerp-server \
 --odoo-config=/etc/odoo/odoo-server.conf \
 --portal-create --server-create --plan-create --run

**Comment by thanhchatvn** [comment]
good solutions

Vào Th 6, 13 thg 5, 2016 vào lúc 17:42 iledarn notifications@github.com
đã viết:

**Comment by augustynr** [comment]
Hi Thank you,

Would one of you be available to do this correctly for me, I have had nothing but problems?

I have tried to build it from the scripts which you have but it always fails.

I would pay for your time.

﻿Sincerely,

Robert Augustyn

p:519.997.3106 ext:802

m:519.817.2503

www.linqone.com http://www.linqone.com/ 

﻿

-----Original message-----

**Comment by yelizariev** [comment]
@augustynr you can contact us by email it@it-projects.info

**Comment by augustynr** [comment]
btw: what is the admin's password?

﻿Sincerely,

Robert Augustyn

p:519.997.3106 ext:802

m:519.817.2503

www.linqone.com http://www.linqone.com/ 

﻿

-----Original message-----

**Comment by augustynr** [comment]
Hi I did send you an email but nobody returns them ....

﻿

-----Original message-----

**Comment by yelizariev** [comment]
I worked last days on runbot https://github.com/yelizariev/odoo-saas-tools/issues/280
I will check email soon

**Comment by augustynr** [comment]
Thank you.

I have problems installing saas-tools on odoo 9.

﻿

﻿

-----Original message-----

**Comment by ygol** [comment]
When using saas.py, all databases are created with suffix .local how would I go to access them from the internet? 
I've set the dns record to point to the server with: 

> *.mydomain.com

Should I change the suffix in saas.py from **".local"** to **".mydomain.com"** ?
TIA

**Comment by yelizariev** [comment]
@ygol sure, use your suffix. Alternatively, specify portal and database names : `--portal-db-name`, `--server-db-name`, etc

**Comment by bitsnaps** [comment]
I had to change fews things to get `saas.py` working for me (ubuntu 16 & python 3.5 & odoo v11):
- Reinstalled gevent (`pip install gevent`)
- Replace `read()` by `readfp` in the script ([issue#16601757](https://stackoverflow.com/questions/16601757/python-configparser-nosectionerror-no-section-testinformation))
- Describe the full path everywhere (`odoo.conf` and command line)
- Also replace `openerp-server` by `odoo-bin` for v11 compatibility
now the script is running, and it creates a db with some issues...
