### ISSUE TITLE
mailgun: ignore errors from mailgun on database creating

### ISSUE THREAD

**Issue by yelizariev** [it-projects-llc/odoo-saas-tools#285]
process is aborted if mailgun return error.
It creates database, but haven't finished process of creating saas_portal.client and other

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 643, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 680, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 316, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 309, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 959, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 509, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/web/controllers/main.py", line 896, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/lib/python2.7/dist-packages/openerp/addons/web/controllers/main.py", line 884, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 381, in old_api
    result = method(recs, *args, **kwargs)
  File "/usr/local/src/ -addons/yelizariev/ -saas-tools/saas_portal/models/wizard.py", line 145, in apply
    async=self.async_creation)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/usr/local/src/ -addons/yelizariev/ -saas-tools/saas_portal/models/saas_portal.py", line 199, in create_new_database
    return self._create_new_database(**kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/usr/local/src/ -addons/yelizariev/ -saas-tools/saas_sysadmin_mailgun/models/saas_sysadmin_mailgun.py", line 68, in _create_new_database
    client_obj._create_route_on_mailgun()
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/usr/local/src/ -addons/yelizariev/ -saas-tools/saas_sysadmin_mailgun/models/saas_sysadmin_mailgun.py", line 38, in _create_route_on_mailgun
    mail_domain=self.mail_domain, request_scheme=self.server_id.request_scheme)
  File "/usr/local/src/ -addons/yelizariev/ -saas-tools/saas_sysadmin_mailgun/models/mailgun.py", line 213, in create_store_route
    "action": [action]})
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 107, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 53, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 426, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', error(104, 'Connection reset by peer'))
```

**Comment by yelizariev** [comment]
@iledarn

**Comment by iledarn** [comment]
This is done in
https://github.com/yelizariev/odoo-saas-tools/pull/286
