### ISSUE TITLE
Installation problem  INTERNAL SERVER ERROR 

### ISSUE THREAD

**Issue by nadiaafa** [it-projects-llc/odoo-saas-tools#322]
I have followed Ivan's instruction and read all the support docs .
I've used db-filter=%h.

create two database:
portal: saas-portal-8.local
server: s1.saas-portal-8.local
i configured nginx : 
`server {
listen 80 default_server;

server_name .local;
proxy_next_upstream error timeout invalid_header http_500 http$
proxy_redirect off;
proxy_set_header Host $host;

proxy_set_header X-Real-IP $remote_addr;

proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

proxy_set_header X-Forwarded-Proto $scheme;
location /longpolling {
proxy_pass http://127.0.0.1:8072;
}

location / {
proxy_pass http://127.0.0.1:80;
}

}
`

here is my hosts:

`# generated by odoo-saas-tools
127.0.0.1 saas-portal-8.local
127.0.0.1 s1.saas-portal-8.local
127.0.0.1 template-1.saas-portal-8.local
127.0.0.1 client-001.saas-portal-8.local
127.0.0.1 client-002.saas-portal-8.local
127.0.0.1 client-003.saas-portal-8.local
127.0.0.1 client-004.saas-portal-8.local
127.0.0.1 client-005.saas-portal-8.local
127.0.0.1 client-006.saas-portal-8.local
127.0.0.1 client-007.saas-portal-8.local
127.0.0.1 client-008.saas-portal-8.local
127.0.0.1 client-009.saas-portal-8.local
127.0.0.1 client-010.saas-portal-8.local
`

but on creating template db i get this error:
`2016-07-11 17:05:50,191 6423 ERROR saas-portal-8.local openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/opt/odoo/openerp/http.py", line 543, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/openerp/http.py", line 580, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/openerp/http.py", line 316, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/openerp/http.py", line 313, in checked_call
    return self.endpoint(*a, **kw)
  File "/opt/odoo/openerp/http.py", line 809, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/openerp/http.py", line 409, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/openerp/addons/web/controllers/main.py", line 948, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/openerp/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/opt/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/api.py", line 399, in old_api
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/odoo-saas-tools/saas_portal/models/saas_portal.py", line 367, in create_template
    return self.action_sync_server()
  File "/opt/odoo/openerp/api.py", line 266, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/odoo-saas-tools/saas_portal/models/saas_portal.py", line 372, in action_sync_server
    r.server_id.action_sync_server()
  File "/opt/odoo/openerp/api.py", line 266, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/api.py", line 443, in new_api
    result = [method(rec, *args, **kwargs) for rec in self]
  File "/opt/odoo/odoo-saas-tools/saas_portal/models/saas_portal.py", line 136, in action_sync_server
    raise Warning('Reason: %s \n Message: %s' % (res.reason, res.content))
Warning: Reason: INTERNAL SERVER ERROR 
 Message: expected string or buffer
`

can someone help me fix this issue please.

**Comment by yelizariev** [comment]
Can you provide full more logs?

**Comment by nadiaafa** [comment]
thank you for your replay

i had a problem on my computer so i started from the beginning, but i still have errors on creating db template:

**so i created two database:**
portal: odoo.local with module portal installed 

![image](https://cloud.githubusercontent.com/assets/20404183/16902977/47ff9e6e-4c68-11e6-8341-ee84bf493d63.png)

![image](https://cloud.githubusercontent.com/assets/20404183/16902982/70f7fe10-4c68-11e6-8339-162f1a45deb9.png)

![image](https://cloud.githubusercontent.com/assets/20404183/16902987/a447e122-4c68-11e6-8cc0-2f6819b25c12.png)

**i get this error when i click on create template db**

![image](https://cloud.githubusercontent.com/assets/20404183/16902996/c0a49d88-4c68-11e6-94ec-25c7baacc3dc.png)

**on the terminal it's :** 

```
`2016-07-17 20:50:10,225 21381 INFO odoo.local werkzeug: 127.0.0.1 - - [17/Jul/2016 20:50:10] "POST /web/dataset/search_read HTTP/1.0" 200 -
2016-07-17 20:50:45,116 21383 INFO ? openerp.sql_db: ConnectionPool(used=0/count=0/max=64): Closed 1 connections to 'user=odoo dbname=s1.odoo.local'
2016-07-17 20:50:45,145 21383 INFO ? openerp.sql_db: ConnectionPool(used=0/count=0/max=64): Closed 1 connections to 'user=odoo dbname=saas-portal-8.local'
2016-07-17 20:50:45,180 21383 INFO ? openerp.sql_db: ConnectionPool(used=0/count=0/max=64): Closed 1 connections to 'user=odoo dbname=odoo.local'
http://s1.odoo.local:80/saas_server/new_database
s1.odoo.local
80
{'access_token': u'IXbc1sDcmi5JMryJ3FrrckULXvxsZw', 'expires_in': 3600, 'token_type': 'Bearer', 'state': '{"lang": "en_US", "tz": false, "d": "t1.odoo.local", "demo": 0, "is_template_db": 1, "addons": []}', 'redirect_uri': 'http://s1.odoo.local:80/web', 'response_type': 'token', 'client_id': u'60a8affe-4c5a-11e6-ae3f-000c2903abb9', 'scope': 'userinfo force_login trial skiptheuse'}
plplplpl
<Request [GET]>
2016-07-17 20:50:48,565 21381 INFO odoo.local requests.packages.urllib3.connectionpool: Starting new HTTP connection (1): s1.odoo.local
2016-07-17 20:50:48,572 21379 INFO None openerp.http: Generating nondb routing
2016-07-17 20:50:48,590 21379 INFO None werkzeug: 127.0.0.1 - - [17/Jul/2016 20:50:48] "GET /saas_server/new_database HTTP/1.0" 404 -
2016-07-17 20:50:48,591 21381 ERROR odoo.local openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/opt/odoo/openerp/http.py", line 543, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/openerp/http.py", line 580, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/openerp/http.py", line 316, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/openerp/http.py", line 313, in checked_call
    return self.endpoint(*a, **kw)
  File "/opt/odoo/openerp/http.py", line 809, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/openerp/http.py", line 409, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/openerp/addons/web/controllers/main.py", line 948, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/openerp/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/opt/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/api.py", line 399, in old_api
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/odoo-saas-tools/saas_portal/models/saas_portal.py", line 367, in create_template
    raise Warning('Error on request: %s\nReason: %s \n Message: %s' % (req.url, res.reason, res.content))
Warning: Error on request: http://s1.odoo.local:80/saas_server/new_database
Reason: NOT FOUND 
 Message: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>404 Not Found</title>
<h1>Not Found</h1>
<p>The requested URL was not found on the server.</p><p>If you entered the URL manually please check your spelling and try again.</p>

2016-07-17 20:50:48,595 21381 INFO odoo.local werkzeug: 127.0.0.1 - - [17/Jul/2016 20:50:48] "POST /web/dataset/call_button HTTP/1.0" 200 -
127.0.0.1 - - [2016-07-17 20:50:49] "POST /longpolling/poll HTTP/1.0" 200 304 50.033838
2016-07-17 20:50:51,049 21384 INFO ? openerp.sql_db: ConnectionPool(used=0/count=0/max=64): Closed 1 connections to 'user=odoo dbname=s1.odoo.local'
2016-07-17 20:50:51,071 21384 INFO ? openerp.sql_db: ConnectionPool(used=0/count=0/max=64): Closed 1 connections to 'user=odoo dbname=saas-portal-8.local'
2016-07-17 20:50:51,096 21384 INFO ? openerp.sql_db: ConnectionPool(used=0/count=0/max=64): Closed 1 connections to 'user=odoo dbname=odoo.local'
127.0.0.1 - - [2016-07-17 20:51:39] "POST /longpolling/poll HTTP/1.0" 200 305 50.026838
2016-07-17 20:51:48,289 21383 INFO ? openerp.sql_db: ConnectionPool(used=0/count=0/max=64): Closed 1 connections to 'user=odoo dbname=s1.odoo.local'
2016-07-17 20:51:48,310 21383 INFO ? openerp.sql_db: ConnectionPool(used=0/count=0/max=64): Closed 1 connections to 'user=odoo dbname=saas-portal-8.local'
2016-07-17 20:51:48,334 21383 INFO ? openerp.sql_db: ConnectionPool(used=0/count=0/max=64): Closed 1 connections to 'user=odoo dbname=odoo.local'
2016-07-17 20:51:55,184 21384 INFO ? openerp.sql_db: ConnectionPool(used=0/count=0/max=64): Closed 1 connections to 'user=odoo dbna`


```

**server**: s1.odoo.local: i installed the saas!server module
this is the uuid i configured on my portal database

![image](https://cloud.githubusercontent.com/assets/20404183/16903045/4dafdbb0-4c6a-11e6-8043-b797f0647aa6.png)

**i configured nginx  like this :**  

```

`server {
listen 80 default_server;
server_name .local;

proxy_set_header Host $host;

proxy_set_header X-Real-IP $remote_addr;

proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

proxy_set_header X-Forwarded-Proto $scheme;

location /longpolling {
proxy_pass http://127.0.0.1:8072;
}

location / {
proxy_pass http://127.0.0.1:8069;
`
```

this id my host file:

![image](https://cloud.githubusercontent.com/assets/20404183/16903036/16a6bf12-4c6a-11e6-8d17-dfa586a868a7.png)

and this is my odoo configuration file:

![image](https://cloud.githubusercontent.com/assets/20404183/16903024/9b79ed78-4c69-11e6-8aac-405b9697407c.png)

**Comment by yelizariev** [comment]
> 2016-07-17 20:50:48,590 21379 INFO **None** werkzeug: 127.0.0.1 - - [17/Jul/2016 20:50:48] "GET /saas_server/new_database HTTP/1.0" 404 -

It looks like you haven't specified dbfilter https://github.com/it-projects-llc/odoo-saas-tools/blob/9.0/docs/odoo-configuration.rst#dbfilter

**Comment by nadiaafa** [comment]
i have it on my config file:
![11](https://cloud.githubusercontent.com/assets/20404183/16912035/e8e99ca0-4cd9-11e6-8a71-44142c300c35.png)
 it gives me the not found error, but when i add it to when i start the server:
./openerp-server --conf=/etc/openerp-server.conf  --db-filter=^%h$

when i click create template DB, i get this error:

```

`{'access_token': u'6fDtirGiZQ3SzIoI3MZ05PjhlTWcu5', 'expires_in': 3600, 'token_type': 'Bearer', 'state': '{"d": "s1.odoo.local", "client_id": "d1800016-4c59-11e6-81e8-000c2903abb9"}', 'redirect_uri': 'http://s1.odoo.local:80/web', 'response_type': 'token', 'client_id': u'd1800016-4c59-11e6-81e8-000c2903abb9', 'scope': 'userinfo force_login trial skiptheuse'}
plplplpl
<Request [GET]>
=======
2016-07-18 10:48:16,720 23943 INFO odoo.local requests.packages.urllib3.connectionpool: Starting new HTTP connection (1): s1.odoo.local
2016-07-18 10:48:16,736 23945 INFO s1.odoo.local openerp.addons.saas_server.controllers.main: sync_server post: {}
2016-07-18 10:48:16,736 23945 ERROR s1.odoo.local openerp.addons.saas_server.controllers.main: expected string or buffer
Traceback (most recent call last):
  File "/opt/odoo/odoo-saas-tools/saas_server/controllers/main.py", line 25, in wrap
    return f(*args, **kw)
  File "/opt/odoo/odoo-saas-tools/saas_server/controllers/main.py", line 264, in stats
    state = simplejson.loads(post.get('state'))
  File "/usr/lib/python2.7/dist-packages/simplejson/__init__.py", line 413, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/dist-packages/simplejson/decoder.py", line 402, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
TypeError: expected string or buffer
2016-07-18 10:48:16,737 23945 INFO s1.odoo.local werkzeug: 127.0.0.1 - - [18/Jul/2016 10:48:16] "GET /saas_server/sync_server HTTP/1.0" 500 -
d1800016-4c59-11e6-81e8-000c2903abb9
2016-07-18 10:48:16,747 23943 ERROR odoo.local openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/opt/odoo/openerp/http.py", line 543, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/openerp/http.py", line 580, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/openerp/http.py", line 316, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/openerp/http.py", line 313, in checked_call
    return self.endpoint(*a, **kw)
  File "/opt/odoo/openerp/http.py", line 809, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/openerp/http.py", line 409, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/openerp/addons/web/controllers/main.py", line 948, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/openerp/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/opt/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/api.py", line 399, in old_api
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/odoo-saas-tools/saas_portal/models/saas_portal.py", line 368, in create_template
    return self.action_sync_server()
  File "/opt/odoo/openerp/api.py", line 266, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/odoo-saas-tools/saas_portal/models/saas_portal.py", line 373, in action_sync_server
    r.server_id.action_sync_server()
  File "/opt/odoo/openerp/api.py", line 266, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/api.py", line 443, in new_api
    result = [method(rec, *args, **kwargs) for rec in self]
  File "/opt/odoo/odoo-saas-tools/saas_portal/models/saas_portal.py", line 137, in action_sync_server
    raise Warning('Reason: %s \n Message: %s' % (res.reason, res.content))
Warning: Reason: INTERNAL SERVER ERROR 
 Message: expected string or buffer
2016-07-18 10:48:16,755 23943 INFO odoo.local werkzeug: 127.0.0.1 - - [18/Jul/2016 10:48:16] "POST /web/dataset/call_button HTTP/1.0" 200 -
`
```

and when i use dbfilter here i can't access server database anymore(it's not on the database selector)

**Comment by yelizariev** [comment]
Can you print  
`print post.get('state')`
near
   `state = simplejson.loads(post.get('state'))`

**Comment by nadiaafa** [comment]
i commented the warning message, so it can enter the block try:

`    def action_sync_server(self):
        state = {
            'd': self.name,
            'client_id': self.client_id,
        }
        req, req_kwargs = self._request_server(path='/saas_server/sync_server', state=state, client_id=self.client_id)
        print '======='
        res = requests.Session().send(req, **req_kwargs)
        print self.client_id

```
    if res.ok != True:
        #raise Warning('Reason: %s \n Message: %s' % (res.reason, res.content))
        print "!!!!!!"
    try:
        data = simplejson.loads(res.text)
        print '§§§§§§§'
        print data.get('state')
```

`
this is the result, it blocks on simplejson.loads
`!!!!!!
2016-07-18 12:22:03,223 27178 ERROR odoo.local openerp.addons.saas_portal.models.saas_portal: Error on parsing response: ['http://s1.odoo.local:80/saas_server/sync_server', {'host': u's1.odoo.local', 'Content-Type': 'application/x-www-form-urlencoded', 'Content-Length': '347'}, 'access_token=Qhyzjp7QiRT46E6wDTwqXQVK7tTCO3&expires_in=3600&token_type=Bearer&state=%7B%22d%22%3A+%22s1.odoo.local%22%2C+%22client_id%22%3A+%22b089a392-4cdd-11e6-b34a-000c2903abb9%22%7D&redirect_uri=http%3A%2F%2Fs1.odoo.local%3A80%2Fweb&response_type=token&client_id=b089a392-4cdd-11e6-b34a-000c2903abb9&scope=userinfo+force_login+trial+skiptheuse']
expected string or buffer
`

**Comment by Matt-OBell** [comment]
Hi,
I am getting the same error when I try to create a new database from Create client in SaaS>>SaaS>>Plans

2016-10-29 04:04:32,284 15012 ERROR macca.odoosme.com openerp.addons.saas_server.controllers.main: 'NoneType' object has no attribute 'write'
Traceback (most recent call last):
  File "/opt/odoo/odoo/addons/mattobell/saas_server/controllers/main.py", line 25, in wrap
    return f(_args, *_kw)
  File "/opt/odoo/odoo/addons/mattobell/saas_server/controllers/main.py", line 64, in new_database
    client.create_database(template_db, demo, lang)
  File "/opt/odoo/odoo/openerp/api.py", line 248, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo/openerp/api.py", line 425, in new_api
    result = [method(rec, _args, *_kwargs) for rec in self]
  File "/opt/odoo/odoo/addons/mattobell/saas_server/models/saas_server.py", line 40, in create_database
    openerp.service.db.exp_duplicate_database(template_db, new_db)
  File "/opt/odoo/odoo/openerp/service/db.py", line 108, in exp_duplicate_database
    registry['ir.config_parameter'].init(cr, force=True)
  File "/opt/odoo/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo/addons/mattobell/saas_client/models/ir_configparameter.py", line 9, in init
    super(IrConfigParameter, self).init(cr, force=force)
  File "/opt/odoo/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo/addons/auth_oauth/ir_configparameter.py", line 14, in init
    oauth_oe.write({'client_id': dbuuid})
AttributeError: 'NoneType' object has no attribute 'write'
2016-10-29 04:04:32,290 15012 INFO macca.odoosme.com werkzeug: 10.244.0.1 - - [29/Oct/2016 04:04:32] "GET /saas_server/new_database HTTP/1.1" 500 -
2016-10-29 04:04:32,297 15012 ERROR odoosme.com openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/opt/odoo/odoo/openerp/http.py", line 648, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo/openerp/http.py", line 685, in dispatch
    result = self._call_function(*_self.params)
  File "/opt/odoo/odoo/openerp/http.py", line 321, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/opt/odoo/odoo/openerp/service/model.py", line 118, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/opt/odoo/odoo/openerp/http.py", line 314, in checked_call
    result = self.endpoint(_a, *_kw)
  File "/opt/odoo/odoo/openerp/http.py", line 964, in __call__
    return self.method(_args, *_kw)
  File "/opt/odoo/odoo/openerp/http.py", line 514, in response_wrap
    response = f(_args, *_kw)
  File "/opt/odoo/odoo/addons/web/controllers/main.py", line 892, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/odoo/addons/web/controllers/main.py", line 880, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "/opt/odoo/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo/openerp/api.py", line 381, in old_api
    result = method(recs, _args, *_kwargs)
  File "/opt/odoo/odoo/addons/mattobell/saas_portal/models/wizard.py", line 157, in apply
    async=self.async_creation)
  File "/opt/odoo/odoo/openerp/api.py", line 248, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo/addons/mattobell/saas_portal/models/saas_portal.py", line 208, in create_new_database
    return self._create_new_database(*_kwargs)
  File "/opt/odoo/odoo/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, *_kwargs)
  File "/opt/odoo/odoo/addons/mattobell/saas_portal_sale/models/saas_portal.py", line 23, in _create_new_database
    async=async)
  File "/opt/odoo/odoo/openerp/api.py", line 248, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo/addons/mattobell/saas_portal/models/saas_portal.py", line 295, in _create_new_database
    raise Warning('Error on request: %s\nReason: %s \n Message: %s' % (req.url, res.reason, res.content))
Warning: Error on request: http://217.65.41.15:8069/saas_server/new_database
Reason: INTERNAL SERVER ERROR 
 Message: 'NoneType' object has no attribute 'write'

**Comment by Arsalan88** [comment]
Hi nadiaafa,

I am facing the same issue... Seems like you are succeeded to have it done.. Can you help me in this ?

Thanks

**Comment by yelizariev** [comment]
For not found error like following
```

Warning: Error on request: http://s1.odoo.local:80/saas_server/new_database
Reason: NOT FOUND 
```
one need to check db-filter https://it-projects-llc.github.io/odoo-saas-tools/blog/reason-not-found

---------------

For error like following
```

File "/opt/odoo/odoo/addons/auth_oauth/ir_configparameter.py", line 14, in init
oauth_oe.write({'client_id': dbuuid})
AttributeError: 'NoneType' object has no attribute 'write'
```
one probably need to recreate *SaaS server* and *saas client*, because the error means that oauth provider record doesn't exist, but it is difficult to create it manualy with proper reference 

--------------

For error

> and when i use dbfilter here i can't access server database anymore(it's not on the database selector)

one has to check that following are correspond each other:
* db-filter
* host name
* server database name

**Comment by yelizariev** [comment]
I close this issue as it's a bit old and has three question at once. Open new issue if you face any of it at newest version

**Comment by mah007** [comment]
Traceback (most recent call last):
  File "/home/mahmoud/odoo/10c/odoo/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/mahmoud/odoo/10c/odoo/http.py", line 675, in dispatch
    result = self._call_function(**self.params)
  File "/home/mahmoud/odoo/10c/odoo/http.py", line 331, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/mahmoud/odoo/10c/odoo/service/model.py", line 119, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/mahmoud/odoo/10c/odoo/http.py", line 324, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/mahmoud/odoo/10c/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/home/mahmoud/odoo/10c/odoo/http.py", line 504, in response_wrap
    response = f(*args, **kw)
  File "/home/mahmoud/odoo/10c/addons/web/controllers/main.py", line 889, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/mahmoud/odoo/10c/addons/web/controllers/main.py", line 877, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/mahmoud/odoo/10c/odoo/api.py", line 681, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/home/mahmoud/odoo/10c/odoo/api.py", line 672, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<string>", line 2, in action_sync_server
  File "/home/mahmoud/odoo/10c/odoo/api.py", line 361, in loop
    result = [method(rec, *args, **kwargs) for rec in self]
  File "/home/mahmoud/odoo/10c/saas/saas_portal/models/saas_portal.py", line 136, in action_sync_server
    raise Warning('Reason: %s \n Message: %s' % (res.reason, res.content))
Warning: Reason: INTERNAL SERVER ERROR 
 Message: Expected singleton: saas_server.client()

**Comment by mah007** [comment]
what is that ????
Warning: Reason: INTERNAL SERVER ERROR
Message: Expected singleton: saas_server.client()

**Comment by drodoo** [comment]
I think you may have to create first a client before sync. Because it seems to be expecting a client.
