### ISSUE TITLE
Installation problem: Fault: <Fault 2: 'None'> on RPC Execute

### ISSUE THREAD

**Issue by difra** [it-projects-llc/odoo-saas-tools#337]
I think the problem is in this execution:

`saas.py >>> RPC Execute, saas_portal.server, create, [{'local_host': 'localhost', 'name': 'server-1.saas-portal-9.local', 'client_id': '862cdff6-704b-11e6-95ee-5254a20183f8', 'local_port': '8069'}], {}
`

Complete log:

```
odoo@Ubuntu-1604-64:~/odoo/ocb8/odoo-saas-tools$ python saas.py --portal-create --server-create --plan-create --run --odoo-script=/home/odoo/odoo/ocb8/openerp-server --odoo-config=/home/odoo/odoo/ocb8/odoo.conf 

2016-09-01 15:53:04
saas.py >>> Read odoo config, /home/odoo/odoo/ocb8/odoo.conf

2016-09-01 15:53:04
saas.py >>> Dropping  database saas-portal-9.local

2016-09-01 15:53:05
saas.py >>> Result: DROP DATABASE

2016-09-01 15:53:05
saas.py >>> Creating empty database saas-portal-9.local

2016-09-01 15:53:05
saas.py >>> Result: CREATE DATABASE

2016-09-01 15:53:05
saas.py >>> EXEC: , /home/odoo/odoo/ocb8/openerp-server --xmlrpc-port=8069 --database=saas-portal-9.local --db-filter=%h --workers=3 --config=/home/odoo/odoo/ocb8/odoo.conf -i saas_portal_start,saas_portal,saas_portal_sale_online --without-demo=all --stop-after-init

2016-09-01 15:53:46
saas.py >>> Dropping  database server-1.saas-portal-9.local

2016-09-01 15:53:48
saas.py >>> Result: DROP DATABASE

2016-09-01 15:53:48
saas.py >>> Creating empty database server-1.saas-portal-9.local

2016-09-01 15:53:49
saas.py >>> Result: CREATE DATABASE

2016-09-01 15:53:49
saas.py >>> EXEC: , /home/odoo/odoo/ocb8/openerp-server --xmlrpc-port=8069 --database=server-1.saas-portal-9.local --db-filter=%h --workers=3 --config=/home/odoo/odoo/ocb8/odoo.conf -i saas_server --without-demo=all --stop-after-init

2016-09-01 15:55:05
saas.py >>> Spawn, /home/odoo/odoo/ocb8/openerp-server --xmlrpc-port=8069 --database= --db-filter=%h --workers=3 --config=/home/odoo/odoo/ocb8/odoo.conf

2016-09-01 15:55:05
saas.py >>> Spawn pid: 11667

2016-09-01 15:55:05
saas.py >>> Waiting for port, 127.0.0.1, 8069

2016-09-01 15:55:07
saas.py >>> auth, ('saas-portal-9.local', <ServerProxy for localhost:8069/xmlrpc/2/object>, 1, 'admin')

2016-09-01 15:55:07
saas.py >>> RPC Execute, res.users, write, [[1], {'password': 'admin'}], {}

2016-09-01 15:55:07
saas.py >>> auth, ('saas-portal-9.local', <ServerProxy for localhost:8069/xmlrpc/2/object>, 1, 'admin')

2016-09-01 15:55:07
saas.py >>> RPC Execute, ir.config_parameter, set_param, ['saas_portal.base_saas_domain', 'saas-portal-9.local'], {}

2016-09-01 15:55:07
saas.py >>> auth, ('saas-portal-9.local', <ServerProxy for localhost:8069/xmlrpc/2/object>, 1, 'admin')

2016-09-01 15:55:07
saas.py >>> RPC Execute, ir.config_parameter, set_param, ['auth_signup.allow_uninvited', 'True'], {}

2016-09-01 15:55:08
saas.py >>> auth, ('server-1.saas-portal-9.local', <ServerProxy for localhost:8069/xmlrpc/2/object>, 1, 'admin')

2016-09-01 15:55:08
saas.py >>> RPC Execute, res.users, write, [[1], {'password': 'admin'}], {}

2016-09-01 15:55:10
saas.py >>> auth, ('server-1.saas-portal-9.local', <ServerProxy for localhost:8069/xmlrpc/2/object>, 1, 'admin')

2016-09-01 15:55:10
saas.py >>> RPC Execute, ir.model.data, xmlid_to_res_id, ['saas_server.saas_oauth_provider'], {}

2016-09-01 15:55:11
saas.py >>> auth, ('server-1.saas-portal-9.local', <ServerProxy for localhost:8069/xmlrpc/2/object>, 1, 'admin')

2016-09-01 15:55:11
saas.py >>> RPC Execute, auth.oauth.provider, read, [4], {}

2016-09-01 15:55:12
saas.py >>> auth, ('server-1.saas-portal-9.local', <ServerProxy for localhost:8069/xmlrpc/2/object>, 1, 'admin')

2016-09-01 15:55:12
saas.py >>> RPC Execute, auth.oauth.provider, write, [[4], {'local_port': '8069', 'local_ip': 'localhost', 'validation_endpoint': 'http://saas-portal-9.local/oauth2/tokeninfo', 'auth_endpoint': 'http://saas-portal-9.local/oauth2/auth'}], {}

2016-09-01 15:55:13
saas.py >>> auth, ('server-1.saas-portal-9.local', <ServerProxy for localhost:8069/xmlrpc/2/object>, 1, 'admin')

2016-09-01 15:55:13
saas.py >>> RPC Execute, ir.config_parameter, get_param, ['database.uuid'], {}

2016-09-01 15:55:13
saas.py >>> auth, ('saas-portal-9.local', <ServerProxy for localhost:8069/xmlrpc/2/object>, 1, 'admin')

2016-09-01 15:55:13
saas.py >>> RPC Execute, saas_portal.server, create, [{'local_host': 'localhost', 'name': 'server-1.saas-portal-9.local', 'client_id': '862cdff6-704b-11e6-95ee-5254a20183f8', 'local_port': '8069'}], {}
Traceback (most recent call last):
  File "saas.py", line 169, in main
    rpc_add_server_to_portal(args.get('portal_db_name'))
  File "saas.py", line 301, in rpc_add_server_to_portal
    rpc_execute_kw(auth, 'saas_portal.server', 'create', [{'name': server_db_name, 'client_id': uuid, 'local_port': xmlrpc_port, 'local_host':'localhost'}])
  File "saas.py", line 250, in rpc_execute_kw
    model, method, rpc_args, rpc_kwargs)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1243, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1602, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1283, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1316, in single_request
    return self.parse_response(response)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1493, in parse_response
    return u.close()
  File "/usr/lib/python2.7/xmlrpclib.py", line 800, in close
    raise Fault(**self._stack[0])
Fault: <Fault 2: 'None'>

2016-09-01 15:55:13
saas.py >>> KILL, 11667
```

Can someone help me fix this issue please?
Thank you.

**Comment by difra** [comment]
It was my fault.
I forgot "website_sale_require_login" and "website_sale_require_login" module installation.

Thank you.
