### ISSUE TITLE
V10: configuring saas main database

### ISSUE THREAD

**Issue by ygol** [it-projects-llc/odoo-saas-tools#354]
https://github.com/it-projects-llc/odoo-saas-tools/blob/10.0/docs/install.rst
In point 4:  

> open Settings/SaaS Portal Settings

getting error:

`
Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo/odoo-server/odoo/http.py", line 675, in dispatch
    result = self._call_function(**self.params)
  File "/odoo/odoo-server/odoo/http.py", line 331, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo/odoo-server/odoo/service/model.py", line 119, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo/odoo-server/odoo/http.py", line 324, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 504, in response_wrap
    response = f(*args, **kw)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 862, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 854, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 679, in call_kw
    return call_kw_model(method, model, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 664, in call_kw_model
    result = method(recs, *args, **kwargs)
  File "/odoo/odoo-server/odoo/addons/base/res/res_config.py", line 508, in default_get
    res.update(getattr(self, method)(fields))
TypeError: get_default_base_saas_domain() takes exactly 1 argument (2 given)
`

**Comment by yelizariev** [comment]
@iledarn currently is porting 10.0 branch

**Comment by ygol** [comment]
are those error report useful? Better to report them on @iledarn fork or here?

**Comment by yelizariev** [comment]
Report all issues here. 
I meant, that @iledarn currently work on 10.0 and will fix this issue
