### ISSUE TITLE
V10 installation saas.py

### ISSUE THREAD

**Issue by ygol** [it-projects-llc/odoo-saas-tools#355]
## Log during the script execution:

2016-10-26 23:27:54 saas.py >>> EXEC: , /odoo/odoo-server/odoo-bin --xmlrpc-port=8069 --database=saas-portal-10.saas.ygol.com --db-filter=%h --workers=0 --max-cron-threads=0 --config=/etc/odoo-server.conf -i saas_portal_start,saas_portal,saas_portal_sale_online --stop-after-init  
`Traceback (most recent call last):  
  File "/usr/lib/python2.7/logging/**init**.py", line 851, in emit msg = self.format(record)  
  File "/usr/lib/python2.7/logging/**init**.py", line 724, in format return fmt.format(record)  
  File "/odoo/odoo-server/odoo/netsvc.py", line 102, in format return logging.Formatter.format(self, record)  
  File "/usr/lib/python2.7/logging/**init**.py", line 464, in format record.message = record.getMessage()  
  File "/usr/lib/python2.7/logging/**init**.py", line 328, in getMessage msg = msg % self.args  
  File "/odoo/odoo-server/odoo/fields.py", line 388, in **str** return "%s.%s" % (self.model_name, self.name)  
  File "/odoo/odoo-server/odoo/fields.py", line 357, in **getattr** return self._attrs[name]
[... CUT...CUT...]
File "/odoo/odoo-server/odoo/fields.py", line 357, in __getattr__
    return self._attrs[name]
RuntimeError: maximum recursion depth exceeded
Logged from file fields.py, line 462
Warn: Can't find .pfb for face 'Times-Roman'
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 851, in emit
    msg = self.format(record)
  File "/usr/lib/python2.7/logging/**init**.py", line 724, in format
    return fmt.format(record)
  File "/odoo/odoo-server/odoo/netsvc.py", line 102, in format
    return logging.Formatter.format(self, record)
  File "/usr/lib/python2.7/logging/**init**.py", line 464, in format
    record.message = record.getMessage()
  File "/usr/lib/python2.7/logging/**init**.py", line 328, in getMessage
    msg = msg % self.args
  File "/odoo/odoo-server/odoo/fields.py", line 388, in **str**
    return "%s.%s" % (self.model_name, self.name)
  File "/odoo/odoo-server/odoo/fields.py", line 357, in **getattr**
    return self._attrs[name]
[... CUT...CUT...]
File "/odoo/odoo-server/odoo/fields.py", line 357, in __getattr__
    return self._attrs[name]
RuntimeError: maximum recursion depth exceeded
Logged from file fields.py, line 462

2016-10-26 23:28:45 saas.py >>> Dropping  database server-1.saas-portal-10.saas.ygol.com`
## then

same issue for **server-1.saas-portal-10...**
## Ends with:

`2016-10-26 23:29:26 saas.py >>> Waiting for port, 127.0.0.1, 8069
Traceback (most recent call last):
  File "/odoo/custom/odoo-saas-tools/saas.py", line 168, in main
    rpc_init_db(args.get('portal_db_name'), new_admin_password=args.get('admin_password'))
  File "/odoo/custom/odoo-saas-tools/saas.py", line 263, in rpc_init_db
    auth = rpc_auth(dbname)
  File "/odoo/custom/odoo-saas-tools/saas.py", line 244, in rpc_auth
    admin_uid = common.authenticate(dbname, admin_username, admin_password, {})
  File "/usr/lib/python2.7/xmlrpclib.py", line 1233, in **call**
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1587, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1273, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1301, in single_request
    self.send_content(h, request_body)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1448, in send_content
    connection.endheaders(request_body)
  File "/usr/lib/python2.7/httplib.py", line 975, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 835, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 797, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 778, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 571, in create_connection
    raise err
error: [Errno 111] Connection refused

2016-10-26 23:29:26
saas.py >>> KILL, 25663`

when starting odoo directly, both databases are there with the modules saas_portal and saas_server properly installed in each. There are no data in the modules (servers/plan/OAuth...)

**Comment by yelizariev** [comment]
@ygol we are able to repeat the problem and are trying to resolve it

**Comment by yelizariev** [comment]
cc @iledarn

**Comment by yelizariev** [comment]
@ygol there is bug in odoo, which were introduced by this commit: https://github.com/odoo/odoo/commit/cae04ba1d3782f89e78b7ecf68edb89269b2fff7

Odoo trying to print warning and raise recursion error. 
We will fix the issue that odoo trying to warn about.
You can try to send issue to odoo about the issue with warning

**Comment by yelizariev** [comment]
I have found the issue report https://github.com/odoo/odoo/issues/14036
