### ISSUE TITLE
V9 saas_portal_start: create database error

### ISSUE THREAD

**Issue by ygol** [it-projects-llc/odoo-saas-tools#371]
As per [documentation](https://github.com/it-projects-llc/odoo-saas-tools/blob/9.0/docs/features.rst):

> by client after choosing subdomain (similar to https://www.odoo.com/page/start ) - module saas_portal_start

![image](https://cloud.githubusercontent.com/assets/2945174/20007547/6ed0bbb6-a2a5-11e6-946e-5b4ac05b5a03.png)

generate the following error (log):

`
Traceback (most recent call last):
  File "/odoo9/odoo9-server/addons/website/models/ir_http.py", line 242, in _handle_exception
    response = super(ir_http, self)._handle_exception(exception)
  File "/odoo9/odoo9-server/openerp/addons/base/ir/ir_http.py", line 158, in _handle_exception
    return request._handle_exception(exception)
  File "/odoo9/odoo9-server/openerp/http.py", line 786, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/odoo9/odoo9-server/openerp/addons/base/ir/ir_http.py", line 183, in _dispatch
    result = request.dispatch()
  File "/odoo9/odoo9-server/openerp/http.py", line 845, in dispatch
    r = self._call_function(**self.params)
  File "/odoo9/odoo9-server/openerp/http.py", line 321, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo9/odoo9-server/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo9/odoo9-server/openerp/http.py", line 314, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo9/odoo9-server/openerp/http.py", line 964, in __call__
    return self.method(*args, **kw)
  File "/odoo9/odoo9-server/openerp/http.py", line 514, in response_wrap
    response = f(*args, **kw)
  File "/odoo9/custom/odoo-saas-tools/saas_portal_sale/controllers/main.py", line 12, in add_new_client
    plan = self.get_plan(int(post.get('plan_id', 0) or 0))
ValueError: invalid literal for int() with base 10: 'undefined'
`

- Did I mis-configured?
- Where is the default plan defined?

**Comment by ygol** [comment]
seem to be duplicate of  https://github.com/it-projects-llc/odoo-saas-tools/issues/234 ?!
