### ISSUE TITLE
Error install saas tools one odoo V10

### ISSUE THREAD

**Issue by 360org** [it-projects-llc/odoo-saas-tools#372]
hello i need help. i try to install saas tool on odoo v10 but allways get error
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 675, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 331, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/service/model.py", line 119, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 324, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 504, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/web/controllers/main.py", line 866, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/lib/python2.7/dist-packages/odoo/addons/web/controllers/main.py", line 854, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/api.py", line 679, in call_kw
    return call_kw_model(method, model, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/api.py", line 664, in call_kw_model
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/module/module.py", line 709, in install_from_urls
    post_install_action = to_install.button_immediate_install()
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/module/module.py", line 410, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/module/module.py", line 484, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/usr/lib/python2.7/dist-packages/odoo/modules/registry.py", line 78, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/usr/lib/python2.7/dist-packages/odoo/modules/loading.py", line 337, in load_modules
    loaded_modules, update_module)
  File "/usr/lib/python2.7/dist-packages/odoo/modules/loading.py", line 235, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/usr/lib/python2.7/dist-packages/odoo/modules/loading.py", line 156, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/usr/lib/python2.7/dist-packages/odoo/modules/loading.py", line 95, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/usr/lib/python2.7/dist-packages/odoo/tools/convert.py", line 848, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/usr/lib/python2.7/dist-packages/odoo/tools/convert.py", line 918, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/usr/lib/python2.7/dist-packages/odoo/tools/convert.py", line 799, in parse
    self.parse(rec, mode)
  File "/usr/lib/python2.7/dist-packages/odoo/tools/convert.py", line 802, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/usr/lib/python2.7/dist-packages/odoo/tools/convert.py", line 698, in _tag_record
    f_val = self.id_get(f_ref)
  File "/usr/lib/python2.7/dist-packages/odoo/tools/convert.py", line 785, in id_get
    res = self.model_id_get(id_str, raise_if_not_found)
  File "/usr/lib/python2.7/dist-packages/odoo/tools/convert.py", line 791, in model_id_get
    return self.env['ir.model.data'].xmlid_to_res_model_res_id(id_str, raise_if_not_found=raise_if_not_found)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/ir/ir_model.py", line 1027, in xmlid_to_res_model_res_id
    return self.xmlid_lookup(xmlid)[1:3]
  File "<decorator-gen-5>", line 2, in xmlid_lookup
  File "/usr/lib/python2.7/dist-packages/odoo/tools/cache.py", line 87, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/ir/ir_model.py", line 1016, in xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % xmlid)
ParseError: "External ID not found in the system: saas_portal.model_saas_portal_client" while parsing /var/lib/odoo/.local/share/Odoo/addons/10.0/saas_portal/data/mail_template_data.xml:3, near
<record id="email_template_create_saas" model="mail.template">
            <field name="name">Send SaaS credentials to the buyer of the SaaS</field>
            <field name="email_from">${(object.user_id.email or '')|safe}</field>
            <field name="subject">Credentials:</field>
            <field name="partner_to">${object.partner_id.id}</field>
            <field name="model_id" ref="saas_portal.model_saas_portal_client"/>
            <field name="auto_delete" eval="True"/>
            <field name="lang">${object.partner_id.lang}</field>
            <field name="body_html">

            &lt;p&gt;Web:
            &lt;a href="${object.public_url}"&gt;${object.public_url}&lt;/a&gt;
            &lt;/p&gt;

            </field>
        </record>

**Comment by 360org** [comment]
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 675, in dispatch
    result = self._call_function(*_self.params)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 331, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/service/model.py", line 119, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 324, in checked_call
    result = self.endpoint(_a, *_kw)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 933, in __call__
    return self.method(_args, *_kw)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 504, in response_wrap
    response = f(_args, *_kw)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/web/controllers/main.py", line 866, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/lib/python2.7/dist-packages/odoo/addons/web/controllers/main.py", line 854, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/api.py", line 679, in call_kw
    return call_kw_model(method, model, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/api.py", line 664, in call_kw_model
    result = method(recs, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/module/module.py", line 709, in install_from_urls
    post_install_action = to_install.button_immediate_install()
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/module/module.py", line 410, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/module/module.py", line 484, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/usr/lib/python2.7/dist-packages/odoo/modules/registry.py", line 78, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/usr/lib/python2.7/dist-packages/odoo/modules/loading.py", line 337, in load_modules
    loaded_modules, update_module)
  File "/usr/lib/python2.7/dist-packages/odoo/modules/loading.py", line 235, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/usr/lib/python2.7/dist-packages/odoo/modules/loading.py", line 122, in load_module_graph
    load_openerp_module(package.name)
  File "/usr/lib/python2.7/dist-packages/odoo/modules/module.py", line 367, in load_openerp_module
    __import__('odoo.addons.' + module_name)
  File "/usr/lib/python2.7/dist-packages/odoo/modules/module.py", line 81, in load_module
    execfile(modfile, new_mod.**dict**)
  File "/var/lib/odoo/.local/share/Odoo/addons/10.0/oauth_provider/**init**.py", line 3, in <module>
    from . import controllers
  File "/var/lib/odoo/.local/share/Odoo/addons/10.0/oauth_provider/controllers/**init**.py", line 2, in <module>
    from . import main
  File "/var/lib/odoo/.local/share/Odoo/addons/10.0/oauth_provider/controllers/main.py", line 3, in <module>
    import simplejson
ImportError: No module named simplejson

**Comment by 360org** [comment]
anyone have the error before help plz ?

**Comment by iledarn** [comment]
@W360S , 

> ImportError: No module named simplejson

Install it by:
`sudo pip install simplejson`

**Comment by 360org** [comment]
Thanks for your help :) i need to spend time on this :)
