### ISSUE TITLE
Transport agent has not been configured

### ISSUE THREAD

**Issue by 360org** [it-projects-llc/odoo-saas-tools#384]
where i can config Transport agent has ? plz help

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 675, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 331, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/service/model.py", line 119, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 324, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 504, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/web/controllers/main.py", line 866, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/lib/python2.7/dist-packages/odoo/addons/web/controllers/main.py", line 854, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/api.py", line 681, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/api.py", line 672, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/odoo/odoo-saas-tools/saas_portal_backup/models/saas_portal.py", line 14, in action_backup
    self._backup()
  File "/home/odoo/odoo-saas-tools/saas_portal/models/saas_portal.py", line 420, in _backup
    raise Warning(data)
Warning: [{u'status': u'fail', u'message': u"('Transport agent has not been configured', None)", u'name': u'001.standard.w360s.com.vn'}]

**Comment by yelizariev** [comment]
You need to install this module: https://github.com/it-projects-llc/odoo-saas-tools/tree/10.0/saas_server_backup_s3

**Comment by 360org** [comment]
Hello so that mean i have to use  Amazon S3 service? what happen if i don't use these service? i just want to backup with my own server.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 675, in dispatch
    result = self._call_function(*_self.params)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 331, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/service/model.py", line 119, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 324, in checked_call
    result = self.endpoint(_a, *_kw)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 933, in __call__
    return self.method(_args, *_kw)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 504, in response_wrap
    response = f(_args, *_kw)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/web/controllers/main.py", line 866, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/lib/python2.7/dist-packages/odoo/addons/web/controllers/main.py", line 854, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/api.py", line 681, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/api.py", line 672, in call_kw_multi
    result = method(recs, _args, *_kwargs)
  File "/home/odoo/odoo-saas-tools/saas_portal/models/wizard.py", line 37, in execute_action
    res = getattr(self, method)()
  File "/home/odoo/odoo-saas-tools/saas_portal/models/wizard.py", line 61, in upgrade_database
    res = self.database_ids.upgrade(payload=payload)
  File "/home/odoo/odoo-saas-tools/saas_portal_backup/models/saas_portal.py", line 29, in upgrade
    database_obj._backup()
  File "/home/odoo/odoo-saas-tools/saas_portal/models/saas_portal.py", line 420, in _backup
    raise Warning(data)
Warning: [{u'status': u'fail', u'message': u"(u'Please provide your AWS Access Key and ID         and also the S3 bucket to be used', None)", u'name': u'liongroup.vn'}]

**Comment by yelizariev** [comment]
You can use this module then https://github.com/it-projects-llc/odoo-saas-tools/tree/10.0/saas_server_backup_ftp
don't forget to remove saas_server_backup_s3 first

**Comment by 360org** [comment]
No i mean im using digital ocean vps the server already backup everyday so i dont need other service. how can i disable this & th saas system still work?

**Comment by yelizariev** [comment]
Then, you need to remove saas_portal_backup module

**Comment by 360org** [comment]
Thanks i help me :) work fine now :)
