### ISSUE TITLE
error saas support module installation

### ISSUE THREAD

**Issue by 360org** [it-projects-llc/odoo-saas-tools#385]
Hello i try to install saas support module but it has un error like below and the live chat module not working too.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 675, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 331, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/service/model.py", line 119, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 324, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 504, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/web/controllers/main.py", line 866, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/lib/python2.7/dist-packages/odoo/addons/web/controllers/main.py", line 854, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/api.py", line 681, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/api.py", line 672, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/module/module.py", line 410, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/module/module.py", line 484, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/usr/lib/python2.7/dist-packages/odoo/modules/registry.py", line 78, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/usr/lib/python2.7/dist-packages/odoo/modules/loading.py", line 337, in load_modules
    loaded_modules, update_module)
  File "/usr/lib/python2.7/dist-packages/odoo/modules/loading.py", line 235, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/usr/lib/python2.7/dist-packages/odoo/modules/loading.py", line 122, in load_module_graph
    load_openerp_module(package.name)
  File "/usr/lib/python2.7/dist-packages/odoo/modules/module.py", line 367, in load_openerp_module
    __import__('odoo.addons.' + module_name)
  File "/usr/lib/python2.7/dist-packages/odoo/modules/module.py", line 60, in load_module
    f, path, (_suffix, _mode, type_) = imp.find_module(addon_name, ad_paths)
ImportError: No module named saas_support

**Comment by yelizariev** [comment]
Fixed https://github.com/it-projects-llc/odoo-saas-tools/commit/87e43e9b69f9a4d0b6e9c42b97693a83eddeb6c7

**Comment by 360org** [comment]
Hello what i need to do? i have this file too but when i try to install i has the same error
here is my file

# -_\- coding: utf-8 -_-

##############################################################################
#

# OpenERP, Open Source Management Solution

# Copyright (C) 2004-2010, 2014 Tiny SPRL (http://tiny.be).

#

# This program is free software: you can redistribute it and/or modify

# it under the terms of the GNU Affero General Public License as

# published by the Free Software Foundation, either version 3 of the

# License, or (at your option) any later version.

#

# This program is distributed in the hope that it will be useful,

# but WITHOUT ANY WARRANTY; without even the implied warranty of

# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the

# GNU Affero General Public License for more details.

#

# You should have received a copy of the GNU Affero General Public License

# along with this program.  If not, see http://www.gnu.org/licenses/.

#
##############################################################################

{
    'name': 'Saas Support',
    'version': '0.1',
    'author': 'OpenJAF',
    'license': 'LGPL-3',
    'website': 'http://www.openjaf.com',
    'category': 'Integration',
    'description': """
        Live support
    """,
    'depends': [],
    'data': [
        'view/support.xml',
    ],
    'installable': True
}

**Comment by yelizariev** [comment]
You shall remove the module and don't try to install it

**Comment by 360org** [comment]
so that mean i dont need to install this module? how can customer communicate to admin system if they need?

**Comment by yelizariev** [comment]
We don't have a solution for livechat support in customer backend this at the moment. You can try to install livechat module on main website
