### ISSUE TITLE
Error 500 internal server error

### ISSUE THREAD

**Issue by 360org** [it-projects-llc/odoo-saas-tools#399]
Hello i have problems with customer account when thay login to there account try to navigate to domain http://domain.com/my/domain it show up Error 500 internal server error
what can i do for this? plz see attach file
![2016-11-18_20-36-47](https://cloud.githubusercontent.com/assets/8590556/20431899/2a4512a0-adcf-11e6-8c30-a306700839de.png)

**Comment by 360org** [comment]
here is the error info
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/odoo/addons/website/models/ir_http.py", line 264, in _handle_exception
    response = super(Http, cls)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/ir/ir_http.py", line 169, in _handle_exception
    return request._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 766, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/ir/ir_http.py", line 195, in _dispatch
    result = request.dispatch()
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 825, in dispatch
    r = self._call_function(*_self.params)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 331, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/service/model.py", line 119, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 324, in checked_call
    result = self.endpoint(_a, *_kw)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 933, in __call__
    return self.method(_args, *_kw)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 504, in response_wrap
    response = f(_args, *_kw)
  File "/home/odoo/odoo-saas-tools/saas_portal_portal/controllers/main.py", line 42, in change_domain
    return request.website.render("saas_portal_portal.change_domain", values)
AttributeError: 'website' object has no attribute 'render'

**Comment by yelizariev** [comment]
looks like unported 10.0 feature
cc @iledarn

**Comment by 360org** [comment]
Yeap :) waiting for it fixed :) @yelizariev

**Comment by ovnicraft** [comment]
@W360S was this fixed ?

**Comment by 360org** [comment]
not yet

**Comment by 360org** [comment]
fixed in #452 #488

**Comment by ovnicraft** [comment]
Good if edit the title issue with version affected.
