### ISSUE TITLE
error create db from customer UI

### ISSUE THREAD

**Issue by 360org** [it-projects-llc/odoo-saas-tools#403]
hello i need help, i try to login with customer to create database but it show up error like this. plz help.

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/odoo/addons/website/models/ir_http.py", line 264, in _handle_exception
    response = super(Http, cls)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/ir/ir_http.py", line 169, in _handle_exception
    return request._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 766, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/ir/ir_http.py", line 195, in _dispatch
    result = request.dispatch()
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 825, in dispatch
    r = self._call_function(**self.params)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 331, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/service/model.py", line 119, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 324, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 504, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/odoo-saas-tools/saas_portal_sale/controllers/main.py", line 12, in add_new_client
    plan = self.get_plan(int(post.get('plan_id', 0) or 0))
ValueError: invalid literal for int() with base 10: 'undefined'

**Comment by yelizariev** [comment]
Workaround: use /page/start?plan_id=1 url

**Comment by augustosamame** [comment]
the workaround works. However, it immediately redirects to newly created database subdomain without giving enough time to the route53 subdomain to be created. Then you get a DNS error in the browser. Suggest checking DNS record has been created before redirect
