### ISSUE TITLE
website.com/saas_portal_templates/select-template

### ISSUE THREAD

**Issue by zimbora69** [it-projects-llc/odoo-saas-tools#408]
**Description**
After installing saas_portal_templates

**Issue**

Traceback (most recent call last):
  File "/opt/odoo/odoo100/parts/odoo/addons/website/models/ir_http.py", line 265, in _handle_exception
    response = super(Http, cls)._handle_exception(exception)
  File "/opt/odoo/odoo100/parts/odoo/odoo/addons/base/ir/ir_http.py", line 169, in _handle_exception
    return request._handle_exception(exception)
  File "/opt/odoo/odoo100/parts/odoo/odoo/http.py", line 766, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo100/parts/odoo/odoo/addons/base/ir/ir_http.py", line 195, in _dispatch
    result = request.dispatch()
  File "/opt/odoo/odoo100/parts/odoo/odoo/http.py", line 825, in dispatch
    r = self._call_function(**self.params)
  File "/opt/odoo/odoo100/parts/odoo/odoo/http.py", line 331, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo100/parts/odoo/odoo/service/model.py", line 119, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo100/parts/odoo/odoo/http.py", line 324, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo100/parts/odoo/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo100/parts/odoo/odoo/http.py", line 504, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo100/addons/odoo-saas-tools/saas_portal_templates/controllers/main.py", line 16, in select_template
    return request.website.render("saas_portal_templates.select_template", values)
AttributeError: 'website' object has no attribute 'render'

**Comment by ajaychauhan727** [comment]
Please remove website from that line make it like below.
return request.render("saas_portal_templates.select_template", values)

**Comment by mah007** [comment]
remove website from that line is not even change the message

**Comment by njeudy** [comment]
@zimbora69 did you still encounter this issue ?

**Comment by GoodERPJeff** [comment]
The same

**Comment by zimbora69** [comment]
@njeudy Hello, just tested your fork (branch 11.0-fixes-run01) and while installing saas_portal_templates I got no issue.

**Comment by zimbora69** [comment]
When I enter on domain.com/saas_portal_templates/select-template
Issues still exists, yes. Version 11.
Duplicated #654
