### ISSUE TITLE
Need help cannot access to client db

### ISSUE THREAD

**Issue by 360org** [it-projects-llc/odoo-saas-tools#417]
Hello i have problems when try to access to client yesterday it work find but when i comeback to day try to access it show message like this plz help.
```

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 675, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 331, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/service/model.py", line 119, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 324, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 504, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/web/controllers/main.py", line 804, in search_read
    return self.do_search_read(model, fields, offset, limit, domain, sort)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/web/controllers/main.py", line 826, in do_search_read
    offset=offset or 0, limit=limit or False, order=sort or False)
  File "/usr/lib/python2.7/dist-packages/odoo/models.py", line 4662, in search_read
    result = records.read(fields)
  File "/usr/lib/python2.7/dist-packages/odoo/models.py", line 3002, in read
    values[name] = field.convert_to_read(record[name], record, use_name_get)
  File "/usr/lib/python2.7/dist-packages/odoo/models.py", line 5177, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/usr/lib/python2.7/dist-packages/odoo/fields.py", line 869, in __get__
    self.determine_value(record)
  File "/usr/lib/python2.7/dist-packages/odoo/fields.py", line 980, in determine_value
    self.compute_value(recs)
  File "/usr/lib/python2.7/dist-packages/odoo/fields.py", line 935, in compute_value
    self._compute_value(records)
  File "/usr/lib/python2.7/dist-packages/odoo/fields.py", line 929, in _compute_value
    self.compute(records)
  File "/usr/lib/python2.7/dist-packages/odoo/fields.py", line 579, in _compute_related
    other, field = self.traverse_related(other)
  File "/usr/lib/python2.7/dist-packages/odoo/fields.py", line 568, in traverse_related
    record = record[name][:1]
  File "/usr/lib/python2.7/dist-packages/odoo/models.py", line 5177, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/usr/lib/python2.7/dist-packages/odoo/fields.py", line 869, in __get__
    self.determine_value(record)
  File "/usr/lib/python2.7/dist-packages/odoo/fields.py", line 971, in determine_value
    record._prefetch_field(self)
  File "/usr/lib/python2.7/dist-packages/odoo/models.py", line 3051, in _prefetch_field
    result = records.read([f.name for f in fs], load='_classic_write')
  File "/usr/lib/python2.7/dist-packages/odoo/models.py", line 2991, in read
    self._read_from_database(stored, inherited)
  File "/usr/lib/python2.7/dist-packages/odoo/models.py", line 3119, in _read_from_database
    cr.execute(query_str, params)
  File "/usr/lib/python2.7/dist-packages/odoo/sql_db.py", line 141, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/sql_db.py", line 218, in execute
    res = self._obj.execute(query, params)
ProgrammingError: column saas_portal_client.period does not exist
LINE 1: ...t"."expiration_datetime" as "expiration_datetime","saas_port...
                                                             ^
```

**Comment by 360org** [comment]
Hello really need help i don't know where is the error come from 
here is video [https://www.youtube.com/watch?v=0jAqYEjZCn4&feature=youtu.be](https://www.youtube.com/watch?v=0jAqYEjZCn4&feature=youtu.be)

**Comment by yelizariev** [comment]
I guess you need to update saas_client module. As you don't have access to it, you probably need to do it via command line by running odoo with ``-u saas_client -d CLIENT_DATABASE_NAME`` keys

**Comment by 360org** [comment]
the old one work fine it just error when i remove the old one & clone new one with the update. so what do i need to do?

**Comment by yelizariev** [comment]
As I understand, your databases are created with old code. After updatnig code, you need to updates modules in each database

**Comment by 360org** [comment]
so how can i update the module for each database? & which module do i need to update @yelizariev ? is there anyway to update all module via terminal commend? what happen if in future if i have 100+ customer & have to update manual every-time when saas has new update?

**Comment by yelizariev** [comment]
For terminal command I answered here: https://github.com/it-projects-llc/odoo-saas-tools/issues/417#issuecomment-264621388

But you can update module ``saas_client`` via Upgrade Wizard on SaaS/Clients menu. It allows to upgrade set of clients at once

**Comment by 360org** [comment]
Thanks for your help :) so that mean i just need to run -u saas_client -d CLIENT_DATABASE_NAME and it will upgrade all? and everything ok?
if i update via saas client so i need to go to apps -> saas client -> manual upgrade right?

**Comment by 360org** [comment]
hello i try to rung run -u saas_client -d CLIENT_DATABASE_NAME  this commend but nothing happen & had an error -u: command not found

**Comment by yelizariev** [comment]
I meant that you need to add theseparameters to odoo command you use, e.g.
`./openerp-server  -u saas_client -d CLIENT_DATABASE_NAME`

**Comment by 360org** [comment]
i have fixed this. the error come from new saas base.
