### ISSUE TITLE
ImportError: No module named http

### ISSUE THREAD

**Issue by mdemirell** [it-projects-llc/odoo-saas-tools#431]
Error when installing SaaS Portal Module
**ImportError: No module named http**

**Result**:
Odoo Server Error
Traceback (most recent call last):
  File "/opt/odoo9s/odoo9s-server/odoo/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo9s/odoo9s-server/odoo/http.py", line 675, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo9s/odoo9s-server/odoo/http.py", line 331, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo9s/odoo9s-server/odoo/service/model.py", line 119, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo9s/odoo9s-server/odoo/http.py", line 324, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo9s/odoo9s-server/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo9s/odoo9s-server/odoo/http.py", line 504, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo9s/odoo9s-server/addons/web/controllers/main.py", line 857, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo9s/odoo9s-server/addons/web/controllers/main.py", line 845, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo9s/odoo9s-server/odoo/api.py", line 681, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo9s/odoo9s-server/odoo/api.py", line 672, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo9s/odoo9s-server/odoo/addons/base/module/module.py", line 410, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/opt/odoo9s/odoo9s-server/odoo/addons/base/module/module.py", line 484, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/opt/odoo9s/odoo9s-server/odoo/modules/registry.py", line 78, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo9s/odoo9s-server/odoo/modules/loading.py", line 337, in load_modules
    loaded_modules, update_module)
  File "/opt/odoo9s/odoo9s-server/odoo/modules/loading.py", line 235, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/opt/odoo9s/odoo9s-server/odoo/modules/loading.py", line 122, in load_module_graph
    load_openerp_module(package.name)
  File "/opt/odoo9s/odoo9s-server/odoo/modules/module.py", line 367, in load_openerp_module
    __import__('odoo.addons.' + module_name)
  File "/opt/odoo9s/odoo9s-server/odoo/modules/module.py", line 81, in load_module
    execfile(modfile, new_mod.__dict__)
  File "/opt/odoo9s/custom/addons/saas_portal/__init__.py", line 2, in <module>
    from . import controllers
  File "/opt/odoo9s/custom/addons/saas_portal/controllers/__init__.py", line 2, in <module>
    from . import main
  File "/opt/odoo9s/custom/addons/saas_portal/controllers/main.py", line 6, in <module>
    from openerp.addons.web import http
  File "/opt/odoo9s/odoo9s-server/odoo/modules/module.py", line 109, in load_module
    mod = importlib.import_module(canonical)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named http

**Comment by yelizariev** [comment]
Are you sure that you use  9.0 version both for saas and odoo installation?

**Comment by yelizariev** [comment]
That is how did you get ``/opt/odoo9s/odoo9s-server/``? Is it really 9.0 branch?
