### ISSUE TITLE
Confirg SFTP error

### ISSUE THREAD

**Issue by 360org** [it-projects-llc/odoo-saas-tools#434]
i need help plz 
when i try to config sftp for saas backup it show error
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 675, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 331, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/service/model.py", line 119, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 324, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 504, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/web/controllers/main.py", line 866, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/lib/python2.7/dist-packages/odoo/addons/web/controllers/main.py", line 854, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/api.py", line 681, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/api.py", line 672, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/odoo/odoo-saas-tools/saas_server_backup_ftp/models/res_config.py", line 113, in test_sftp_connection
    raise UserError(_(messageTitle), _(messageContent + "%s") % tools.ustr(e))
TypeError: __init__() takes exactly 2 arguments (3 given)
![2016-12-19_22-07-32](https://cloud.githubusercontent.com/assets/8590556/21317425/9b476d06-c637-11e6-9671-4a2a2ec5b003.png)

**Comment by yelizariev** [comment]
I guess the reason is that``saas_server_backup_ftp`` is not ported to 10.0

**Comment by 360org** [comment]
so which service for backup should i use?

**Comment by yelizariev** [comment]
We are going to refactor backup tools. Currently there are no ready to use solution

**Comment by 360org** [comment]
Thanks, im wating for that.

**Comment by augustosamame** [comment]
+1 for at least one working backup service
Any ETA ?

**Comment by yelizariev** [comment]
We are going to move our resources to saas in February
