### ISSUE TITLE
Error with config ssl, http2

### ISSUE THREAD

**Issue by 360org** [it-projects-llc/odoo-saas-tools#436]
hello!
i have problems with ssl config for http3.
anyone help plz

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 675, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 331, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/service/model.py", line 119, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 324, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 504, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/web/controllers/main.py", line 866, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/lib/python2.7/dist-packages/odoo/addons/web/controllers/main.py", line 854, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/api.py", line 681, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/api.py", line 672, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-247>", line 2, in action_sync_server
  File "/usr/lib/python2.7/dist-packages/odoo/api.py", line 361, in loop
    result = [method(rec, *args, **kwargs) for rec in self]
  File "/home/odoo/odoo-saas-tools/saas_portal/models/saas_portal.py", line 127, in action_sync_server
    res = requests.Session().send(req, **req_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 497, in send
    raise SSLError(e, request=request)
SSLError: ("bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')],)",)

![2016-12-23_02-12-06](https://cloud.githubusercontent.com/assets/8590556/21437255/6785990e-c8b5-11e6-9af8-64c734ba272a.png)
![2016-12-23_02-14-08](https://cloud.githubusercontent.com/assets/8590556/21437287/95fbae72-c8b5-11e6-947c-2bad4e0ac468.png)
![2016-12-23_02-15-30](https://cloud.githubusercontent.com/assets/8590556/21437327/cc04e7cc-c8b5-11e6-9e29-612aede136ef.png)

**Comment by yelizariev** [comment]
Try to switch off "Verify ssl"

**Comment by 360org** [comment]
i did but still not working

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 675, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 331, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/service/model.py", line 119, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 324, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 504, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/web/controllers/main.py", line 866, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/lib/python2.7/dist-packages/odoo/addons/web/controllers/main.py", line 854, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/api.py", line 681, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/api.py", line 672, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-247>", line 2, in action_sync_server
  File "/usr/lib/python2.7/dist-packages/odoo/api.py", line 361, in loop
    result = [method(rec, *args, **kwargs) for rec in self]
  File "/home/odoo/odoo-saas-tools/saas_portal/models/saas_portal.py", line 130, in action_sync_server
    raise Warning('Reason: %s \n Message: %s' % (res.reason, res.content))
Warning: Reason: INTERNAL SERVER ERROR 
 Message: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)>

**Comment by 360org** [comment]
task is close & thank-you @augustosamame 
all you have to use **fullchain**
    ssl on;
    ssl_certificate     /path_to_your_ssl_key/fullchain.pem;
    ssl_certificate_key /path_to_your_ssl_key/privkey.pem;
    keepalive_timeout   60;
