### ISSUE TITLE
New error INTERNAL SERVER ERROR, HTTP Error 404: NOT FOUND

### ISSUE THREAD

**Issue by 360org** [it-projects-llc/odoo-saas-tools#437]
Hello i have successful install everything fine but when i try to connect to clients server it have error like that. plz help.

here is connect db one with db 2 in same vps
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 675, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 331, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/service/model.py", line 119, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 324, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 504, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/web/controllers/main.py", line 866, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/lib/python2.7/dist-packages/odoo/addons/web/controllers/main.py", line 854, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/api.py", line 681, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/api.py", line 672, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-247>", line 2, in action_sync_server
  File "/usr/lib/python2.7/dist-packages/odoo/api.py", line 361, in loop
    result = [method(rec, *args, **kwargs) for rec in self]
  File "/home/odoo/odoo-saas-tools/saas_portal/models/saas_portal.py", line 127, in action_sync_server
    res = requests.Session().send(req, **req_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 437, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='datas.devtechperu.net', port=80): Max retries exceeded with url: /saas_server/sync_server (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f64e6f19250>: Failed to establish a new connection: [Errno -2] Name or service not known',))

**Comment by 360org** [comment]
and here is error when i try to connect to 2 vps 
1 is main server, 2 is clients storage db 

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 675, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 331, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/service/model.py", line 119, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 324, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 504, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/web/controllers/main.py", line 866, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/lib/python2.7/dist-packages/odoo/addons/web/controllers/main.py", line 854, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/api.py", line 681, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/api.py", line 672, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-247>", line 2, in action_sync_server
  File "/usr/lib/python2.7/dist-packages/odoo/api.py", line 361, in loop
    result = [method(rec, *args, **kwargs) for rec in self]
  File "/home/odoo/odoo-saas-tools/saas_portal/models/saas_portal.py", line 130, in action_sync_server
    raise Warning('Reason: %s \n Message: %s' % (res.reason, res.content))
Warning: Reason: INTERNAL SERVER ERROR 
 Message: HTTP Error 404: NOT FOUND

**Comment by 360org** [comment]
![2016-12-23_15-43-08](https://cloud.githubusercontent.com/assets/8590556/21450134/b7e2d1ac-c926-11e6-9c3f-a077b2e76578.png)
![2016-12-23_15-44-57](https://cloud.githubusercontent.com/assets/8590556/21450162/e4d0f7b6-c926-11e6-9daa-a0ce5a9687e3.png)
![2016-12-23_15-46-54](https://cloud.githubusercontent.com/assets/8590556/21450196/225f85fc-c927-11e6-82d8-b11383d378e1.png)

**Comment by 360org** [comment]
i have config port 80 it work fine.

**Comment by augustosamame** [comment]
+1

**Comment by 360org** [comment]
Hello anyone help plz?

**Comment by xyklex** [comment]
+1 

Hello, I have the issue after the server sync, plan and template created, but when I try to create a client the error shows up. I implemented two VPS each one with his database, portal and server. 

UPDATE: 

After several failures, I made it works, it's not an issue of the addon, it's the way odoo works, when you have several databases it don't know to what database make the request, so you need to have configured `dbfilter = ^%h$` in your odoo configuration file.

**Comment by yelizariev** [comment]
I've added a blog post about it https://it-projects-llc.github.io/odoo-saas-tools/blog/reason-not-found
