### ISSUE TITLE
Error when trying to create a subdomain in AWS 

### ISSUE THREAD

**Issue by augustosamame** [it-projects-llc/odoo-saas-tools#438]
I have installed modules SaaS_sysadmin_AWS and Saas Sysadmin AWS Route53 so that appropiate subdomains will be created upon client creation.

Im using version 10 of modules

However I am getting this error when creating clients:

`NameError: global name 'boto' is not defined`

I have configured proper AWS credentials in SaaS settings.
boto IS installed and I have verified it by running boto commands interactively in terminal.

Full traceback follows:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 675, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 331, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/service/model.py", line 119, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 324, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 504, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/web/controllers/main.py", line 866, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/lib/python2.7/dist-packages/odoo/addons/web/controllers/main.py", line 854, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/api.py", line 681, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/api.py", line 672, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/odoo/odoo-saas-tools/saas_portal/wizard/config_wizard.py", line 157, in apply
    trial=self.trial)
  File "/home/odoo/odoo-saas-tools/saas_portal/models/saas_portal.py", line 210, in create_new_database
    return self._create_new_database(**kwargs)
  File "/home/odoo/odoo-saas-tools/saas_portal_sale/models/saas_portal.py", line 23, in _create_new_database
    async=async)
  File "/home/odoo/odoo-saas-tools/saas_portal/models/saas_portal.py", line 257, in _create_new_database
    client = self.env['saas_portal.client'].create(vals)
  File "/home/odoo/odoo-saas-tools/saas_sysadmin_route53/models/saas_sysdamin_route53.py", line 37, in create
    client.server_id._update_zone(client.name, value=client.server_id.name, type='cname')
  File "/home/odoo/odoo-saas-tools/saas_sysadmin_aws_route53/models/saas_sysadmin_aws_route53.py", line 70, in _update_zone
    conn = _get_route53_conn(self.env)
  File "/home/odoo/odoo-saas-tools/saas_sysadmin_aws_route53/models/saas_sysadmin_aws_route53.py", line 22, in _get_route53_conn
    return boto.connect_route53(aws_access_key_id, aws_secret_access_key)
NameError: global name 'boto' is not defined
```

**Comment by augustosamame** [comment]
Ok. THAT problem was solved by a simple server reboot. It seems that Odoo server must be restarted after boto pip install.

Now I'm getting the following error in the logs and subdomain is not being created:

```
2016-12-24 06:38:14,561 1294 ERROR server.devtechperu.net odoo.addons.saas_sysadmin_aws_route53.models.saas_sysadmin_aws_route53: Error modifying AWS hosted zone
Traceback (most recent call last):
  File "/home/odoo/odoo-saas-tools/saas_sysadmin_aws_route53/models/saas_sysadmin_aws_route53.py", line 79, in _update_zone
    getattr(zone, method)(name, value)
AttributeError: 'NoneType' object has no attribute 'add_cname'


```

**Comment by augustosamame** [comment]
It's working now. 

After checking out the module's source code:

` zone = conn.get_zone(self.aws_hosted_zone_id.name)`

it turns out the proper value to put in the server AWS Hosted zone field is the hosted DOMAIN: mydomain.com not the HOST ID.

As the line from the code above indicates, the module will properly get the Host ID it needs when supplied the base DOMAIN.
