### ISSUE TITLE
Cannot create client from plan

### ISSUE THREAD

**Issue by askz** [it-projects-llc/odoo-saas-tools#45]
Hi, when I set the client db name and click create there's this error.
Before this, I have been able to create one client but when I clicked Log In the OAuth unique ID error was present.
Any thoughts?

``````
Odoo Server Error

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 530, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 567, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 303, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 300, in checked_call
    return self.endpoint(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 796, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 396, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/web/controllers/main.py", line 939, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/lib/python2.7/dist-packages/openerp/addons/web/controllers/main.py", line 927, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 363, in old_api
    result = method(recs, *args, **kwargs)
  File "/mnt/odoo-saas-tools/saas_portal/models/wizard.py", line 120, in apply
    url = wizard.plan_id.create_new_database(dbname=wizard.name, partner_id=wizard.partner_id.id)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 397, in new_api
    result = [method(rec, *args, **kwargs) for rec in self]
  File "/mnt/odoo-saas-tools/saas_portal/models/saas_portal.py", line 206, in create_new_database
    server.action_sync_server()
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 397, in new_api
    result = [method(rec, *args, **kwargs) for rec in self]
  File "/mnt/odoo-saas-tools/saas_portal/models/saas_portal.py", line 116, in action_sync_server
    url = self._request_server(path='/saas_server/sync_server', state=state, client_id=self.client_id)[0]
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 397, in new_api
    result = [method(rec, *args, **kwargs) for rec in self]
  File "/mnt/odoo-saas-tools/saas_portal/models/saas_portal.py", line 86, in _request_server
    access_token = access_token[0].token
  File "/usr/lib/python2.7/dist-packages/openerp/models.py", line 5554, in __getitem__
    return self._browse(self.env, (self._ids[key],))
IndexError: tuple index out of range```

``````

**Comment by eltronix** [comment]
I have also experienced the same:
`IndexError: tuple index out of range`

This was after deleting a client in SaaS Server. 
When I tried to sync in the SaaS portal, the above error popped up.

**Comment by yelizariev** [comment]
This part of code was updated
