### ISSUE TITLE
Error when duplicate database

### ISSUE THREAD

**Issue by dansalsero** [it-projects-llc/odoo-saas-tools#450]
Hi, I'm trying to duplicate a database, but there is this error:

It seems that the class SaasPortalDuplicateClient has an error in the function apply:

File "/usr/local/src/odoo-addons/odoo-saas-tools/saas_portal/models/wizard.py", line 190, in apply
    client = self.env['saas_portal.client'].browse(res.get('id'))
AttributeError: 'list' object has no attribute 'get'

I tried to change the line that gives the error:
        client = self.env['saas_portal.client'].browse(res.get('id'))
To:
        client = self.client_id 
 
To get the client, on the form, but the database get copied on the state new with no data on it, no clients, o users, nothing.

Thanks a lot for you guide.

Daniel.

**Comment by dansalsero** [comment]
I forgot, I tried to see if there is some fix on the new commits or in the v10 branch, but this line is the same.

Thanks.

**Comment by dansalsero** [comment]
Hi, as I was unable to duplicate the database using the default button, I had to make a copy using odoo "duplicate database" in the database/manager.

Now, I need to create the saas_portal.client and saas_server.client records to get the new database in the saas_portal database.

I created the records and got it almost working.

I duplicated the database and filled the data with the parameters like name and database UUID, most of it was woking, I was able to log in in the database with the admin but I wasn't able to get the database related data like count of user or mb used computed by the system.

Nether got the configure clients wizard to work, I got this error when I tried to use the wizard to upgrade or install modules.

Traceback (most recent call last):
  File "/usr/local/src/odoo-addons/odoo-saas-tools/saas_server/controllers/main.py", line 25, in wrap
    return f(*args, **kw)
  File "/usr/local/src/odoo-addons/odoo-saas-tools/saas_server/controllers/main.py", line 137, in upgrade_database
    result = client.upgrade_database(data=state.get('data'))[0]

There is anythin I can do to get this working.

Thanks a lot.

Daniel.

**Comment by dansalsero** [comment]
Well, looks like everyone is really busy.

I solved this issue by reusing a client from a trial database, I changed the UUID in the database.UUID and on the client of OAuth provider, also changed the name and client, from saas and saas server.

I hope it helps someone.
