### ISSUE TITLE
Uncaught Error: QWeb2 - template['mail.ChatThread.Message']: No enumerator given to foreach

### ISSUE THREAD

**Issue by zimbora69** [it-projects-llc/odoo-saas-tools#454]
How to reproduce error:

1)
Create two databases (via /web/database/manager):

Main Database, e.g. odoo.local:
install saas_portal and saas_portal_* (optional) modules
Server Database, e.g. s1.odoo.local
install saas_server

2)
Configure Server Database
Tick "Technical Features" for admin at Settings/Users/Users - Administrator
Refresh page
Open Settings/Users/OAuth Providers - SaaS
click [Edit]
update domain name at "Authentication URL" and "Validation URL", change http to https if needed. E.g.
http://odoo.local/oauth2/auth
http://odoo.local/oauth2/tokeninfo
Edit Body according to your brand
click [Save]
remember value of Client ID field. It's a database.uuid of SaaS Server.

4)
Configure Main Database:
open Settings/Configuration/SaaS Portal Settings
set Base SaaS domain, e.g. odoo.local
click Apply (do it even if you didn't make changes)

5)
Register Server Database in Main Database
open SaaS/SaaS/Servers
click [Create]
set Database Name, e.g. s1.odoo.local
fix autogenerated Database UUID to actual one (see previous section)
click [Save]

**On "save" of step 5) it generates following error:**

http://tko.tko-pt.com/web/content/251-a511e28/web.assets_common.js:2908
Traceabilidade:
Error: QWeb2 - template['mail.ChatThread.Message']: No enumerator given to foreach
    at Object.exception (http://tko.tko-pt.com/web/content/251-a511e28/web.assets_common.js:2908:7)
    at Object.foreach (http://tko.tko-pt.com/web/content/251-a511e28/web.assets_common.js:2921:80)
    at Engine.eval (eval at _render (http://tko.tko-pt.com/web/content/251-a511e28/web.assets_common.js:2949:73), <anonymous>:181:23)
    at Engine._render (http://tko.tko-pt.com/web/content/251-a511e28/web.assets_common.js:2948:296)
    at Engine.render (http://tko.tko-pt.com/web/content/251-a511e28/web.assets_common.js:2948:151)
    at Engine._render (http://tko.tko-pt.com/web/content/251-a511e28/web.assets_common.js:2952:57)
    at Object.call (http://tko.tko-pt.com/web/content/251-a511e28/web.assets_common.js:2918:23)
    at eval (eval at _render (http://tko.tko-pt.com/web/content/251-a511e28/web.assets_common.js:2949:73), <anonymous>:28:31)
    at Object.foreach (http://tko.tko-pt.com/web/content/251-a511e28/web.assets_common.js:2919:18)
    at Engine.eval (eval at _render (http://tko.tko-pt.com/web/content/251-a511e28/web.assets_common.js:2949:73), <anonymous>:15:23)

**Comment by 360org** [comment]
remove the chat module i think

**Comment by zimbora69** [comment]
Deleted mail.message records and error dissapeared.

Thanks @W360S
