### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by heshammostafa07** [it-projects-llc/odoo-saas-tools#458]
error when execute 
python saas.py --portal-create --server-create --plan-create --run --odoo-script=/opt/odoo/odoo-server/openerp-server --odoo-config=/etc/odoo-server.conf
odoo-saas-tools ver 8.0 - Ubuntu 16.04
**error log**
2017-02-18 19:11:43
saas.py >>> RPC Execute, ir.config_parameter, get_param, ['database.uuid'], {}

2017-02-18 19:11:43
saas.py >>> auth, ('saas-portal-8.local', <ServerProxy for localhost:8069/xmlrpc/2/object>, 1, 'admin')

2017-02-18 19:11:43
saas.py >>> RPC Execute, saas_portal.server, create, [{'local_host': 'localhost', 'name': 'server-1.saas-portal-8.local', 'client_id': 'e2c71f12-f5fa-11e6-aa80-0050568c0c8b', 'local_port': '8069'}], {}
Traceback (most recent call last):
  File "saas.py", line 178, in main
    rpc_add_server_to_portal(args.get('portal_db_name'))
  File "saas.py", line 319, in rpc_add_server_to_portal
    rpc_execute_kw(auth, 'saas_portal.server', 'create', [{'name': server_db_name, 'client_id': uuid, 'local_port': local_xmlrpc_port, 'local_host': 'localhost'}])
  File "saas.py", line 268, in rpc_execute_kw
    model, method, rpc_args, rpc_kwargs)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1243, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1602, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1283, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1316, in single_request
    return self.parse_response(response)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1493, in parse_response
    return u.close()
  File "/usr/lib/python2.7/xmlrpclib.py", line 800, in close
    raise Fault(**self._stack[0])
Fault: <Fault 2: "Object saas_portal.server doesn't exist">

2017-02-18 19:11:43
saas.py >>> KILL, 19244

**Comment by tuanna11520678** [comment]
I'm having the same issue, please let me know how you fixed ?

**Comment by CristianHR** [comment]
I also have the same problem, did someone manage to solve it?

**Comment by zinating** [comment]
I also have this problem. I don't know about 

`--server-hosts-template={dbname}.{base_saas_domain_1} \
--plan-template-db-name=template-1 \
--plan-clients=demo-%i \`

I know how to fix it.
