### ISSUE TITLE
Warning: Status Code - 404

### ISSUE THREAD

**Issue by lcstar** [it-projects-llc/odoo-saas-tools#47]
when I click create template DB
and the problem is

Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo/odoo/openerp/http.py", line 537, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo/openerp/http.py", line 574, in dispatch
    result = self._call_function(*_self.params)
  File "/opt/odoo/odoo/openerp/http.py", line 310, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/opt/odoo/odoo/openerp/service/model.py", line 113, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/opt/odoo/odoo/openerp/http.py", line 307, in checked_call
    return self.endpoint(_a, *_kw)
  File "/opt/odoo/odoo/openerp/http.py", line 803, in __call__
    return self.method(_args, *_kw)
  File "/opt/odoo/odoo/openerp/http.py", line 403, in response_wrap
    response = f(_args, *_kw)
  File "/opt/odoo/addons/web/controllers/main.py", line 952, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/addons/web/controllers/main.py", line 940, in _call_kw
    return checked_call(request.db, _args, *_kwargs)
  File "/opt/odoo/odoo/openerp/service/model.py", line 113, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/opt/odoo/addons/web/controllers/main.py", line 939, in checked_call
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "/opt/odoo/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo/openerp/api.py", line 372, in old_api
    result = method(recs, _args, *_kwargs)
  File "/opt/odoo/addons/saas_portal/models/saas_portal.py", line 292, in create_template
    raise Warning(msg)
Warning: Status Code - 404
Reason - Not Found
URL - http://s1.odoo.local:80/saas_server/new_database?access_token=YolFUqTObnLWNjeaMUv8g8KOFpoEaj&expires_in=3600&token_type=Bearer&state=%7B%22lang%22%3A+%22zh_CN%22%2C+%22tz%22%3A+false%2C+%22d%22%3A+%22ti.odoo.local%22%2C+%22demo%22%3A+0%2C+%22is_template_db%22%3A+1%2C+%22addons%22%3A+%5B%5D%7D&redirect_uri=http%3A%2F%2Fs1.odoo.local%3A80%2Fsaas_server%2Fnew_database&response_type=token&client_id=0dc7b49a-716f-11e5-bafa-00155d17010f&scope=userinfo+force_login+trial+skiptheuse

how can I fix it

**Comment by saltonmassally** [comment]
What port is your server listening to?

**Comment by lcstar** [comment]
What server?Nginx is 80 port.odoo's port is 8069

**Comment by saltonmassally** [comment]
Did you carefully follow the instructions especially the part about updating /etc/hosts? I suggest you bypass nginx until your setup is finished by changing request port on your saas server to 8069

**Comment by lcstar** [comment]
You mean I just set saas server's port on 8069?

**Comment by saltonmassally** [comment]
Do that and create template db

**Comment by lcstar** [comment]
I want know "set dbfilter in config file or run odoo with --db-filter parameter, e.g. ^%h$" how can I find the config file ,or  how to run odoo with --db-filter parameter

**Comment by lcstar** [comment]
The First time When  I click create template db ,it error is 504 Gateway error
The Second time When I click create template db,it error is 404 error??
Why  ？ how can I fix it? Thank you

**Comment by ojobello** [comment]
Hi guys,

I have followed the instructions and set my nginx and dbfilter correctly. Everything works fine after several tweaks until I get to the point where I need to create a client database from the template
in SaaS>>SaaS>>Plans. I select the plan and then create client. 

Looking at the tracert, the client database shows up in the log, seems the database is created but I get the error below in tracert and the browser shows "Server Error".

But when I enter the client url eg client-x.odoo.local, it takes me to odoo home page but I cannot login. What is the username and password to login to this created client so I can test if the modules installed match the modules configured in the template.

This is the error in traceback:

2015-10-27 01:50:17,394 24759 ERROR s5.odoosme.net openerp.sql_db: Programming error: must be superuser to signal other server processes
, in query SELECT pg_terminate_backend(procpid)
                      FROM pg_stat_activity
                      WHERE datname = %s AND
                            procpid != pg_backend_pid()
2015-10-27 01:50:17,394 24759 INFO s5.odoosme.net openerp.service.db: Duplicate database `t6.odoosme.net` to `helpnow2.odoosme.net`.
2015-10-27 01:50:17,398 24759 INFO s5.odoosme.net openerp.sql_db: ConnectionPool(used=2/count=7/max=64): Closed 2 connections to 'user=odoo dbname=t6.odoosme.net'
2015-10-27 01:50:21,133 24759 ERROR s5.odoosme.net openerp.sql_db: bad query: UPDATE "saas_server_client" SET "state"='open',"write_uid"=1,"write_date"=(now() at time zone 'UTC') WHERE id IN (32)
Traceback (most recent call last):
  File "/opt/odoo/odoo/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
InternalError: current transaction is aborted, commands ignored until end of transaction block

2015-10-27 01:50:21,140 24759 ERROR s5.odoosme.net openerp.addons.website.models.ir_http: 500 Internal Server Error:

Traceback (most recent call last):
  File "/opt/odoo/odoo/addons/website/models/ir_http.py", line 199, in _handle_exception
    response = super(ir_http, self)._handle_exception(exception)
  File "/opt/odoo/odoo/openerp/addons/base/ir/ir_http.py", line 145, in _handle_exception
    return request._handle_exception(exception)
  File "/opt/odoo/odoo/openerp/http.py", line 666, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo/openerp/addons/base/ir/ir_http.py", line 171, in _dispatch
    result = request.dispatch()
  File "/opt/odoo/odoo/openerp/http.py", line 684, in dispatch
    r = self._call_function(**self.params)
  File "/opt/odoo/odoo/openerp/http.py", line 310, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo/openerp/http.py", line 307, in checked_call
    return self.endpoint(*a, **kw)
  File "/opt/odoo/odoo/openerp/http.py", line 803, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo/openerp/http.py", line 403, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo/addons/auth_oauth/controllers/main.py", line 42, in wrapper
    return func(self, *a, **kw)
  File "/opt/odoo/odoo/addons/saas_server/controllers/main.py", line 53, in new_database
    client.create_database(template_db, demo, lang)
  File "/opt/odoo/odoo/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/odoo/openerp/api.py", line 416, in new_api
    result = [method(rec, *args, **kwargs) for rec in self]
  File "/opt/odoo/odoo/addons/saas_server/models/saas_server.py", line 50, in create_database
    self.state = 'open'
  File "/opt/odoo/odoo/openerp/fields.py", line 855, in __set__
    record.write({self.name: self.convert_to_write(value)})
  File "/opt/odoo/odoo/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/odoo/openerp/api.py", line 565, in new_api
    result = method(self._model, cr, uid, self.ids, *args, **kwargs)
  File "/opt/odoo/odoo/addons/mail/mail_thread.py", line 432, in write
    result = super(mail_thread, self).write(cr, uid, ids, values, context=context)
  File "/opt/odoo/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/odoo/openerp/api.py", line 372, in old_api
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/odoo/openerp/models.py", line 3787, in write
    self._write(old_vals)
  File "/opt/odoo/odoo/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/odoo/openerp/api.py", line 565, in new_api
    result = method(self._model, cr, uid, self.ids, *args, **kwargs)
  File "/opt/odoo/odoo/openerp/models.py", line 3898, in _write
    cr.execute(query, params + (sub_ids,))
  File "/opt/odoo/odoo/openerp/sql_db.py", line 158, in wrapper
    return f(self, *args, **kwargs)
  File "/opt/odoo/odoo/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
InternalError: current transaction is aborted, commands ignored until end of transaction block


2015-10-27 01:50:21,142 24759 ERROR s5.odoosme.net openerp.sql_db: bad query:  SELECT "website"."social_twitter","website"."default_lang_id","website"."id","website"."create_date","website"."social_facebook","website"."company_id","website"."social_linkedin","website"."user_id","website"."create_uid","website"."default_lang_code","website"."write_date","website"."social_googleplus","website"."social_youtube","website"."menu_id","website"."google_analytics_key","website"."write_uid","website"."name","website"."social_github" FROM "website"
                        WHERE "website".id IN (1)  ORDER BY "website"."id"  
                    
Traceback (most recent call last):
  File "/opt/odoo/odoo/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
InternalError: current transaction is aborted, commands ignored until end of transaction block

2015-10-27 01:50:21,144 24759 ERROR s5.odoosme.net openerp.sql_db: bad query:  SELECT "website"."social_twitter","website"."default_lang_id","website"."id","website"."create_date","website"."social_facebook","website"."company_id","website"."social_linkedin","website"."user_id","website"."create_uid","website"."default_lang_code","website"."write_date","website"."social_googleplus","website"."social_youtube","website"."menu_id","website"."google_analytics_key","website"."write_uid","website"."name","website"."social_github" FROM "website"
                        WHERE "website".id IN (1)  ORDER BY "website"."id"  
                    
Traceback (most recent call last):
  File "/opt/odoo/odoo/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
InternalError: current transaction is aborted, commands ignored until end of transaction block

2015-10-27 01:50:21,151 24759 INFO s5.odoosme.net werkzeug: 191.101.2.17 - - [27/Oct/2015 01:50:21] "GET /saas_server/new_database?access_token=LcHS03Us6VgpslutSmqtFuKHhJgodN&token_type=Bearer&state=%7B%22db_template%22%3A+%22t6.odoosme.net%22%2C+%22r%22%3A+%22http%3A%2F%2Fhelpnow2.odoosme.net%3A80%2Fweb%22%2C+%22e%22%3A+false%2C+%22d%22%3A+%22helpnow2.odoosme.net%22%7D&expires_in=3600&scope=userinfo+force_login+trial+skiptheuse HTTP/1.0" 500 -
2015-10-27 01:50:21,194 24759 ERROR s5.odoosme.net werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/share/pyshared/werkzeug/serving.py", line 159, in run_wsgi
    execute(app)
  File "/usr/share/pyshared/werkzeug/serving.py", line 146, in execute
    application_iter = app(environ, start_response)
  File "/opt/odoo/odoo/openerp/service/server.py", line 290, in app
    return self.app(e, s)
  File "/opt/odoo/odoo/openerp/service/wsgi_server.py", line 216, in application
    return application_unproxied(environ, start_response)
  File "/opt/odoo/odoo/openerp/service/wsgi_server.py", line 202, in application_unproxied
    result = handler(environ, start_response)
  File "/opt/odoo/odoo/openerp/http.py", line 1290, in __call__
    return self.dispatch(environ, start_response)
  File "/opt/odoo/odoo/openerp/http.py", line 1264, in __call__
    return self.app(environ, start_wrapped)
  File "/usr/share/pyshared/werkzeug/wsgi.py", line 411, in __call__
    return self.app(environ, start_response)
  File "/opt/odoo/odoo/openerp/http.py", line 1437, in dispatch
    result = ir_http._dispatch()
  File "/opt/odoo/odoo/addons/website/models/ir_http.py", line 148, in _dispatch
    resp = super(ir_http, self)._dispatch()
  File "/opt/odoo/odoo/openerp/addons/base/ir/ir_http.py", line 175, in _dispatch
    return self._handle_exception(e)
  File "/opt/odoo/odoo/addons/website/models/ir_http.py", line 248, in _handle_exception
    html = request.website._render('website.http_error', values)
  File "/opt/odoo/odoo/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/odoo/openerp/api.py", line 565, in new_api
    result = method(self._model, cr, uid, self.ids, *args, **kwargs)
  File "/opt/odoo/odoo/addons/website/models/website.py", line 288, in _render
    return self.pool['ir.ui.view'].render(cr, uid, template, values=values, context=context)
  File "/opt/odoo/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/odoo/addons/website/models/ir_ui_view.py", line 142, in render
    company = self.pool['res.company'].browse(cr, SUPERUSER_ID, request.website.company_id.id, context=context)
  File "/opt/odoo/odoo/openerp/fields.py", line 819, in __get__
    self.determine_value(record)
  File "/opt/odoo/odoo/openerp/fields.py", line 912, in determine_value
    record._prefetch_field(self)
  File "/opt/odoo/odoo/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/odoo/openerp/models.py", line 3241, in _prefetch_field
    result = records.read(list(fnames), load='_classic_write')
  File "/opt/odoo/odoo/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/odoo/openerp/models.py", line 3178, in read
    self._read_from_database(stored, inherited)
  File "/opt/odoo/odoo/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/odoo/openerp/models.py", line 3310, in _read_from_database
    cr.execute(query_str, [tuple(sub_ids)] + where_params)
  File "/opt/odoo/odoo/openerp/sql_db.py", line 158, in wrapper
    return f(self, *args, **kwargs)
  File "/opt/odoo/odoo/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
InternalError: current transaction is aborted, commands ignored until end of transaction block


Thanks for your help on this one

**Comment by yelizariev** [comment]
https://github.com/yelizariev/odoo-saas-tools/blob/9.0/docs/odoo-configuration.rst
or
https://it-projects-llc.github.io/odoo-saas-tools/blog/reason-not-found

**Comment by thanhchatvn** [comment]
inside config file please add attribute "dbfilter=%h" and /etc/hosts add your many host
