### ISSUE TITLE
saas plan  cannot create template DB

### ISSUE THREAD

**Issue by FLwalkaway** [it-projects-llc/odoo-saas-tools#479]
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 675, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 331, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/service/model.py", line 119, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 324, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 504, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/web/controllers/main.py", line 882, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/lib/python2.7/dist-packages/odoo/addons/web/controllers/main.py", line 870, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/api.py", line 681, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/api.py", line 672, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/saas_portal/models/saas_portal.py", line 321, in create_template_button
    res = self.create_template()
  File "/usr/lib/python2.7/dist-packages/odoo/addons/saas_portal/models/saas_portal.py", line 343, in create_template
    raise Warning('Error on request: %s\nReason: %s \n Message: %s' % (req.url, res.reason, res.content))
Warning: Error on request: http://server.xxx.com:80/saas_server/new_database
Reason: Not Found 
 Message: <html>
<head><title>404 Not Found</title></head>
<body bgcolor="white">
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.10.0 (Ubuntu)</center>

**Comment by FLwalkaway** [comment]
above is odoo server error.Is there someone come with this problem? I cannot deal with it

**Comment by 360org** [comment]
This is nginx config error. make sure you have ^%h$ in db filter and nginx right config, also check with limit
limit_time_cpu = 600
limit_time_real = 1200

**Comment by FLwalkaway** [comment]
thank you! I did't config nginx correctly. however,saas can not use "max user".if i log in client, i can not add other users. How can i solve this problem?

**Comment by 360org** [comment]
Check your plan, where is the user limit

**Comment by FLwalkaway** [comment]
if i want log in saas use email and password,we should provide "sign up" for users. should i install "saas portal sale"?

**Comment by FLwalkaway** [comment]
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 675, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 331, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/service/model.py", line 119, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 324, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 504, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/web/controllers/main.py", line 882, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/lib/python2.7/dist-packages/odoo/addons/web/controllers/main.py", line 870, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/api.py", line 681, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/api.py", line 672, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/module/module.py", line 410, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/module/module.py", line 484, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/usr/lib/python2.7/dist-packages/odoo/modules/registry.py", line 78, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/usr/lib/python2.7/dist-packages/odoo/modules/loading.py", line 339, in load_modules
    loaded_modules, update_module)
  File "/usr/lib/python2.7/dist-packages/odoo/modules/loading.py", line 237, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/usr/lib/python2.7/dist-packages/odoo/modules/loading.py", line 156, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/usr/lib/python2.7/dist-packages/odoo/modules/loading.py", line 95, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/usr/lib/python2.7/dist-packages/odoo/tools/convert.py", line 848, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/usr/lib/python2.7/dist-packages/odoo/tools/convert.py", line 918, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/usr/lib/python2.7/dist-packages/odoo/tools/convert.py", line 799, in parse
    self.parse(rec, mode)
  File "/usr/lib/python2.7/dist-packages/odoo/tools/convert.py", line 802, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/usr/lib/python2.7/dist-packages/odoo/tools/convert.py", line 710, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/ir/ir_model.py", line 1192, in _update
    record = record.create(values)
  File "/usr/lib/python2.7/dist-packages/odoo/models.py", line 3811, in create
    record = self.browse(self._create(old_vals))
  File "/usr/lib/python2.7/dist-packages/odoo/models.py", line 3901, in _create
    cr.execute(query, tuple(u[2] for u in updates if len(u) > 2))
  File "/usr/lib/python2.7/dist-packages/odoo/sql_db.py", line 141, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/sql_db.py", line 218, in execute
    res = self._obj.execute(query, params)
ParseError: "duplicate key value violates unique constraint "ir_config_parameter_key_uniq"
DETAIL:  Key (key)=(saas_portal.page_for_nonfree_subdomains) already exists.
" while parsing /usr/lib/python2.7/dist-packages/odoo/addons/saas_portal_sale/data/ir_config_parameter.xml:4, near
<record id="saas_page_for_nonfree_subdomains" model="ir.config_parameter">
            <field name="key">saas_portal.page_for_nonfree_subdomains</field>
            <field name="value">/</field>
        </record>

**Comment by FLwalkaway** [comment]
if i install  mudule"saas portal sale"  ,above is odoo server error

**Comment by 360org** [comment]
DETAIL: Key (key)=(saas_portal.page_for_nonfree_subdomains) already exists.
" while parsing /usr/lib/python2.7/dist-packages/odoo/addons/saas_portal_sale/data/ir_config_parameter.xml:4, near

saas_portal.page_for_nonfree_subdomains
/
Here is the error

**Comment by 360org** [comment]
it say key exists

DETAIL: Key (key)=(saas_portal.page_for_nonfree_subdomains) already exists.

**Comment by sathwiksunderreddy** [comment]
Hi I am trying to create a template db in Saas module but getting the below error pls help me 

Thanks in Advance

Odoo Server Error
Traceback (most recent call last):
  File "D:\New odoo\odoo-8.0-20170403\openerp\http.py", line 544, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "D:\New odoo\odoo-8.0-20170403\openerp\http.py", line 581, in dispatch
    result = self._call_function(**self.params)
  File "D:\New odoo\odoo-8.0-20170403\openerp\http.py", line 317, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "D:\New odoo\odoo-8.0-20170403\openerp\service\model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "D:\New odoo\odoo-8.0-20170403\openerp\http.py", line 314, in checked_call
    return self.endpoint(*a, **kw)
  File "D:\New odoo\odoo-8.0-20170403\openerp\http.py", line 810, in __call__
    return self.method(*args, **kw)
  File "D:\New odoo\odoo-8.0-20170403\openerp\http.py", line 410, in response_wrap
    response = f(*args, **kw)
  File "D:\New odoo\odoo-8.0-20170403\openerp\addons\web\controllers\main.py", line 948, in call_button
    action = self._call_kw(model, method, args, {})
  File "D:\New odoo\odoo-8.0-20170403\openerp\addons\web\controllers\main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "D:\New odoo\odoo-8.0-20170403\openerp\api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "D:\New odoo\odoo-8.0-20170403\openerp\api.py", line 399, in old_api
    result = method(recs, *args, **kwargs)
  File "D:\New odoo\odoo-8.0-20170403\openerp\addons\saas_portal\models\saas_portal.py", line 344, in create_template_button
    res = self.create_template()
  File "D:\New odoo\odoo-8.0-20170403\openerp\api.py", line 266, in wrapper
    return new_api(self, *args, **kwargs)
  File "D:\New odoo\odoo-8.0-20170403\openerp\addons\saas_portal\models\saas_portal.py", line 365, in create_template
    raise Warning('Error on request: %s\nReason: %s \n Message: %s' % (req.url, res.reason, res.content))
Warning: Error on request: http://localhost:8069/saas_server/new_database
Reason: NOT FOUND 
 Message: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>404 Not Found</title>
<h1>Not Found</h1>
<p>The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.</p>

**Comment by 360org** [comment]
check your nginx configuration and also do not naming existing db

**Comment by sathwiksunderreddy** [comment]
I checked the nginx configuration its working fine and I am naming unique db 

actually I am trying it in local odoo instance 
Its poping up the same error

Thanks

**Comment by oanhle** [comment]
Hi all, I'm also get the same error. But I fixed it. please run command 
pip uninstall Werkzeug
pip install requests --upgrade
Because the packages block this requests.
p/s: the saas only running on Ubuntu 14.04 above

**Comment by ovnicraft** [comment]
Please check this: https://it-projects-llc.github.io/odoo-saas-tools/blog/reason-not-found

**Comment by butagreeza** [comment]
Am trying to create a TemplateDB but am having this error. 
Traceback (most recent call last):
  File "/var/repo/mautinoa/odoo/odoo/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/var/repo/mautinoa/odoo/odoo/http.py", line 675, in dispatch
    result = self._call_function(**self.params)
  File "/var/repo/mautinoa/odoo/odoo/http.py", line 331, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/var/repo/mautinoa/odoo/odoo/service/model.py", line 119, in wrapper
    return f(dbname, *args, **kwargs)
  File "/var/repo/mautinoa/odoo/odoo/http.py", line 324, in checked_call
    result = self.endpoint(*a, **kw)
  File "/var/repo/mautinoa/odoo/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/var/repo/mautinoa/odoo/odoo/http.py", line 504, in response_wrap
    response = f(*args, **kw)
  File "/var/repo/mautinoa/odoo/addons/web/controllers/main.py", line 882, in call_button
    action = self._call_kw(model, method, args, {})
  File "/var/repo/mautinoa/odoo/addons/web/controllers/main.py", line 870, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/var/repo/mautinoa/odoo/odoo/api.py", line 681, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/var/repo/mautinoa/odoo/odoo/api.py", line 672, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/var/repo/mautinoa/odoo/custom/community/saas_portal/models/saas_portal.py", line 351, in create_template_button
    res = self.create_template()
  File "/var/repo/mautinoa/odoo/custom/community/saas_portal/models/saas_portal.py", line 374, in create_template
    data = simplejson.loads(res.text)
  File "/var/repo/env/mautinoa/local/lib/python2.7/site-packages/simplejson/__init__.py", line 516, in loads
    return _default_decoder.decode(s)
  File "/var/repo/env/mautinoa/local/lib/python2.7/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/var/repo/env/mautinoa/local/lib/python2.7/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
JSONDecodeError: Expecting value: line 1 column 1 (char 0)


Any suggestions??

**Comment by JETSHUB** [comment]
I got this error
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/SME cloud/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/SME cloud/http.py", line 675, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python2.7/dist-packages/SME cloud/http.py", line 331, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/SME cloud/service/model.py", line 119, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/SME cloud/http.py", line 324, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/SME cloud/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/SME cloud/http.py", line 504, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/SME cloud/addons/web/controllers/main.py", line 882, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/lib/python2.7/dist-packages/SME cloud/addons/web/controllers/main.py", line 870, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/SME cloud/api.py", line 681, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/SME cloud/api.py", line 672, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/SME cloud/SME cloud-saas-tools/saas_portal/models/saas_portal.py", line 336, in create_template_button
    res = self.create_template()
  File "/home/SME cloud/SME cloud-saas-tools/saas_portal/models/saas_portal.py", line 358, in create_template
    raise Warning('Error on request: %s\nReason: %s \n Message: %s' % (req.url, res.reason, res.content))
Warning: Error on request: https://clients.xxxx.xxx:443/saas_server/new_database
Reason: INTERNAL SERVER ERROR 
 Message: "External ID not found in the system: website.assets_frontend" while parsing None:5, near
<data name="assets" inherit_id="website.assets_frontend">
            <xpath expr="." position="inside">
                
                <script type="text/javascript" src="/saas_client/static/src/js/saas_client.js"/>
                <script type="text/javascript" src="/saas_client/static/src/js/saas_dashboard.js"/>
            </xpath>
        </data>

**Comment by 360org** [comment]
Warning: Error on request: https://clients.xxxx.xxx:443/saas_server/new_database
Reason: INTERNAL SERVER ERROR
Message: "External ID not found in the system: website.assets_frontend" while parsing None:5, near
check this.

**Comment by serpentcs-dev1** [comment]
Hello @njeudy , I am facing the same issue, I checked this post https://it-projects-llc.github.io/odoo-saas-tools/blog/reason-not-found.

I am installing saas in localhost, it is showing me this while creating a new client : `http://localhost:8069/saas_server/new_database`

As -db-filter=^%h$ will not help in localhost. Then can you please advise what is the solution for this?

**Comment by 360org** [comment]
you need to make sure your local domain work first.

**Comment by serpentcs-dev1** [comment]
![localhost](https://user-images.githubusercontent.com/20109026/39303831-41aaac1e-4975-11e8-9682-79ded3e8735d.png)

@W360S I tried manually earlier it was saying 404, I found that the `saas_server` module was not installed on the `saas-portal-11.local` database, I installed it and then tried again, it is working now manually but not from the code still while creating the client! 

cc @njeudy

**Comment by serpentcs-dev1** [comment]
@oanhle Does the below solution works for you, I am still getting http://localhost:8069/saas_server/new_database in localhost while creating client.

> Hi all, I'm also get the same error. But I fixed it. please run command
> pip uninstall Werkzeug
> pip install requests --upgrade
> Because the packages block this requests.
> p/s: the saas only running on Ubuntu 14.04 above

**Comment by oanhle** [comment]
@darshan-serpent  I think you have got some mistakes. on the database server, you should only install module saas_server to manage database for saas. On the database client, you don't install  saas_server, must be install saas_portal, saas_base ...... Between them mustbe login by saas auth by IP, account....

**Comment by oodlesShivam** [comment]
```
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/util/connection.py", line 57, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.5/socket.py", line 732, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.5/http/client.py", line 1106, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1151, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.5/http/client.py", line 1102, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/usr/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connection.py", line 181, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connection.py", line 168, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fdf73365dd8>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.5/dist-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='s1.odoo.local', port=80): Max retries exceeded with url: /saas_server/new_database (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fdf73365dd8>: Failed to establish a new connection: [Errno -2] Name or service not known',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/shivam/Videos/odoo-11.0/odoo/http.py", line 651, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/shivam/Videos/odoo-11.0/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/shivam/Videos/odoo-11.0/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/home/shivam/Videos/odoo-11.0/odoo/http.py", line 693, in dispatch
    result = self._call_function(**self.params)
  File "/home/shivam/Videos/odoo-11.0/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/shivam/Videos/odoo-11.0/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/shivam/Videos/odoo-11.0/odoo/http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/shivam/Videos/odoo-11.0/odoo/http.py", line 937, in __call__
    return self.method(*args, **kw)
  File "/home/shivam/Videos/odoo-11.0/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/home/shivam/Videos/odoo-11.0/addons/web/controllers/main.py", line 938, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/shivam/Videos/odoo-11.0/addons/web/controllers/main.py", line 926, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/shivam/Videos/odoo-11.0/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/home/shivam/Videos/odoo-11.0/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/shivam/Videos/odoo-11.0/odoo-saas-tools/saas_portal/models/saas_portal.py", line 410, in create_template_button
    return self.create_template()
  File "/home/shivam/Videos/odoo-11.0/odoo-saas-tools/saas_portal/models/saas_portal.py", line 428, in create_template
    res = requests.Session().send(req, **req_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='s1.odoo.local', port=80): Max retries exceeded with url: /saas_server/new_database (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fdf73365dd8>: Failed to establish a new connection: [Errno -2] Name or service not known',))
```
This exception is coming at time of creating template DB please help me to slove this.

**Comment by oodlesShivam** [comment]
`Error:
Odoo Server Error

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/util/connection.py", line 57, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.5/socket.py", line 732, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.5/http/client.py", line 1106, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1151, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.5/http/client.py", line 1102, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/usr/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connection.py", line 181, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connection.py", line 168, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fdf70dc1b70>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.5/dist-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='s1.odoo.local', port=80): Max retries exceeded with url: /saas_server/new_database (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fdf70dc1b70>: Failed to establish a new connection: [Errno -2] Name or service not known',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/shivam/Videos/odoo-11.0/odoo/http.py", line 651, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/shivam/Videos/odoo-11.0/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/shivam/Videos/odoo-11.0/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/home/shivam/Videos/odoo-11.0/odoo/http.py", line 693, in dispatch
    result = self._call_function(**self.params)
  File "/home/shivam/Videos/odoo-11.0/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/shivam/Videos/odoo-11.0/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/shivam/Videos/odoo-11.0/odoo/http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/shivam/Videos/odoo-11.0/odoo/http.py", line 937, in __call__
    return self.method(*args, **kw)
  File "/home/shivam/Videos/odoo-11.0/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/home/shivam/Videos/odoo-11.0/addons/web/controllers/main.py", line 938, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/shivam/Videos/odoo-11.0/addons/web/controllers/main.py", line 926, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/shivam/Videos/odoo-11.0/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/home/shivam/Videos/odoo-11.0/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/shivam/Videos/odoo-11.0/odoo-saas-tools/saas_portal/models/saas_portal.py", line 410, in create_template_button
    return self.create_template()
  File "/home/shivam/Videos/odoo-11.0/odoo-saas-tools/saas_portal/models/saas_portal.py", line 428, in create_template
    res = requests.Session().send(req, **req_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='s1.odoo.local', port=80): Max retries exceeded with url: /saas_server/new_database (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fdf70dc1b70>: Failed to establish a new connection: [Errno -2] Name or service not known',))`


This exception is coming at the time of creating template DB please help me to solve this.

**Comment by bitsnaps** [comment]
I had the same issue, I fixed that by filling `DB Names` field (e.g. `tt%i.odoo.local`)
