### ISSUE TITLE
ConnectionError

### ISSUE THREAD

**Issue by LearShelfy** [it-projects-llc/odoo-saas-tools#50]
When I click the button "Sync Server":

Traceback (most recent call last):
  File "/opt/openerp/server/openerp/http.py", line 537, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/openerp/server/openerp/http.py", line 574, in dispatch
    result = self._call_function(*_self.params)
  File "/opt/openerp/server/openerp/http.py", line 310, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/opt/openerp/server/openerp/service/model.py", line 113, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/opt/openerp/server/openerp/http.py", line 307, in checked_call
    return self.endpoint(_a, *_kw)
  File "/opt/openerp/server/openerp/http.py", line 803, in __call__
    return self.method(_args, *_kw)
  File "/opt/openerp/server/openerp/http.py", line 403, in response_wrap
    response = f(_args, *_kw)
  File "/opt/openerp/server/openerp/addons/web/controllers/main.py", line 948, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/openerp/server/openerp/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "/opt/openerp/server/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/openerp/server/openerp/api.py", line 394, in old_api
    result = new_api(recs, _args, *_kwargs)
  File "/opt/openerp/server/openerp/api.py", line 398, in new_api
    result = [method(rec, _args, *_kwargs) for rec in self]
  File "/opt/openerp/oscg/saas/saas_portal/models/saas_portal.py", line 97, in action_sync_server
    res = requests.get(url)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 65, in get
    return request('get', url, *_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 49, in request
    response = session.request(method=method, url=url, *_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 461, in request
    resp = self.send(prep, *_send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, *_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', BadStatusLine("''",))

**Comment by yelizariev** [comment]
Check this configuration requirements https://github.com/yelizariev/odoo-saas-tools/blob/9.0/docs/odoo-configuration.rst
