### ISSUE TITLE
error when clone client database (create more like this)

### ISSUE THREAD

**Issue by clxadmin** [it-projects-llc/odoo-saas-tools#518]
Hello, I'm looking for help
My SaaS Portal shows error if I try to clone one client database in SaaS Tool - create more like this:

Odoo Server Error
Traceback (most recent call last):
  File "/usr/local/src/odoo-source/odoo/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/local/src/odoo-source/odoo/http.py", line 675, in dispatch
    result = self._call_function(**self.params)
  File "/usr/local/src/odoo-source/odoo/http.py", line 331, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/local/src/odoo-source/odoo/service/model.py", line 119, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/local/src/odoo-source/odoo/http.py", line 324, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/local/src/odoo-source/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/usr/local/src/odoo-source/odoo/http.py", line 504, in response_wrap
    response = f(*args, **kw)
  File "/usr/local/src/odoo-source/addons/web/controllers/main.py", line 882, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/local/src/odoo-source/addons/web/controllers/main.py", line 870, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/local/src/odoo-source/odoo/api.py", line 681, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/usr/local/src/odoo-source/odoo/api.py", line 672, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/usr/local/src/odoo-extra-addons/it-projects-llc/odoo-saas-tools/saas_portal/wizard/config_wizard.py", line 202, in apply
    client = self.env['saas_portal.client'].browse(res.get('id'))
AttributeError: 'list' object has no attribute 'get'

**Comment by clxadmin** [comment]
I'm facing the same issue on runbot http://05136-10-0-677674--base---portal.runbot.it-projects.info/web?

**Comment by clxadmin** [comment]
can anyone else clone clients database with SaaS Tool?

**Comment by iledarn** [comment]
@clxadmin, thanks
I think I did fix it here https://github.com/it-projects-llc/odoo-saas-tools/pull/539

**Comment by iledarn** [comment]
@clxadmin, thanks
I think I did fix it here #539
