### ISSUE TITLE
Getting error "Fault 2: None" during automatic script execution

### ISSUE THREAD

**Issue by satgurumss** [it-projects-llc/odoo-saas-tools#547]
I am executing the script as below:
python saas.py --portal-create --server-create --plan-create --admin-password='ubuntu' --run --odoo-script=/opt/odoo/odoo-10.0/odoo-bin --odoo-config=/etc/odoo.conf

i keep getting the error "Fault 2: None". 
Logs are below:
2017-05-16 10:06:09
saas.py >>> Read odoo config, /etc/odoo.conf

2017-05-16 10:06:09
saas.py >>> Waiting for port, 127.0.0.1, 8069

2017-05-16 10:06:12
saas.py >>> Spawn, /opt/odoo/odoo-10.0/odoo-bin --xmlrpc-port=8069 --longpolling-port=8072 --database= --db-filter=%h --workers=3 --db_user=odoo --db_password=odoo --db_port=5432 --max-cron-threads=0 --config=/etc/odoo.conf

2017-05-16 10:06:12
saas.py >>> Spawn pid: 8767

2017-05-16 10:06:12
saas.py >>> Waiting for port, 127.0.0.1, 8069
Running as user 'root' is a security risk.

2017-05-16 10:06:14
saas.py >>> create database via xmlrpc
Running as user 'root' is a security risk.

2017-05-16 10:06:45
saas.py >>> auth, ('saas-portal-10.local', <ServerProxy for localhost:8069/xmlrpc/2/object>, 1, 'ubuntu')

2017-05-16 10:06:45
saas.py >>> RPC Execute, ir.module.module, search, [[('state', '=', 'uninstalled'), ('name', 'in', ['saas_portal_start', 'saas_portal', 'saas_portal_sale_online'])]], {}

2017-05-16 10:06:45
saas.py >>> auth, ('saas-portal-10.local', <ServerProxy for localhost:8069/xmlrpc/2/object>, 1, 'ubuntu')

2017-05-16 10:06:45
saas.py >>> RPC Execute, ir.module.module, button_immediate_install, [[176, 109, 62]], {}
Traceback (most recent call last):
  File "saas.py", line 186, in main
    install_modules=portal_modules)
  File "saas.py", line 299, in rpc_init_db
    rpc_execute_kw(auth, 'ir.module.module', 'button_immediate_install', [module_ids])
  File "saas.py", line 291, in rpc_execute_kw
    model, method, rpc_args, rpc_kwargs)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1243, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1602, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1283, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1316, in single_request
    return self.parse_response(response)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1493, in parse_response
    return u.close()
  File "/usr/lib/python2.7/xmlrpclib.py", line 800, in close
    raise Fault(**self._stack[0])
Fault: <Fault 2: 'None'>

Any help is appreciated

**Comment by captainjapeng** [comment]
Any luck solving this?

**Comment by captainjapeng** [comment]
I've installed all the dependencies listed in `['saas_portal_start', 'saas_portal', 'saas_portal_sale_online'` manually one by one and shows up missing dependencies. Have a great day!
