### ISSUE TITLE
Error after update system.

### ISSUE THREAD

**Issue by 360org** [it-projects-llc/odoo-saas-tools#562]
Hello!, i need help, anyone help plz, after upgrade the system i have error like this bellow. anyone meet the same?
--------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 675, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 331, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/service/model.py", line 119, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 324, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 504, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/web/controllers/main.py", line 885, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/web/controllers/main.py", line 877, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/api.py", line 679, in call_kw
    return call_kw_model(method, model, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/api.py", line 664, in call_kw_model
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/models.py", line 1338, in load_views
    for [v_id, v_type] in views
  File "/usr/lib/python2.7/dist-packages/odoo/models.py", line 1338, in <dictcomp>
    for [v_id, v_type] in views
  File "/usr/lib/python2.7/dist-packages/odoo/models.py", line 1417, in fields_view_get
    xarch, xfields = View.postprocess_and_fields(self._name, etree.fromstring(result['arch']), view_id)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/ir/ir_ui_view.py", line 903, in postprocess_and_fields
    self.raise_view_error(message, view_id)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/ir/ir_ui_view.py", line 461, in raise_view_error
    raise ValueError(message)
ValueError: Field `technical_name` does not exist

Error context:
View `saas_portal.plans.form`
[view_id: 604, xml_id: saas_portal.view_plans_form, model: saas_portal.plan, parent_id: n/a]

**Comment by repodevs** [comment]
Which version you use ?
I think it's unstable or bug for the new update

**Comment by 360org** [comment]
Im using V10

**Comment by 360org** [comment]
After update New saas code and it show up this.

**Comment by 360org** [comment]
the module demo install but cannot upgrade, when upgrade it show up this. any one know how to fixed it?

**Comment by njeudy** [comment]
@W360S still have this issue ?

**Comment by 360org** [comment]
:) migrated all to saas 11 :) like feature on v11 :) on issues in v10 anymore :)

**Comment by 360org** [comment]
but someone will get same me when they try to update.

**Comment by njeudy** [comment]
Ok I will close for now as I think it is an update issue .. and will wait for new issue for this probleme ..
Upgrade issue can be very difficult to reproduce ..
