### ISSUE TITLE
authentication failed for user odoo on running saas.py

### ISSUE THREAD

**Issue by aamnj** [it-projects-llc/odoo-saas-tools#566]
2017-05-23 19:15:10
saas.py >>> Waiting for port, 127.0.0.1, 8069
ERROR: couldn't create the logfile directory. Logging to the standard output.

2017-05-23 19:15:11
saas.py >>> create database via xmlrpc, saas-portal-10.local
2017-05-23 13:45:11,445 25902 INFO None odoo.sql_db: Connection to the database failed
2017-05-23 13:45:11,446 25902 ERROR None odoo.http: FATAL:  Peer authentication failed for user "odoo"
Traceback (most recent call last):
  File "/opt/odoo/odoo-10.0/odoo/http.py", line 118, in dispatch_rpc
    result = dispatch(method, params)
  File "/opt/odoo/odoo-10.0/odoo/service/db.py", line 381, in dispatch
    return g[exp_method_name](*params)
  File "/opt/odoo/odoo-10.0/odoo/service/db.py", line 92, in exp_create_database
    _create_empty_database(db_name)
  File "/opt/odoo/odoo-10.0/odoo/service/db.py", line 79, in _create_empty_database
    with closing(db.cursor()) as cr:
  File "/opt/odoo/odoo-10.0/odoo/sql_db.py", line 622, in cursor
    return Cursor(self.__pool, self.dbname, self.dsn, serialized=serialized)
  File "/opt/odoo/odoo-10.0/odoo/sql_db.py", line 164, in __init__
    self._cnx = pool.borrow(dsn)
  File "/opt/odoo/odoo-10.0/odoo/sql_db.py", line 505, in _locked
    return fun(self, *args, **kwargs)
  File "/opt/odoo/odoo-10.0/odoo/sql_db.py", line 573, in borrow
    **connection_info)
  File "/usr/lib/python2.7/dist-packages/psycopg2/__init__.py", line 164, in connect
    conn = _connect(dsn, connection_factory=connection_factory, async=async)
OperationalError: FATAL:  Peer authentication failed for user "odoo"

2017-05-23 19:15:11
saas.py >>> xmlrpc database creation error:, <Fault 1: 'Traceback (most recent call last):\n  File "/opt/odoo/odoo-10.0/odoo/service/wsgi_server.py", line 56, in xmlrpc_return\n    result = odoo.http.dispatch_rpc(service, method, params)\n  File "/opt/odoo/odoo-10.0/odoo/http.py", line 118, in dispatch_rpc\n    result = dispatch(method, params)\n  File "/opt/odoo/odoo-10.0/odoo/service/db.py", line 381, in dispatch\n    return g[exp_method_name](*params)\n  File "/opt/odoo/odoo-10.0/odoo/service/db.py", line 92, in exp_create_database\n    _create_empty_database(db_name)\n  File "/opt/odoo/odoo-10.0/odoo/service/db.py", line 79, in _create_empty_database\n    with closing(db.cursor()) as cr:\n  File "/opt/odoo/odoo-10.0/odoo/sql_db.py", line 622, in cursor\n    return Cursor(self.__pool, self.dbname, self.dsn, serialized=serialized)\n  File "/opt/odoo/odoo-10.0/odoo/sql_db.py", line 164, in __init__\n    self._cnx = pool.borrow(dsn)\n  File "/opt/odoo/odoo-10.0/odoo/sql_db.py", line 505, in _locked\n    return fun(self, *args, **kwargs)\n  File "/opt/odoo/odoo-10.0/odoo/sql_db.py", line 573, in borrow\n    **connection_info)\n  File "/usr/lib/python2.7/dist-packages/psycopg2/__init__.py", line 164, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, async=async)\nOperationalError: FATAL:  Peer authentication failed for user "odoo"\n\n'>
2017-05-23 13:45:11,455 25902 INFO None odoo.sql_db: Connection to the database failed
2017-05-23 13:45:11,455 25902 ERROR saas-portal-10.local odoo.http: FATAL:  Peer authentication failed for user "odoo"
Traceback (most recent call last):
  File "/opt/odoo/odoo-10.0/odoo/http.py", line 118, in dispatch_rpc
    result = dispatch(method, params)
  File "/opt/odoo/odoo-10.0/odoo/service/common.py", line 57, in dispatch
    return g[exp_method_name](*params)
  File "/opt/odoo/odoo-10.0/odoo/service/common.py", line 29, in exp_authenticate
    res_users = odoo.registry(db)['res.users']
  File "/opt/odoo/odoo-10.0/odoo/__init__.py", line 52, in registry
    return modules.registry.Registry(database_name)
  File "/opt/odoo/odoo-10.0/odoo/modules/registry.py", line 59, in __new__
    return cls.new(db_name)
  File "/opt/odoo/odoo-10.0/odoo/modules/registry.py", line 71, in new
    registry.init(db_name)
  File "/opt/odoo/odoo-10.0/odoo/modules/registry.py", line 139, in init
    with closing(self.cursor()) as cr:
  File "/opt/odoo/odoo-10.0/odoo/modules/registry.py", line 458, in cursor
    return self._db.cursor()
  File "/opt/odoo/odoo-10.0/odoo/sql_db.py", line 622, in cursor
    return Cursor(self.__pool, self.dbname, self.dsn, serialized=serialized)
  File "/opt/odoo/odoo-10.0/odoo/sql_db.py", line 164, in __init__
    self._cnx = pool.borrow(dsn)
  File "/opt/odoo/odoo-10.0/odoo/sql_db.py", line 505, in _locked
    return fun(self, *args, **kwargs)
  File "/opt/odoo/odoo-10.0/odoo/sql_db.py", line 573, in borrow
    **connection_info)
  File "/usr/lib/python2.7/dist-packages/psycopg2/__init__.py", line 164, in connect
    conn = _connect(dsn, connection_factory=connection_factory, async=async)
OperationalError: FATAL:  Peer authentication failed for user "odoo"

Traceback (most recent call last):
  File "saas.py", line 187, in main
    install_modules=portal_modules)
  File "saas.py", line 295, in rpc_init_db
    auth = rpc_auth(dbname, admin_password=args.get('admin_password'))
  File "saas.py", line 278, in rpc_auth
    admin_uid = common.authenticate(dbname, admin_username, admin_password, {})
  File "/usr/lib/python2.7/xmlrpclib.py", line 1243, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1602, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1283, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1316, in single_request
    return self.parse_response(response)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1493, in parse_response
    return u.close()
  File "/usr/lib/python2.7/xmlrpclib.py", line 800, in close
    raise Fault(**self._stack[0])
Fault: <Fault 1: 'Traceback (most recent call last):\n  File "/opt/odoo/odoo-10.0/odoo/service/wsgi_server.py", line 56, in xmlrpc_return\n    result = odoo.http.dispatch_rpc(service, method, params)\n  File "/opt/odoo/odoo-10.0/odoo/http.py", line 118, in dispatch_rpc\n    result = dispatch(method, params)\n  File "/opt/odoo/odoo-10.0/odoo/service/common.py", line 57, in dispatch\n    return g[exp_method_name](*params)\n  File "/opt/odoo/odoo-10.0/odoo/service/common.py", line 29, in exp_authenticate\n    res_users = odoo.registry(db)[\'res.users\']\n  File "/opt/odoo/odoo-10.0/odoo/__init__.py", line 52, in registry\n    return modules.registry.Registry(database_name)\n  File "/opt/odoo/odoo-10.0/odoo/modules/registry.py", line 59, in __new__\n    return cls.new(db_name)\n  File "/opt/odoo/odoo-10.0/odoo/modules/registry.py", line 71, in new\n    registry.init(db_name)\n  File "/opt/odoo/odoo-10.0/odoo/modules/registry.py", line 139, in init\n    with closing(self.cursor()) as cr:\n  File "/opt/odoo/odoo-10.0/odoo/modules/registry.py", line 458, in cursor\n    return self._db.cursor()\n  File "/opt/odoo/odoo-10.0/odoo/sql_db.py", line 622, in cursor\n    return Cursor(self.__pool, self.dbname, self.dsn, serialized=serialized)\n  File "/opt/odoo/odoo-10.0/odoo/sql_db.py", line 164, in __init__\n    self._cnx = pool.borrow(dsn)\n  File "/opt/odoo/odoo-10.0/odoo/sql_db.py", line 505, in _locked\n    return fun(self, *args, **kwargs)\n  File "/opt/odoo/odoo-10.0/odoo/sql_db.py", line 573, in borrow\n    **connection_info)\n  File "/usr/lib/python2.7/dist-packages/psycopg2/__init__.py", line 164, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, async=async)\nOperationalError: FATAL:  Peer authentication failed for user "odoo"\n\n'>

2017-05-23 19:15:11
saas.py >>> KILL, 25899

**Comment by repodevs** [comment]
your odoo can't access to database, make sure you have done with database configuration.

**Comment by aamnj** [comment]
where to edit the database changes?

**Comment by repodevs** [comment]
@Since95 do you mean database configuration?
to change database configuration (credential) change in your `odoo.conf` file

**Comment by njeudy** [comment]
@Since95 you have to setup your postgresql to accept connection and to have odoo user with correct password.

It is a setup issue, will close it know. feel free to open new one if you encounter this again.
