### ISSUE TITLE
Create template DB error,with plans.

### ISSUE THREAD

**Issue by javacaoyu** [it-projects-llc/odoo-saas-tools#593]
HI guys:
i follow the manual with https://odoo-saas-tools.readthedocs.io/en/10.0/setup/install.html
when work to create templater DB  , i got this error:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 675, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 331, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 324, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 504, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/site-packages/odoo/addons/web/controllers/main.py", line 889, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/lib/python2.7/site-packages/odoo/addons/web/controllers/main.py", line 877, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python2.7/site-packages/odoo/api.py", line 681, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python2.7/site-packages/odoo/api.py", line 672, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/odoo/addons/saas_portal/models/saas_portal.py", line 358, in create_template_button
    res = self.create_template()
  File "/usr/lib/python2.7/site-packages/odoo/addons/saas_portal/models/saas_portal.py", line 379, in create_template
    raise Warning('Error on request: %s\nReason: %s \n Message: %s' % (req.url, res.reason, res.content))
Warning: Error on request: http://s1.odoo.local:8069/saas_server/new_database
Reason: INTERNAL SERVER ERROR 
 Message: <urlopen error [Errno 111] Connection refused>

i setting odoo deploy machine hosts same with manual, it like :
127.0.0.1 odoo.local # portal
127.0.0.1 s1.odoo.local # server
127.0.0.1 t1.odoo.local # template
127.0.0.1 t2.odoo.local # template
127.0.0.1 client-x.odoo.local
127.0.0.1 client-y.odoo.local
127.0.0.1 client-z.odoo.local

and set my client machine hosts file to:
10.211.55.8 www.odoo.local
10.211.55.8 odoo.local # portal
10.211.55.8 s1.odoo.local # server
10.211.55.8 t1.odoo.local # template
10.211.55.8 t2.odoo.local # template
10.211.55.8 client-x.odoo.local
10.211.55.8 client-y.odoo.local
10.211.55.8 client-z.odoo.local

The ip of 10.211.55.8 is the odoo machine's ip. odoo deploy on it.

I don't use the nginx because i don't know how to use it. 
so i config my client machine hosts let me can use the domain name to access odoo web page.
For example: in chrome enter: odoo.local:8069    i can access the odoo web page and select the database with 'odoo.local'
dbfliter with %h

please help me. thanks all guys very much.

im not english man , so english is not good , hope you can understand. tks.

**Comment by javacaoyu** [comment]
i use version 10.0

**Comment by javacaoyu** [comment]
i need help, can anybody help me. very thanks.
i love you all.

**Comment by yelizariev** [comment]
THere are probably more logs that describe internal error. But anyway my bet is that SaaS server has wrong local host and port values on oauth provider

**Comment by javacaoyu** [comment]
Thanks for you comment yelizariev. 
First, I not use nginx to map 80 port to  8069
But when i use nginx to map port, i create template DB has success.
i don't know why , the nginx config is use the docs provide.

**Comment by njeudy** [comment]
You can not have all odoo instance on same port without proxy map.
So you have to keep nginx and open on 10.211.55.8

here is the explain:

10.211.55.8 odoo.local # portal (take 8069 port)
10.211.55.8 s1.odoo.local # server (so 8069 port no available)
10.211.55.8 t1.odoo.local # template (so 8069 port no available)

nginx should be open on 10.211.55.8:80 (or 8069 if you want) and should map all odoo instance (docker I think ..)
