### ISSUE TITLE
Unable to configure and set Paramaters in Odoo Saas Clients

### ISSUE THREAD

**Issue by sathwiksunderreddy** [it-projects-llc/odoo-saas-tools#599]
Hi I had installed and configured Saas module in odoo I was successfull in configuringing I am able to create Plans and Clients but when I am trying to configure the parameters it throughs an error like : 
```

Odoo Server Error
Traceback (most recent call last):
  File "D:\New odoo\odoo-8.0-20170403\openerp\http.py", line 544, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "D:\New odoo\odoo-8.0-20170403\openerp\http.py", line 581, in dispatch
    result = self._call_function(**self.params)
  File "D:\New odoo\odoo-8.0-20170403\openerp\http.py", line 317, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "D:\New odoo\odoo-8.0-20170403\openerp\service\model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "D:\New odoo\odoo-8.0-20170403\openerp\http.py", line 314, in checked_call
    return self.endpoint(*a, **kw)
  File "D:\New odoo\odoo-8.0-20170403\openerp\http.py", line 810, in __call__
    return self.method(*args, **kw)
  File "D:\New odoo\odoo-8.0-20170403\openerp\http.py", line 410, in response_wrap
    response = f(*args, **kw)
  File "D:\New odoo\odoo-8.0-20170403\openerp\addons\web\controllers\main.py", line 948, in call_button
    action = self._call_kw(model, method, args, {})
  File "D:\New odoo\odoo-8.0-20170403\openerp\addons\web\controllers\main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "D:\New odoo\odoo-8.0-20170403\openerp\api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "D:\New odoo\odoo-8.0-20170403\openerp\api.py", line 399, in old_api
    result = method(recs, *args, **kwargs)
  File "D:\New odoo\odoo-8.0-20170403\openerp\addons\saas_portal\wizard\config_wizard.py", line 36, in execute_action
    res = getattr(self, method)()
  File "D:\New odoo\odoo-8.0-20170403\openerp\api.py", line 266, in wrapper
    return new_api(self, *args, **kwargs)
  File "D:\New odoo\odoo-8.0-20170403\openerp\addons\saas_portal\wizard\config_wizard.py", line 58, in upgrade_database
    res = self.database_ids.upgrade(payload=payload)
  File "D:\New odoo\odoo-8.0-20170403\openerp\api.py", line 266, in wrapper
    return new_api(self, *args, **kwargs)
  File "D:\New odoo\odoo-8.0-20170403\openerp\addons\saas_portal_backup\models\saas_portal.py", line 29, in upgrade
    database_obj._backup()
  File "D:\New odoo\odoo-8.0-20170403\openerp\api.py", line 266, in wrapper
    return new_api(self, *args, **kwargs)
  File "D:\New odoo\odoo-8.0-20170403\openerp\addons\saas_portal\models\saas_portal.py", line 469, in _backup
    raise Warning(warning)
Warning: Transport agent has not been configured

```

I am unable to understand what step I had missed and what this Transport error refers to I have found nothing about this in the odoo forum 
can any one please help me out of this

Thanks in Advance @yelizariev

**Comment by yelizariev** [comment]
You have to remove saas_portal_backup module or install one of saas_server_backup_* module

**Comment by yelizariev** [comment]
@ilmir-k can you make error message be more clear?

**Comment by sathwiksunderreddy** [comment]
Hi Ivan yes I have uninstalled the Saas_portal_Backup module and Its working fine now Iam able to set the Parameters for clients Thanks:-)

**Comment by sathwiksunderreddy** [comment]
One more query that when ever Iam creating a new Plan or a new Client Should I have to add the database names in /etc/hosts file 

as only the links that are given in that file are opening it

 Is this should be done manually for each and every client

**Comment by yelizariev** [comment]
@sathwiksunderreddy open new issues  for new questions, please
