### ISSUE TITLE
saas_portal/wizard/config_wizard.py has error AttributeError: 'int' object has no attribute 'server_id'

### ISSUE THREAD

**Issue by javacaoyu** [it-projects-llc/odoo-saas-tools#600]
Use xmlrpc with https://odoo-saas-tools.readthedocs.io/en/10.0/api.html
And do :
Suspend client database
To suspend client database its id should be known.

To suspend:

```
saas_portal_client_id = ids[0]
data = {'params': [{'key': 'saas_client.suspended', 'value': '1', 'hidden': True}]}
res = models.execute_kw(portal_db, admin_uid, admin_password,
                     'saas.config', 'do_upgrade_database',
                     [data, saas_portal_client_id])
```
get some error.
and Limit number of users for client database function has same error.

Odoo version 10.0 
odoo saas tool version 10.0

2017-06-22 08:53:01,201 12986 ERROR portal.odootest.com odoo.http: 'int' object has no attribute 'server_id'
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 118, in dispatch_rpc
    result = dispatch(method, params)
  File "/usr/lib/python2.7/site-packages/odoo/service/model.py", line 38, in dispatch
    res = fn(db, uid, *params)
  File "/usr/lib/python2.7/site-packages/odoo/service/model.py", line 157, in execute_kw
    return execute(db, uid, obj, method, *args, **kw or {})
  File "/usr/lib/python2.7/site-packages/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/odoo/service/model.py", line 164, in execute
    res = execute_cr(cr, uid, obj, method, *args, **kw)
  File "/usr/lib/python2.7/site-packages/odoo/service/model.py", line 153, in execute_cr
    return odoo.api.call_kw(recs, method, args, kw)
  File "/usr/lib/python2.7/site-packages/odoo/api.py", line 679, in call_kw
    return call_kw_model(method, model, args, kwargs)
  File "/usr/lib/python2.7/site-packages/odoo/api.py", line 664, in call_kw_model
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/odoo/addons/saas_portal/wizard/config_wizard.py", line 79, in do_upgrade_database
    req, req_kwargs = database_record.server_id._request_server(
AttributeError: 'int' object has no attribute 'server_id'

**Comment by njeudy** [comment]
@iledarn did you work on this ?

database_record is an id when passing it through xmlrpc .. should do browse I think
