### ISSUE TITLE
expand max allowed users

### ISSUE THREAD

**Issue by clxadmin** [it-projects-llc/odoo-saas-tools#635]
Hi
I try to expand max allowed users from 2 to 4. After setting to Limit Number of Records:
Model: res.users
Maximum Records: 4
>> execute

Im facing this error: {"mydatabase.com": {"owner_id": "Owner's user is not found"}}

after that I try to execute again....allways getting this error
the max allowed user is still on 2

Can anyone help please?

**Comment by clxadmin** [comment]
Hello, I try to do the same on the runbot -- and this produces also a error message like you see below. How to expand allowed users for a client ?? Can anyone help please?

runbot: http://07194-10-0-1d8a16--base---portal.runbot.it-projects.info

Odoo Server Error
Traceback (most recent call last):
  File "/mnt/odoo-extra/runbot/static/build/07194-10-0-1d8a16/odoo/http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/mnt/odoo-extra/runbot/static/build/07194-10-0-1d8a16/odoo/http.py", line 677, in dispatch
    result = self._call_function(**self.params)
  File "/mnt/odoo-extra/runbot/static/build/07194-10-0-1d8a16/odoo/http.py", line 333, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/mnt/odoo-extra/runbot/static/build/07194-10-0-1d8a16/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/mnt/odoo-extra/runbot/static/build/07194-10-0-1d8a16/odoo/http.py", line 326, in checked_call
    result = self.endpoint(*a, **kw)
  File "/mnt/odoo-extra/runbot/static/build/07194-10-0-1d8a16/odoo/http.py", line 935, in __call__
    return self.method(*args, **kw)
  File "/mnt/odoo-extra/runbot/static/build/07194-10-0-1d8a16/odoo/http.py", line 506, in response_wrap
    response = f(*args, **kw)
  File "/mnt/odoo-extra/runbot/static/build/07194-10-0-1d8a16/odoo/addons/web/controllers/main.py", line 889, in call_button
    action = self._call_kw(model, method, args, {})
  File "/mnt/odoo-extra/runbot/static/build/07194-10-0-1d8a16/odoo/addons/web/controllers/main.py", line 877, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/mnt/odoo-extra/runbot/static/build/07194-10-0-1d8a16/odoo/api.py", line 681, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/mnt/odoo-extra/runbot/static/build/07194-10-0-1d8a16/odoo/api.py", line 672, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/mnt/odoo-extra/runbot/static/build/07194-10-0-1d8a16/odoo/addons/saas_portal/wizard/config_wizard.py", line 37, in execute_action
    res = getattr(self, method)()
  File "/mnt/odoo-extra/runbot/static/build/07194-10-0-1d8a16/odoo/addons/saas_portal/wizard/config_wizard.py", line 61, in upgrade_database
    res = self.database_ids.upgrade(payload=payload)
  File "/mnt/odoo-extra/runbot/static/build/07194-10-0-1d8a16/odoo/addons/saas_portal_backup/models/saas_portal.py", line 29, in upgrade
    database_obj._backup()
  File "/mnt/odoo-extra/runbot/static/build/07194-10-0-1d8a16/odoo/addons/saas_portal/models/saas_portal.py", line 493, in _backup
    raise Warning(warning)
Warning: 'NoneType' object has no attribute 'startswith'

**Comment by clxadmin** [comment]
I have got the workaround from it-projects:

As an alternative way, you can change max allowed user from client DB directly:
1. Login to client DB
2. Activate the developer mode
3. Go to Settings >> Technical >> Parameters >> System Parameters
4. Open saas_client.max_users item and set Value as 4
5. Save changes
6. Go to SaaS Portal >> Client DB form and click on Sync Client to see the changes
