### ISSUE TITLE
Error Creating TemplateDB from Plan

### ISSUE THREAD

**Issue by butagreeza** [it-projects-llc/odoo-saas-tools#636]
Am trying to create a TemplateDB but am having this error.

Traceback (most recent call last):
File "/var/repo/mautinoa/odoo/odoo/http.py", line 638, in _handle_exception
return super(JsonRequest, self)._handle_exception(exception)
File "/var/repo/mautinoa/odoo/odoo/http.py", line 675, in dispatch
result = self._call_function(**self.params)
File "/var/repo/mautinoa/odoo/odoo/http.py", line 331, in _call_function
return checked_call(self.db, *args, **kwargs)
File "/var/repo/mautinoa/odoo/odoo/service/model.py", line 119, in wrapper
return f(dbname, *args, **kwargs)
File "/var/repo/mautinoa/odoo/odoo/http.py", line 324, in checked_call
result = self.endpoint(*a, **kw)
File "/var/repo/mautinoa/odoo/odoo/http.py", line 933, in call
return self.method(*args, **kw)
File "/var/repo/mautinoa/odoo/odoo/http.py", line 504, in response_wrap
response = f(*args, **kw)
File "/var/repo/mautinoa/odoo/addons/web/controllers/main.py", line 882, in call_button
action = self._call_kw(model, method, args, {})
File "/var/repo/mautinoa/odoo/addons/web/controllers/main.py", line 870, in _call_kw
return call_kw(request.env[model], method, args, kwargs)
File "/var/repo/mautinoa/odoo/odoo/api.py", line 681, in call_kw
return call_kw_multi(method, model, args, kwargs)
File "/var/repo/mautinoa/odoo/odoo/api.py", line 672, in call_kw_multi
result = method(recs, *args, **kwargs)
File "/var/repo/mautinoa/odoo/custom/community/saas_portal/models/saas_portal.py", line 351, in create_template_button
res = self.create_template()
File "/var/repo/mautinoa/odoo/custom/community/saas_portal/models/saas_portal.py", line 374, in create_template
data = simplejson.loads(res.text)
File "/var/repo/env/mautinoa/local/lib/python2.7/site-packages/simplejson/init.py", line 516, in loads
return _default_decoder.decode(s)
File "/var/repo/env/mautinoa/local/lib/python2.7/site-packages/simplejson/decoder.py", line 370, in decode
obj, end = self.raw_decode(s)
File "/var/repo/env/mautinoa/local/lib/python2.7/site-packages/simplejson/decoder.py", line 400, in raw_decode
return self.scan_once(s, idx=_w(s, idx).end())
JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Any suggestions??

**Comment by minhyk** [comment]
It seems the simplejson is not up to date. Try to upgrade it then try again.

**Comment by njeudy** [comment]
@butagreeza can you say which odoo version you use ?

Did you encounter this issue today or is it solved ?

**Comment by butagreeza** [comment]
@njeudy the issue has been resolved. Thanks.

**Comment by cedvict** [comment]
@butagreeza Pls can you explain how to resolve this issue?

**Comment by butagreeza** [comment]
@cedvict I installed the latest version of simplejson and the error was fixed. I was using odoo 10

**Comment by 360org** [comment]
You need to use pip3 not pip

Thanks & Best Regards
Chau Le’s
World 360° Services
Sent from iPhone

On Apr 27, 2018, at 23:56, Francis Bangura <notifications@github.com<mailto:notifications@github.com>> wrote:


@cedvict<https://github.com/cedvict> I installed the latest version of simplejson and the error was fixed. I was using odoo 10
