### ISSUE TITLE
issue installation addon SaaS Portal - /page/start

### ISSUE THREAD

**Issue by namnguyenx6** [it-projects-llc/odoo-saas-tools#65]
I can not install addon SaaS Portal - /page/start in SaaS Tool for Odoo 9.

Odoo Server Error
Traceback (most recent call last):
  File "/opt/odoo/odoo/openerp/http.py", line 599, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo/openerp/http.py", line 636, in dispatch
    result = self._call_function(*_self.params)
  File "/opt/odoo/odoo/openerp/http.py", line 315, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/opt/odoo/odoo/openerp/service/model.py", line 118, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/opt/odoo/odoo/openerp/http.py", line 308, in checked_call
    result = self.endpoint(_a, *_kw)
  File "/opt/odoo/odoo/openerp/http.py", line 887, in __call__
    return self.method(_args, *_kw)
  File "/opt/odoo/odoo/openerp/http.py", line 465, in response_wrap
    response = f(_args, *_kw)
  File "/opt/odoo/odoo/addons/web/controllers/main.py", line 975, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/odoo/addons/web/controllers/main.py", line 963, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "/opt/odoo/odoo/openerp/api.py", line 232, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo/openerp/addons/base/module/module.py", line 459, in button_immediate_install
    return self._button_immediate_function(cr, uid, ids, self.button_install, context=context)
  File "/opt/odoo/odoo/openerp/api.py", line 232, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo/openerp/addons/base/module/module.py", line 533, in _button_immediate_function
    registry = openerp.modules.registry.RegistryManager.new(cr.dbname, update_module=True)
  File "/opt/odoo/odoo/openerp/modules/registry.py", line 385, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/odoo/openerp/modules/loading.py", line 337, in load_modules
    loaded_modules, update_module)
  File "/opt/odoo/odoo/openerp/modules/loading.py", line 237, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/opt/odoo/odoo/openerp/modules/loading.py", line 156, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/opt/odoo/odoo/openerp/modules/loading.py", line 98, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/opt/odoo/odoo/openerp/tools/convert.py", line 852, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/opt/odoo/odoo/openerp/tools/convert.py", line 939, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/opt/odoo/odoo/openerp/tools/convert.py", line 802, in parse
    self.parse(rec, mode)
  File "/opt/odoo/odoo/openerp/tools/convert.py", line 805, in parse
    self._tags[rec.tag](self.cr, rec, de, mode=mode)
  File "/opt/odoo/odoo/openerp/tools/convert.py", line 778, in _tag_template
    return self._tag_record(cr, record, data_node)
  File "/opt/odoo/odoo/openerp/tools/convert.py", line 701, in _tag_record
    f_val = self.id_get(cr, f_ref)
  File "/opt/odoo/odoo/openerp/tools/convert.py", line 783, in id_get
    res = self.model_id_get(cr, id_str, raise_if_not_found)
  File "/opt/odoo/odoo/openerp/tools/convert.py", line 794, in model_id_get
    raise_if_not_found=raise_if_not_found)
  File "/opt/odoo/odoo/openerp/api.py", line 232, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo/openerp/addons/base/ir/ir_model.py", line 966, in xmlid_to_res_model_res_id
    return self.xmlid_lookup(cr, uid, xmlid)[1:3]
  File "/opt/odoo/odoo/openerp/api.py", line 232, in wrapper
    return old_api(self, _args, *_kwargs)
  File "<string>", line 2, in xmlid_lookup
  File "/opt/odoo/odoo/openerp/tools/cache.py", line 85, in lookup
    value = d[key] = self.method(_args, *_kwargs)
  File "/opt/odoo/odoo/openerp/addons/base/ir/ir_model.py", line 956, in xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % (xmlid))
ParseError: "External ID not found in the system: website.theme" while parsing None:6, near
<data inherit_id="website.theme" name="saas portal assets">
            <xpath expr="//link[@href='/website/static/src/css/website.css']" position="before">
                <link rel="stylesheet" href="/saas_portal_start/static/src/css/odoo.css" t-ignore="true"/>
            </xpath>
        </data>

**Comment by ebukoz** [comment]
This is fixed on the 9.0-dev branch.. check it out. big thanks to @yelizariev
