### ISSUE TITLE
Error with SaaS Portal - templates

### ISSUE THREAD

**Issue by dawnblack2** [it-projects-llc/odoo-saas-tools#654]
I have installed SaaS Portal - templates module. and run on your docker 
When i run my link with http://portal.portal-saas.bc/saas_portal_templates/select-template
The error 500: Internal Server Error
with content 
Error
Error message:

'website' object has no attribute 'render'
Traceback
Traceback (most recent call last):
  File "/mnt/odoo-source/addons/website/models/ir_http.py", line 273, in _handle_exception
    response = super(Http, cls)._handle_exception(exception)
  File "/mnt/odoo-source/odoo/addons/base/ir/ir_http.py", line 169, in _handle_exception
    return request._handle_exception(exception)
  File "/mnt/odoo-source/odoo/http.py", line 768, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/mnt/odoo-source/odoo/addons/base/ir/ir_http.py", line 195, in _dispatch
    result = request.dispatch()
  File "/mnt/odoo-source/odoo/http.py", line 827, in dispatch
    r = self._call_function(**self.params)
  File "/mnt/odoo-source/odoo/http.py", line 333, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/mnt/odoo-source/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/mnt/odoo-source/odoo/http.py", line 326, in checked_call
    result = self.endpoint(*a, **kw)
  File "/mnt/odoo-source/odoo/http.py", line 935, in __call__
    return self.method(*args, **kw)
  File "/mnt/odoo-source/odoo/http.py", line 506, in response_wrap
    response = f(*args, **kw)
  File "/mnt/addons/it-projects-llc/odoo-saas-tools/saas_portal_templates/controllers/main.py", line 16, in select_template
    return request.website.render("saas_portal_templates.select_template", values)
AttributeError: 'website' object has no attribute 'render'

**Comment by njeudy** [comment]
@dawnblack2 hello, I try to do triage on issue

can you give me odoo version you use and if you  always encounter the issue ? thanks

**Comment by GoodERPJeff** [comment]
I got the same message, version is 10

**Comment by njeudy** [comment]
think it is resolved now, feel free to reopen bug if you encouter this.
