### ISSUE TITLE
Error on automated install with saas.py

### ISSUE THREAD

**Issue by gsusrafael** [it-projects-llc/odoo-saas-tools#706]
I've been checking the automated install process and looking at the output, but i found this weird error:

```
2017-12-07 16:29:00
saas.py >>> RPC Execute, ir.module.module, button_immediate_install, [[360, 183, 64]], {}
Traceback (most recent call last):
  File "saas.py", line 190, in main
    install_modules=portal_modules)
  File "saas.py", line 303, in rpc_init_db
    rpc_execute_kw(auth, 'ir.module.module', 'button_immediate_install', [module_ids])
  File "saas.py", line 295, in rpc_execute_kw
    model, method, rpc_args, rpc_kwargs)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1243, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1602, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1283, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1316, in single_request
    return self.parse_response(response)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1493, in parse_response
    return u.close()
  File "/usr/lib/python2.7/xmlrpclib.py", line 800, in close
    raise Fault(**self._stack[0])
Fault: <Fault 2: ''>
```

**Comment by HAHGX** [comment]
What version are you working on? v10?

**Comment by gsusrafael** [comment]
sure, v10 @xuanox
