### ISSUE TITLE
Saas automated script saas.py setup issue

### ISSUE THREAD

**Issue by saitejaganapavarapu** [it-projects-llc/odoo-saas-tools#715]
Hello all, I am using https://github.com/it-projects-llc/odoo-saas-tools to setup a saas for my odoo instance, I am using the saas.py automated script to setup saas, I was struck at this issue, could someone take a look and help me out, thanks in advacne

saas.py >>> RPC Execute, ir.module.module, button_immediate_install, [[358, 185, 65]], {}
2018-01-03 06:28:29,160 17029 INFO saas-portal-10.local odoo.modules.loading: loading 1 modules...
2018-01-03 06:28:29,279 17029 INFO saas-portal-10.local odoo.modules.loading: 1 modules loaded in 0.12s, 0 queries 2018-01-03 06:28:29,286 17029 INFO saas-portal-10.local odoo.modules.loading: loading 9 modules...
2018-01-03 06:28:29,323 17029 INFO saas-portal-10.local odoo.modules.loading: 9 modules loaded in 0.04s, 0 queries 2018-01-03 06:28:29,488 17029 INFO saas-portal-10.local odoo.modules.loading: Modules loaded.
2018-01-03 06:28:29,748 17029 INFO saas-portal-10.local werkzeug: 127.0.0.1 - - [03/Jan/2018 06:28:29] "POST /xmlrpc/2/object HTTP/1.1" 200 - Traceback (most recent call last):
  File "saas.py", line 190, in main
    install_modules=portal_modules)
  File "saas.py", line 303, in rpc_init_db
    rpc_execute_kw(auth, 'ir.module.module', 'button_immediate_install', [module_ids])
  File "saas.py", line 295, in rpc_execute_kw
    model, method, rpc_args, rpc_kwargs)
  File "/usr/local/lib/python2.7/xmlrpclib.py", line 1233, in __call__
    return self.__send(self.__name, args)
  File "/usr/local/lib/python2.7/xmlrpclib.py", line 1591, in __request
    verbose=self.__verbose
  File "/usr/local/lib/python2.7/xmlrpclib.py", line 1273, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/local/lib/python2.7/xmlrpclib.py", line 1306, in single_request
    return self.parse_response(response)
  File "/usr/local/lib/python2.7/xmlrpclib.py", line 1482, in parse_response
    return u.close()
  File "/usr/local/lib/python2.7/xmlrpclib.py", line 794, in close
    raise Fault(**self._stack[0])
Fault: <Fault 2: ''>

**Comment by HAHGX** [comment]
What version are you working on? v10?

**Comment by saitejaganapavarapu** [comment]
Hello xuanox, thanks for your reply, I am using v10
