### ISSUE TITLE
When install saas.py, get an error problem:AttributeError: 'NoneType' object has no attribute 'endswith'

### ISSUE THREAD

**Issue by keecome** [it-projects-llc/odoo-saas-tools#744]
version: odoo 10.0
server:ubuntu 16.04 server
webservice: NGINX
InstallScript: Yenthe666/InstallScript

odoo is Run normal.

root@Kvmla:/data/odoo/custom/it-projects-llc/odoo-saas-tools# python saas.py --portal-create --server-create --plan-create --run --odoo-script=/data/odoo/odoo-server/odoo-bin --odoo-config=/etc/odoo-server.conf

.....

2018-02-21 19:56:18
saas.py >>> RPC Execute, saas_portal.database, create, [{'name': 't1.local.com'}], {}

2018-02-21 19:56:18
saas.py >>> auth, ('local.com', <ServerProxy for local.com:8069/xmlrpc/2/object>, 1, 'admin')

2018-02-21 19:56:18
saas.py >>> RPC Execute, saas_portal.plan, create, [{'server_id': 1, 'dbname_template': 'c1.local.com', 'name': 'Plan', 'template_id': 1}], {}

2018-02-21 19:56:18
saas.py >>> Dropping  database t1.local.com

2018-02-21 19:56:18
saas.py >>> Result: DROP DATABASE
Traceback (most recent call last):
  File "saas.py", line 201, in main
    plan_id = rpc_create_plan(args.get('portal_db_name'))
  File "saas.py", line 439, in rpc_create_plan
    dropdb(plan_template_db_name)
  File "saas.py", line 262, in dropdb
    paths = [os.path.join(datadir, 'filestore', dbname)]
  File "/usr/lib/python2.7/posixpath.py", line 70, in join
    elif path == '' or path.endswith('/'):
AttributeError: 'NoneType' object has no attribute 'endswith'

I've been referring to a lot of online methods, but I can't solve it.
Who can help me solve it?

**Comment by keecome** [comment]
I have solved it!
