### ISSUE TITLE
install saas_portal_portal Error:website_portal.portal_layout 

### ISSUE THREAD

**Issue by keecome** [it-projects-llc/odoo-saas-tools#745]
`Traceback (most recent call last):
  File "/data/odoo/odoo-server/odoo/tools/cache.py", line 84, in lookup
    r = d[key]
  File "/data/odoo/odoo-server/odoo/tools/func.py", line 68, in wrapper
    return func(self, *args, **kwargs)
  File "/data/odoo/odoo-server/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: ('ir.model.data', <function IrModelData.xmlid_lookup at 0x7fe999466488>, 'website_portal.portal_layout')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/odoo/odoo-server/odoo/tools/convert.py", line 741, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/data/odoo/odoo-server/odoo/tools/convert.py", line 719, in _tag_template
    return self._tag_record(record, data_node)
  File "/data/odoo/odoo-server/odoo/tools/convert.py", line 639, in _tag_record
    f_val = self.id_get(f_ref)
  File "/data/odoo/odoo-server/odoo/tools/convert.py", line 724, in id_get
    res = self.model_id_get(id_str, raise_if_not_found)
  File "/data/odoo/odoo-server/odoo/tools/convert.py", line 730, in model_id_get
    return self.env['ir.model.data'].xmlid_to_res_model_res_id(id_str, raise_if_not_found=raise_if_not_found)
  File "/data/odoo/odoo-server/odoo/addons/base/ir/ir_model.py", line 1316, in xmlid_to_res_model_res_id
    return self.xmlid_lookup(xmlid)[1:3]
  File "<decorator-gen-21>", line 2, in xmlid_lookup
  File "/data/odoo/odoo-server/odoo/tools/cache.py", line 89, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/data/odoo/odoo-server/odoo/addons/base/ir/ir_model.py", line 1305, in xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % xmlid)
ValueError: External ID not found in the system: website_portal.portal_layout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/odoo/odoo-server/odoo/http.py", line 647, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/data/odoo/odoo-server/odoo/http.py", line 307, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/data/odoo/odoo-server/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/data/odoo/odoo-server/odoo/http.py", line 689, in dispatch
    result = self._call_function(**self.params)
  File "/data/odoo/odoo-server/odoo/http.py", line 339, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/data/odoo/odoo-server/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/data/odoo/odoo-server/odoo/http.py", line 332, in checked_call
    result = self.endpoint(*a, **kw)
  File "/data/odoo/odoo-server/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/data/odoo/odoo-server/odoo/http.py", line 512, in response_wrap
    response = f(*args, **kw)
  File "/data/odoo/odoo-server/addons/web/controllers/main.py", line 934, in call_button
    action = self._call_kw(model, method, args, {})
  File "/data/odoo/odoo-server/addons/web/controllers/main.py", line 922, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/data/odoo/odoo-server/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/data/odoo/odoo-server/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-40>", line 2, in button_immediate_install
  File "/data/odoo/odoo-server/odoo/addons/base/module/module.py", line 71, in check_and_log
    return method(self, *args, **kwargs)
  File "/data/odoo/odoo-server/odoo/addons/base/module/module.py", line 448, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/data/odoo/odoo-server/odoo/addons/base/module/module.py", line 541, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/data/odoo/odoo-server/odoo/modules/registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/data/odoo/odoo-server/odoo/modules/loading.py", line 343, in load_modules
    loaded_modules, update_module)
  File "/data/odoo/odoo-server/odoo/modules/loading.py", line 242, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/data/odoo/odoo-server/odoo/modules/loading.py", line 156, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/data/odoo/odoo-server/odoo/modules/loading.py", line 94, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/data/odoo/odoo-server/odoo/tools/convert.py", line 788, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/data/odoo/odoo-server/odoo/tools/convert.py", line 849, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/data/odoo/odoo-server/odoo/tools/convert.py", line 748, in parse
    exc_info[2]
  File "/data/odoo/odoo-server/odoo/tools/pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "/data/odoo/odoo-server/odoo/tools/convert.py", line 741, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/data/odoo/odoo-server/odoo/tools/convert.py", line 719, in _tag_template
    return self._tag_record(record, data_node)
  File "/data/odoo/odoo-server/odoo/tools/convert.py", line 639, in _tag_record
    f_val = self.id_get(f_ref)
  File "/data/odoo/odoo-server/odoo/tools/convert.py", line 724, in id_get
    res = self.model_id_get(id_str, raise_if_not_found)
  File "/data/odoo/odoo-server/odoo/tools/convert.py", line 730, in model_id_get
    return self.env['ir.model.data'].xmlid_to_res_model_res_id(id_str, raise_if_not_found=raise_if_not_found)
  File "/data/odoo/odoo-server/odoo/addons/base/ir/ir_model.py", line 1316, in xmlid_to_res_model_res_id
    return self.xmlid_lookup(xmlid)[1:3]
  File "<decorator-gen-21>", line 2, in xmlid_lookup
  File "/data/odoo/odoo-server/odoo/tools/cache.py", line 89, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/data/odoo/odoo-server/odoo/addons/base/ir/ir_model.py", line 1305, in xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % xmlid)
odoo.tools.convert.ParseError: "External ID not found in the system: website_portal.portal_layout" while parsing None:65, near
<data name="Account" inherit_id="website_portal.portal_layout">
    <xpath expr="//div[contains(@class,'mb64')]" position="inside">
      <t t-call="saas_portal_portal.stats"/>
    </xpath>
  </data>`

who can help me.

**Comment by 360org** [comment]
Missing web portal.

Thanks & Best Regards
Chau Le’s
World 360° Services
Sent from iPhone

On Mar 1, 2018, at 00:25, keecome <notifications@github.com<mailto:notifications@github.com>> wrote:


`Traceback (most recent call last):
File "/data/odoo/odoo-server/odoo/tools/cache.py", line 84, in lookup
r = d[key]
File "/data/odoo/odoo-server/odoo/tools/func.py", line 68, in wrapper
return func(self, *args, **kwargs)
File "/data/odoo/odoo-server/odoo/tools/lru.py", line 44, in getitem
a = self.d[obj].me
KeyError: ('ir.model.data', <function IrModelData.xmlid_lookup at 0x7fe999466488>, 'website_portal.portal_layout')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/data/odoo/odoo-server/odoo/tools/convert.py", line 741, in parse
self._tags[rec.tag](rec, de, mode=mode)
File "/data/odoo/odoo-server/odoo/tools/convert.py", line 719, in _tag_template
return self._tag_record(record, data_node)
File "/data/odoo/odoo-server/odoo/tools/convert.py", line 639, in _tag_record
f_val = self.id_get(f_ref)
File "/data/odoo/odoo-server/odoo/tools/convert.py", line 724, in id_get
res = self.model_id_get(id_str, raise_if_not_found)
File "/data/odoo/odoo-server/odoo/tools/convert.py", line 730, in model_id_get
return self.env['ir.model.data'].xmlid_to_res_model_res_id(id_str, raise_if_not_found=raise_if_not_found)
File "/data/odoo/odoo-server/odoo/addons/base/ir/ir_model.py", line 1316, in xmlid_to_res_model_res_id
return self.xmlid_lookup(xmlid)[1:3]
File "", line 2, in xmlid_lookup
File "/data/odoo/odoo-server/odoo/tools/cache.py", line 89, in lookup
value = d[key] = self.method(*args, **kwargs)
File "/data/odoo/odoo-server/odoo/addons/base/ir/ir_model.py", line 1305, in xmlid_lookup
raise ValueError('External ID not found in the system: %s' % xmlid)
ValueError: External ID not found in the system: website_portal.portal_layout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/data/odoo/odoo-server/odoo/http.py", line 647, in _handle_exception
return super(JsonRequest, self)._handle_exception(exception)
File "/data/odoo/odoo-server/odoo/http.py", line 307, in _handle_exception
raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
File "/data/odoo/odoo-server/odoo/tools/pycompat.py", line 87, in reraise
raise value
File "/data/odoo/odoo-server/odoo/http.py", line 689, in dispatch
result = self._call_function(**self.params)
File "/data/odoo/odoo-server/odoo/http.py", line 339, in _call_function
return checked_call(self.db, *args, **kwargs)
File "/data/odoo/odoo-server/odoo/service/model.py", line 97, in wrapper
return f(dbname, *args, **kwargs)
File "/data/odoo/odoo-server/odoo/http.py", line 332, in checked_call
result = self.endpoint(*a, **kw)
File "/data/odoo/odoo-server/odoo/http.py", line 933, in call
return self.method(*args, **kw)
File "/data/odoo/odoo-server/odoo/http.py", line 512, in response_wrap
response = f(*args, **kw)
File "/data/odoo/odoo-server/addons/web/controllers/main.py", line 934, in call_button
action = self._call_kw(model, method, args, {})
File "/data/odoo/odoo-server/addons/web/controllers/main.py", line 922, in _call_kw
return call_kw(request.env[model], method, args, kwargs)
File "/data/odoo/odoo-server/odoo/api.py", line 689, in call_kw
return call_kw_multi(method, model, args, kwargs)
File "/data/odoo/odoo-server/odoo/api.py", line 680, in call_kw_multi
result = method(recs, *args, **kwargs)
File "", line 2, in button_immediate_install
File "/data/odoo/odoo-server/odoo/addons/base/module/module.py", line 71, in check_and_log
return method(self, *args, **kwargs)
File "/data/odoo/odoo-server/odoo/addons/base/module/module.py", line 448, in button_immediate_install
return self._button_immediate_function(type(self).button_install)
File "/data/odoo/odoo-server/odoo/addons/base/module/module.py", line 541, in _button_immediate_function
modules.registry.Registry.new(self._cr.dbname, update_module=True)
File "/data/odoo/odoo-server/odoo/modules/registry.py", line 85, in new
odoo.modules.load_modules(registry._db, force_demo, status, update_module)
File "/data/odoo/odoo-server/odoo/modules/loading.py", line 343, in load_modules
loaded_modules, update_module)
File "/data/odoo/odoo-server/odoo/modules/loading.py", line 242, in load_marked_modules
loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
File "/data/odoo/odoo-server/odoo/modules/loading.py", line 156, in load_module_graph
_load_data(cr, module_name, idref, mode, kind='data')
File "/data/odoo/odoo-server/odoo/modules/loading.py", line 94, in _load_data
tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
File "/data/odoo/odoo-server/odoo/tools/convert.py", line 788, in convert_file
convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
File "/data/odoo/odoo-server/odoo/tools/convert.py", line 849, in convert_xml_import
obj.parse(doc.getroot(), mode=mode)
File "/data/odoo/odoo-server/odoo/tools/convert.py", line 748, in parse
exc_info[2]
File "/data/odoo/odoo-server/odoo/tools/pycompat.py", line 86, in reraise
raise value.with_traceback(tb)
File "/data/odoo/odoo-server/odoo/tools/convert.py", line 741, in parse
self._tags[rec.tag](rec, de, mode=mode)
File "/data/odoo/odoo-server/odoo/tools/convert.py", line 719, in _tag_template
return self._tag_record(record, data_node)
File "/data/odoo/odoo-server/odoo/tools/convert.py", line 639, in _tag_record
f_val = self.id_get(f_ref)
File "/data/odoo/odoo-server/odoo/tools/convert.py", line 724, in id_get
res = self.model_id_get(id_str, raise_if_not_found)
File "/data/odoo/odoo-server/odoo/tools/convert.py", line 730, in model_id_get
return self.env['ir.model.data'].xmlid_to_res_model_res_id(id_str, raise_if_not_found=raise_if_not_found)
File "/data/odoo/odoo-server/odoo/addons/base/ir/ir_model.py", line 1316, in xmlid_to_res_model_res_id
return self.xmlid_lookup(xmlid)[1:3]
File "", line 2, in xmlid_lookup
File "/data/odoo/odoo-server/odoo/tools/cache.py", line 89, in lookup
value = d[key] = self.method(*args, **kwargs)
File "/data/odoo/odoo-server/odoo/addons/base/ir/ir_model.py", line 1305, in xmlid_lookup
raise ValueError('External ID not found in the system: %s' % xmlid)
odoo.tools.convert.ParseError: "External ID not found in the system: website_portal.portal_layout" while parsing None:65, near




`

who can help me.

**Comment by keecome** [comment]
What modules do I need to install to solve this problem?

@W360S

Thanks & Best Regards

**Comment by 360org** [comment]
check it here: #711

**Comment by 360org** [comment]
and here: #740

**Comment by keecome** [comment]
Thank you very much!

The install problem I Solved it.

but I got a new problem:

when odoo service reboot running,the log:

`Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python3.5/dist-packages/werkzeug/serving.py", line 258, in execute
    application_iter = app(environ, start_response)
  File "/data/odoo/odoo-server/odoo/service/server.py", line 252, in app
    return self.app(e, s)
  File "/data/odoo/odoo-server/odoo/service/wsgi_server.py", line 166, in application
    return application_unproxied(environ, start_response)
  File "/data/odoo/odoo-server/odoo/service/wsgi_server.py", line 154, in application_unproxied
    result = handler(environ, start_response)
  File "/data/odoo/odoo-server/odoo/http.py", line 1303, in __call__
    self.load_addons()
  File "/data/odoo/odoo-server/odoo/http.py", line 1325, in load_addons
    m = __import__('odoo.addons.' + module)
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load

  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked

  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked

  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible

  File "/data/odoo/odoo-server/odoo/modules/module.py", line 82, in load_module
    exec(open(modfile, 'rb').read(), new_mod.__dict__)
  File "<string>", line 3, in <module>

  File "/data/odoo/custom/it-projects-llc/odoo-saas-tools/saas_portal/models/__init__.py", line 4, in <module>
    from . import ir_config_parameter
File "/data/odoo/custom/it-projects-llc/odoo-saas-tools/saas_portal/models/ir_config_parameter.py", line 15
    self.set_param(BASE_SAAS_DOMAIN, domain_only)`

@W360S @yelizariev

**Comment by njeudy** [comment]
@keecome can you test with latest commit ?

**Comment by jeffery9** [comment]
I have fixed this.  should PR soon.
