### ISSUE TITLE
odoo.exceptions.AccessDenied: Access denied

### ISSUE THREAD

**Issue by 360org** [it-projects-llc/odoo-saas-tools#749]
Hello @njeudy today i meet  new error it, i dont know where is it come from but like something new come when i try to update something new
Traceback (most recent call last):
  File "/home/odoo-saas-tools/saas_server/controllers/main.py", line 23, in wrap
    return f(*args, **kw)
  File "/home/odoo-saas-tools/saas_server/controllers/main.py", line 189, in delete_database
    client.delete_database()
  File "<decorator-gen-356>", line 2, in delete_database
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 369, in loop
    result = [method(rec, *args, **kwargs) for rec in self]
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 369, in <listcomp>
    result = [method(rec, *args, **kwargs) for rec in self]
  File "/home/odoo-saas-tools/saas_server/models/saas_server.py", line 363, in delete_database
    odoo.service.db.exp_drop(self.name)
  File "<decorator-gen-5>", line 2, in exp_drop
  File "/usr/lib/python3/dist-packages/odoo/service/db.py", line 39, in if_db_mgt_enabled
    raise AccessDenied()
odoo.exceptions.AccessDenied: Access denied

**Comment by 360org** [comment]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 647, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 307, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 689, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 339, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 332, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 512, in response_wrap
    response = f(*args, **kw)
  File "/home/en-addons/addons/web/controllers/main.py", line 924, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/en-addons/addons/web/controllers/main.py", line 916, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/odoo-saas-tools/saas_portal/models/saas_portal.py", line 679, in write
    record.upgrade(payload)
  File "/home/odoo-saas-tools/saas_portal/models/saas_portal.py", line 551, in upgrade
    res.append(config_obj.do_upgrade_database(payload.copy(), database_obj))
  File "/home/odoo-saas-tools/saas_portal/wizard/config_wizard.py", line 86, in do_upgrade_database
    raise Warning('Reason: %s \n Message: %s' % (res.reason, res.content))
Warning: Reason: INTERNAL SERVER ERROR 
 Message: b'FATAL:  database "liongroup.vn" does not exist\n'
i try to delete db create no success it show what message

**Comment by 360org** [comment]
update error
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 647, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 307, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 689, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 339, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 332, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 512, in response_wrap
    response = f(*args, **kw)
  File "/home/en-addons/addons/web/controllers/main.py", line 928, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/en-addons/addons/web/controllers/main.py", line 916, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/odoo-saas-tools/saas_portal/models/saas_portal.py", line 447, in action_sync_server
    r.server_id.action_sync_server()
  File "/home/odoo-saas-tools/saas_portal/models/saas_portal.py", line 151, in action_sync_server
    (res.reason, res.content))
Warning: Reason: INTERNAL SERVER ERROR 
 Message: b'Expected singleton: saas_server.client(1, 2, 3, 4, 5, 6, 7, 8, 9, 11, 12, 13, 14, 15, 16, 17)'

**Comment by 360org** [comment]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 647, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 307, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 689, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 339, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 332, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 512, in response_wrap
    response = f(*args, **kw)
  File "/home/en-addons/addons/web/controllers/main.py", line 928, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/en-addons/addons/web/controllers/main.py", line 916, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/odoo-saas-tools/saas_portal/models/saas_portal.py", line 795, in sync_client
    self.server_id.action_sync_server(updating_client_ID=self.client_id)
  File "/home/odoo-saas-tools/saas_portal/models/saas_portal.py", line 151, in action_sync_server
    (res.reason, res.content))
Warning: Reason: INTERNAL SERVER ERROR 
 Message: b'0'

**Comment by 360org** [comment]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 647, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 307, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 689, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 339, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 332, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 512, in response_wrap
    response = f(*args, **kw)
  File "/home/en-addons/addons/web/controllers/main.py", line 928, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/en-addons/addons/web/controllers/main.py", line 916, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/odoo-saas-tools/saas_portal/wizard/config_wizard.py", line 178, in apply
    trial=self.trial)
  File "/home/odoo-saas-tools/saas_portal/models/saas_portal.py", line 286, in create_new_database
    return self._create_new_database(**kwargs)
  File "/home/odoo-saas-tools/saas_portal/models/saas_portal.py", line 369, in _create_new_database
    req.url, res.reason, res.content))
Warning: Error on request: http://clients.wcloud.vn:80/saas_server/new_database
Reason: INTERNAL SERVER ERROR 
 Message: b'Access denied'

**Comment by njeudy** [comment]
@W360S ok I think you use my current WIP branch ?

I will install from scratch and setup en new saas env to test, thanks for the report (will try to add test for this too)

**Comment by 360org** [comment]
I need to help to solved this problems.
I think the probem comewhen i try to make new plan and it happen.

**Comment by 360org** [comment]
Hello @njeudy do you have telegram? 
https://t.me/joinchat/EdoTHBCuElRZjrwvbDpAzQ
Plz join this group i may need your instant help

**Comment by njeudy** [comment]
Ok I reproduce it, will correct in #746

**Comment by 360org** [comment]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/requests/packages/urllib3/connection.py", line 142, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/local/lib/python3.6/dist-packages/requests/packages/urllib3/util/connection.py", line 98, in create_connection
    raise err
  File "/usr/local/lib/python3.6/dist-packages/requests/packages/urllib3/util/connection.py", line 88, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/requests/packages/urllib3/connectionpool.py", line 595, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.6/dist-packages/requests/packages/urllib3/connectionpool.py", line 363, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/usr/local/lib/python3.6/dist-packages/requests/packages/urllib3/connection.py", line 167, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.6/dist-packages/requests/packages/urllib3/connection.py", line 151, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
requests.packages.urllib3.exceptions.NewConnectionError: <requests.packages.urllib3.connection.HTTPConnection object at 0x7f6640e7ccc0>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/usr/local/lib/python3.6/dist-packages/requests/packages/urllib3/connectionpool.py", line 640, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.6/dist-packages/requests/packages/urllib3/util/retry.py", line 287, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
requests.packages.urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='clients.wcloud.vn', port=80): Max retries exceeded with url: /saas_server/new_database (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f6640e7ccc0>: Failed to establish a new connection: [Errno 111] Connection refused',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 647, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 307, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 689, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 339, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 332, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 512, in response_wrap
    response = f(*args, **kw)
  File "/home/en-addons/addons/web/controllers/main.py", line 928, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/en-addons/addons/web/controllers/main.py", line 916, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/odoo-saas-tools/saas_portal/wizard/config_wizard.py", line 178, in apply
    trial=self.trial)
  File "/home/odoo-saas-tools/saas_portal/models/saas_portal.py", line 286, in create_new_database
    return self._create_new_database(**kwargs)
  File "/home/odoo-saas-tools/saas_portal/models/saas_portal.py", line 366, in _create_new_database
    res = requests.Session().send(req, **req_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/requests/sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/requests/adapters.py", line 487, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='clients.wcloud.vn', port=80): Max retries exceeded with url: /saas_server/new_database (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f6640e7ccc0>: Failed to establish a new connection: [Errno 111] Connection refused',))

**Comment by 360org** [comment]
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 647, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 307, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 689, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 339, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 332, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 512, in response_wrap
    response = f(*args, **kw)
  File "/home/en-addons/addons/web/controllers/main.py", line 928, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/en-addons/addons/web/controllers/main.py", line 916, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/odoo-saas-tools/saas_portal/models/saas_portal.py", line 447, in action_sync_server
    r.server_id.action_sync_server()
  File "/home/odoo-saas-tools/saas_portal/models/saas_portal.py", line 151, in action_sync_server
    (res.reason, res.content))
Warning: Reason: INTERNAL SERVER ERROR 
 Message: b'Expected singleton: saas_server.client(1, 2, 3, 4, 5, 6, 7, 8, 9, 11, 12, 13, 14, 15, 16, 17, 18)'

**Comment by 360org** [comment]
File "/home/odoo-saas-tools/saas_server/controllers/main.py", line 21, in wrap
    return f(*args, **kw)
  File "/home/odoo-saas-tools/saas_server/controllers/main.py", line 68, in new_database
    res = client.create_database(template_db, demo, lang)
  File "/home/odoo-saas-tools/saas_server/models/saas_server.py", line 49, in create_database
    db.exp_duplicate_database(template_db, new_db)
  File "<decorator-gen-4>", line 2, in exp_duplicate_database
  File "/usr/lib/python3/dist-packages/odoo/service/db.py", line 39, in if_db_mgt_enabled
    raise AccessDenied()
odoo.exceptions.AccessDenied: Access denied

**Comment by njeudy** [comment]
@W360: connection refused is not from code but network setup i think.

Will try to reproduce duplicate database :)

**Comment by njeudy** [comment]
@W360S can not have Access denied error, can you help me to reproduce ?

**Comment by njeudy** [comment]
With latest code it is ok.

IMPORTANT: in saas_server you should not disable db_list because it prevent for database creating / renaming

see odoo code:

```
def check_db_management_enabled(method):
    def if_db_mgt_enabled(method, self, *args, **kwargs):
        if not odoo.tools.config['list_db']:
            _logger.error('Database management functions blocked, admin disabled database listing')
            raise AccessDenied()
        return method(self, *args, **kwargs)
    return decorator(if_db_mgt_enabled, method)
```

**Comment by njeudy** [comment]
So close :)

**Comment by 360org** [comment]
Here are steps to solved problems.
if you in single VPS list_db = False must be => list_db = True
if you in separate VPS the clients DB must be enabled  list_db = False must be => list_db = True
normal config url: vim /etc/odoo/odoo.conf
