### ISSUE TITLE
saas server erreur

### ISSUE THREAD

**Issue by ikrape** [it-projects-llc/odoo-saas-tools#755]
Traceback (most recent call last):
  File "/home/ikram/odoo/odoo-10/odoo/http.py", line 641, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/ikram/odoo/odoo-10/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/home/ikram/odoo/odoo-10/odoo/http.py", line 333, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/ikram/odoo/odoo-10/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/ikram/odoo/odoo-10/odoo/http.py", line 326, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/ikram/odoo/odoo-10/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/home/ikram/odoo/odoo-10/odoo/http.py", line 506, in response_wrap
    response = f(*args, **kw)
  File "/home/ikram/odoo/odoo-10/odoo/addons/web/controllers/main.py", line 894, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/ikram/odoo/odoo-10/odoo/addons/web/controllers/main.py", line 882, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/ikram/odoo/odoo-10/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/home/ikram/odoo/odoo-10/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/ikram/odoo/custom/saas10/saas_portal/models/saas_portal.py", line 357, in create_template_button
    res = self.create_template()
  File "/home/ikram/odoo/custom/saas10/saas_portal/models/saas_portal.py", line 378, in create_template
    raise Warning('Error on request: %s\nReason: %s \n Message: %s' % (req.url, res.reason, res.content))
Warning: Error on request: http://s1.odoo.local:80/saas_server/new_database
Reason: Bad Gateway 
 Message: <html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.10.3 (Ubuntu)</center>
</body>

**Comment by njeudy** [comment]
hello @ikrape think your saas_portal server don't see saas_server instance (s1.odoo.local) can you check this ?

**Comment by ikrape** [comment]
think for your response @njeudy  but i don't understand you 
https://drive.google.com/file/d/1emU3yveYobvo9uiyAqKOXaolJPYiI2_i/view?usp=sharing
https://drive.google.com/file/d/1U5_tf08DtZ74goYww_F5W-JfwnSR21lw/view?usp=sharing

**Comment by njeudy** [comment]
@ikrape ok your principal server (where you install saas_portal) can not resolv s1.odoo.local.

to check you have to log in your principal server (with ssh) and try to ping s1.odoo.local .. think it will failed .. If it ping try to curl / wget http://s1.odoo.local:80/saas_server/new_database url and see result ..

That is a network problem I think not a code problem ..

**Comment by ikrape** [comment]
thank you @njeudy i have resolved y prblm i had an erreur with the port of the ngnix

**Comment by njeudy** [comment]
no problem, be free to open new issue if you need :)
