### ISSUE TITLE
SSLError: ("bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')],)",)

### ISSUE THREAD

**Issue by msdeek** [it-projects-llc/odoo-saas-tools#788]
Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/http.py", line 642, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo/odoo-server/odoo/http.py", line 684, in dispatch
    result = self._call_function(**self.params)
  File "/odoo/odoo-server/odoo/http.py", line 334, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo/odoo-server/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo/odoo-server/odoo/http.py", line 327, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 942, in __call__
    return self.method(*args, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 507, in response_wrap
    response = f(*args, **kw)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 896, in call_button
    action = self._call_kw(model, method, args, {})
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 884, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-252>", line 2, in action_sync_server
  File "/odoo/odoo-server/odoo/api.py", line 369, in loop
    result = [method(rec, *args, **kwargs) for rec in self]
  File "/odoo/custom/addons/saas_portal/models/saas_portal.py", line 133, in action_sync_server
    res = requests.Session().send(req, **req_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 524, in send
    raise SSLError(e, request=request)
SSLError: ("bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')],)",)

**Comment by Danizan1976** [comment]
Hi,
It seems that the saas setup doesn't suppport SSL via port 443. It works fine if nginx is only configured for port 80, but with addition of listen port 443 (using comodo postiveSSL), i can't sync from portal to server.

Error Log :
Warning: Reason: INTERNAL SERVER ERROR 
 Message: b"HTTPSConnectionPool(host='portal.xxx.com', port=443): Max retries exceeded with url: /oauth2/tokeninfo?access_token=NdfzaUj8TG4bJG37rorGbQI2Vx5W7d (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:720)'),))"

@msdeek , did you manage to solve this?

**Comment by vish-star** [comment]
any one solve
