### ISSUE TITLE
 Message: Expected singleton: saas_server.client()

### ISSUE THREAD

**Issue by msdeek** [it-projects-llc/odoo-saas-tools#789]
Odoo v 10.0

Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/http.py", line 642, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo/odoo-server/odoo/http.py", line 684, in dispatch
    result = self._call_function(**self.params)
  File "/odoo/odoo-server/odoo/http.py", line 334, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo/odoo-server/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo/odoo-server/odoo/http.py", line 327, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 942, in __call__
    return self.method(*args, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 507, in response_wrap
    response = f(*args, **kw)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 896, in call_button
    action = self._call_kw(model, method, args, {})
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 884, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-252>", line 2, in action_sync_server
  File "/odoo/odoo-server/odoo/api.py", line 369, in loop
    result = [method(rec, *args, **kwargs) for rec in self]
  File "/odoo/custom/addons/saas_portal/models/saas_portal.py", line 136, in action_sync_server
    raise Warning('Reason: %s \n Message: %s' % (res.reason, res.content))
Warning: Reason: INTERNAL SERVER ERROR 
 Message: Expected singleton: saas_server.client()

**Comment by YogendrasinhChavda** [comment]
Hello @msetiha ,
Good Morning!
The issue is fixed. Please take the latest pull of 11.0 and check it.
Thanks

**Comment by usmanfarzandali** [comment]
@YogendrasinhChavda not fixed in odoo 10 c?

**Comment by maherkhalil07** [comment]
Hi friends
I need someone to install odoo with saas tools in my private server
if interested send me e mail (maherkhalil@outlook.com)
Regards;

**Comment by ghost** [comment]
Hello Friends, 
**Case:1** 
I'm facing My portal database on Odoo 11 and my server database on Odoo 10. When I create a server in the main database(portal database) and sync server than it returns an error to me below :
**Warning: Reason: INTERNAL SERVER ERROR
Message: Expected singleton: saas_server.client()**
but when I'm sync from the plan it's not through any error. so how can I fix server in the main database(portal database) sync server?

**Case:2**
Both database (portal and server) on Odoo 11 than it's not a through any error.
