### ISSUE TITLE
V11: Database Backup using cron job Issue.

### ISSUE THREAD

**Issue by YogendrasinhChavda** [it-projects-llc/odoo-saas-tools#791]
Hello,
Good Afternoon!

When I am trying to take the databack backup of the instances from the server database it gives traceback and database backup is interrupted.
First of all, I installed module "**saas_server_backup_ftp**" in the **server database** and configured database backup related configuration from the menu: Settings => General Settings in my local system.
When I am trying to run Cronjob ( Backup SaaS Databases Scheduler ) to take the database backup It gives the traceback.

I already installed lib. in my local system:

sudo pip3 install wdb
sudo pip3 install wdb.server

Below is the traceback logs : 

2018-08-07 09:05:24,305 7576 INFO ? paramiko.transport: Connected (version 2.0, client OpenSSH_7.2p2)
2018-08-07 09:05:24,551 7576 INFO ? paramiko.transport: Authentication (password) successful!
2018-08-07 09:05:24,694 wdb You must start/install wdb.server (Retrying on localhost:19840) [Try # 1/10] at connect:228
2018-08-07 09:05:24,918 wdb You must start/install wdb.server (Retrying on localhost:19840) [Try # 2/10] at connect:228
2018-08-07 09:05:25,405 wdb You must start/install wdb.server (Retrying on localhost:19840) [Try # 3/10] at connect:228
2018-08-07 09:05:26,179 wdb You must start/install wdb.server (Retrying on localhost:19840) [Try # 4/10] at connect:228
2018-08-07 09:05:27,062 wdb You must start/install wdb.server (Retrying on localhost:19840) [Try # 5/10] at connect:228
2018-08-07 09:05:28,096 wdb You must start/install wdb.server (Retrying on localhost:19840) [Try # 6/10] at connect:228
2018-08-07 09:05:29,363 wdb You must start/install wdb.server (Retrying on localhost:19840) [Try # 7/10] at connect:228
2018-08-07 09:05:30,945 wdb You must start/install wdb.server (Retrying on localhost:19840) [Try # 8/10] at connect:228
2018-08-07 09:05:33,162 wdb You must start/install wdb.server (Retrying on localhost:19840) [Try # 9/10] at connect:228
2018-08-07 09:05:35,032 wdb You must start/install wdb.server (Retrying on localhost:19840) [Try # 10/10] at connect:228
2018-08-07 09:05:35,221 wdb Could not connect to server at connect:233
2018-08-07 09:05:35,221 wdb No connection at send:754
2018-08-07 09:05:35,229 wdb No connection at receive:762
2018-08-07 09:05:35,229 7576 ERROR s1.test.com odoo.addons.saas_server.models.saas_server: An error happened during database mmb.main.template.test.com backup
Traceback (most recent call last):
  File "/home/saas_v11_tools_latest/odoo-saas-tools/saas_server/models/saas_server.py", line 456, in backup_database
    database_obj._transport_backup(dump_db, filename=filename)
  File "/home/saas_v11_tools_latest/odoo-saas-tools/saas_server_backup_ftp/models/saas_server.py", line 52, in _transport_backup
    import wdb; wdb.set_trace()
  File "/usr/local/lib/python3.5/dist-packages/wdb/__init__.py", line 994, in set_trace
    wdb = Wdb.get(server=server, port=port)
  File "/usr/local/lib/python3.5/dist-packages/wdb/__init__.py", line 103, in get
    Wdb.__init__(wdb, server, port, force_uuid)
  File "/usr/local/lib/python3.5/dist-packages/wdb/__init__.py", line 150, in __init__
    self.get_breakpoints()
  File "/usr/local/lib/python3.5/dist-packages/wdb/__init__.py", line 243, in get_breakpoints
    breaks = loads(breaks)
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'NoneType'

We fixed it temporarily by the comment the one line in  "saas_server_backup_ftp" module.
File : models => saas_server.py
method: def _transport_backup(self, dump_db, filename=None):
line number : 52
Comment line : import wdb; wdb.set_trace()

Can anyone help me how can I resolve this issue permanently?

Thanks in advance.

**Comment by yelizariev** [comment]
Hi, I've just fixed it here https://github.com/it-projects-llc/odoo-saas-tools/commit/aa8a5f9406382b2a702e97812a66bc812758e1f5

**Comment by YogendrasinhChavda** [comment]
Hello @yelizariev,
Thank you. :+1:
