### ISSUE TITLE
Got Error when i install saas

### ISSUE THREAD

**Issue by elliotxin** [it-projects-llc/odoo-saas-tools#823]
I enter on command in the shell as:
`sudo su --preserve-environment - odoo -s /bin/bash -c 'python /usr/local/src/odoo-extra-addons/it-projects-llc/odoo-saas-tools/saas.py`
some error appear:

```
-su: /root/.bash_profile: Permission denied
2018-12-21 18:24:56
saas.py >>> Waiting for port, 127.0.0.1, 8069
2018-12-21 18:24:59
saas.py >>> Spawn, ./odoo-server --xmlrpc-port=8069 --longpolling-port=8072 --database= --db-filter=%h --workers=3 --db_user=odoo --db_password=odoo --db_port=5432 --max-cron-threads=0
2018-12-21 18:24:59
saas.py >>> Spawn pid: 1579
2018-12-21 18:24:59
saas.py >>> Waiting for port, 127.0.0.1, 8069
Traceback (most recent call last):
  File "/usr/local/src/odoo-extra-addons/it-projects-llc/odoo-saas-tools/saas.py", line 662, in <module>
    main()
  File "/usr/local/src/odoo-extra-addons/it-projects-llc/odoo-saas-tools/saas.py", line 183, in main
    pid = spawn_cmd(cmd)
  File "/usr/local/src/odoo-extra-addons/it-projects-llc/odoo-saas-tools/saas.py", line 602, in spawn_cmd
    shell=shell)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1334, in _execute_child
    os.close(errpipe_read)
OSError: [Errno 9] Bad file descriptor

2018-12-21 18:25:29
saas.py >>> KILL, 1579
```
So anyone can tell me how to install the saas-tool after install odoo?

**Comment by elliotxin** [comment]
@yelizariev, please help assist me to fix this, thanks a lot.
@njeudy,please help assist me to fix this, thanks a lot. 
@iledarn ,please help assist me to fix this, thanks a lot.
