### ISSUE TITLE
Cannot install saas_portal module odoo 12

### ISSUE THREAD

**Issue by therealmjk** [it-projects-llc/odoo-saas-tools#830]
Help

I am trying to install the saas_portal module but i keep having this error

> 
Error:
Odoo Server Error

Traceback (most recent call last):
  File "C:\Odoo 12.0\server\odoo\tools\cache.py", line 88, in lookup
    r = d[key]
  File "C:\Odoo 12.0\server\odoo\tools\func.py", line 69, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Odoo 12.0\server\odoo\tools\lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: ('ir.model.data', <function IrModelData.xmlid_lookup at 0x042058A0>, 'saas_portal.model_saas_portal_client')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Odoo 12.0\server\odoo\tools\convert.py", line 757, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "C:\Odoo 12.0\server\odoo\tools\convert.py", line 649, in _tag_record
    f_val = self.id_get(f_ref)
  File "C:\Odoo 12.0\server\odoo\tools\convert.py", line 740, in id_get
    res = self.model_id_get(id_str, raise_if_not_found)
  File "C:\Odoo 12.0\server\odoo\tools\convert.py", line 746, in model_id_get
    return self.env['ir.model.data'].xmlid_to_res_model_res_id(id_str, raise_if_not_found=raise_if_not_found)
  File "c:\odoo 12.0\server\odoo\addons\base\models\ir_model.py", line 1380, in xmlid_to_res_model_res_id
    return self.xmlid_lookup(xmlid)[1:3]
  File "<decorator-gen-25>", line 2, in xmlid_lookup
  File "C:\Odoo 12.0\server\odoo\tools\cache.py", line 93, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "c:\odoo 12.0\server\odoo\addons\base\models\ir_model.py", line 1369, in xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % xmlid)
ValueError: External ID not found in the system: saas_portal.model_saas_portal_client

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Odoo 12.0\server\odoo\http.py", line 654, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "C:\Odoo 12.0\server\odoo\http.py", line 312, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "C:\Odoo 12.0\server\odoo\tools\pycompat.py", line 87, in reraise
    raise value
  File "C:\Odoo 12.0\server\odoo\http.py", line 696, in dispatch
    result = self._call_function(**self.params)
  File "C:\Odoo 12.0\server\odoo\http.py", line 344, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "C:\Odoo 12.0\server\odoo\service\model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "C:\Odoo 12.0\server\odoo\http.py", line 337, in checked_call
    result = self.endpoint(*a, **kw)
  File "C:\Odoo 12.0\server\odoo\http.py", line 939, in __call__
    return self.method(*args, **kw)
  File "C:\Odoo 12.0\server\odoo\http.py", line 517, in response_wrap
    response = f(*args, **kw)
  File "c:\odoo 12.0\server\odoo\addons\web\controllers\main.py", line 966, in call_button
    action = self._call_kw(model, method, args, {})
  File "c:\odoo 12.0\server\odoo\addons\web\controllers\main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "C:\Odoo 12.0\server\odoo\api.py", line 749, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "C:\Odoo 12.0\server\odoo\api.py", line 736, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-61>", line 2, in button_immediate_install
  File "c:\odoo 12.0\server\odoo\addons\base\models\ir_module.py", line 73, in check_and_log
    return method(self, *args, **kwargs)
  File "c:\odoo 12.0\server\odoo\addons\base\models\ir_module.py", line 444, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "c:\odoo 12.0\server\odoo\addons\base\models\ir_module.py", line 552, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "C:\Odoo 12.0\server\odoo\modules\registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "C:\Odoo 12.0\server\odoo\modules\loading.py", line 421, in load_modules
    loaded_modules, update_module, models_to_check)
  File "C:\Odoo 12.0\server\odoo\modules\loading.py", line 313, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "C:\Odoo 12.0\server\odoo\modules\loading.py", line 222, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package, report=report)
  File "C:\Odoo 12.0\server\odoo\modules\loading.py", line 68, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind, report)
  File "C:\Odoo 12.0\server\odoo\tools\convert.py", line 801, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "C:\Odoo 12.0\server\odoo\tools\convert.py", line 864, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "C:\Odoo 12.0\server\odoo\tools\convert.py", line 754, in parse
    self.parse(rec, mode)
  File "C:\Odoo 12.0\server\odoo\tools\convert.py", line 763, in parse
    exc_info[2]
  File "C:\Odoo 12.0\server\odoo\tools\pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "C:\Odoo 12.0\server\odoo\tools\convert.py", line 757, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "C:\Odoo 12.0\server\odoo\tools\convert.py", line 649, in _tag_record
    f_val = self.id_get(f_ref)
  File "C:\Odoo 12.0\server\odoo\tools\convert.py", line 740, in id_get
    res = self.model_id_get(id_str, raise_if_not_found)
  File "C:\Odoo 12.0\server\odoo\tools\convert.py", line 746, in model_id_get
    return self.env['ir.model.data'].xmlid_to_res_model_res_id(id_str, raise_if_not_found=raise_if_not_found)
  File "c:\odoo 12.0\server\odoo\addons\base\models\ir_model.py", line 1380, in xmlid_to_res_model_res_id
    return self.xmlid_lookup(xmlid)[1:3]
  File "<decorator-gen-25>", line 2, in xmlid_lookup
  File "C:\Odoo 12.0\server\odoo\tools\cache.py", line 93, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "c:\odoo 12.0\server\odoo\addons\base\models\ir_model.py", line 1369, in xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % xmlid)
odoo.tools.convert.ParseError: "External ID not found in the system: saas_portal.model_saas_portal_client" while parsing file:/c:/odoo%2012.0/custom/odoo-saas-tools/saas_portal/data/mail_template_data.xml:3, near
<record id="email_template_create_saas" model="mail.template">
            <field name="name">Send SaaS credentials to the buyer of the SaaS</field>
            <field name="email_from">${(object.user_id.email or '')|safe}</field>
            <field name="subject">Credentials:</field>
            <field name="partner_to">${object.partner_id.id}</field>
            <field name="model_id" ref="saas_portal.model_saas_portal_client"/>
            <field name="auto_delete" eval="True"/>
            <field name="lang">${object.partner_id.lang}</field>
            <field name="body_html">

            &lt;p&gt;Web:
            &lt;a href="${object.public_url}"&gt;${object.public_url}&lt;/a&gt;
            &lt;/p&gt;

            </field>
        </record>
>

**Comment by ilmir-k** [comment]
@therealmjk 
The odoo saas tools has not been migrated to v12 yet.
You can try the version from PR #822

**Comment by therealmjk** [comment]
@ilmir-k Thanks much
