### ISSUE TITLE
Error when creating a Client from a Plan

### ISSUE THREAD

**Issue by therealmjk** [it-projects-llc/odoo-saas-tools#832]
When i try to create a client from a plan i have the following error. Please help
P.S i am using simplejson-3.16 and odoo-12

Error:
Odoo Server Error

Traceback (most recent call last):
  File "C:\Odoo 12.0\server\odoo\http.py", line 654, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "C:\Odoo 12.0\server\odoo\http.py", line 312, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "C:\Odoo 12.0\server\odoo\tools\pycompat.py", line 87, in reraise
    raise value
  File "C:\Odoo 12.0\server\odoo\http.py", line 696, in dispatch
    result = self._call_function(**self.params)
  File "C:\Odoo 12.0\server\odoo\http.py", line 344, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "C:\Odoo 12.0\server\odoo\service\model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "C:\Odoo 12.0\server\odoo\http.py", line 337, in checked_call
    result = self.endpoint(*a, **kw)
  File "C:\Odoo 12.0\server\odoo\http.py", line 939, in __call__
    return self.method(*args, **kw)
  File "C:\Odoo 12.0\server\odoo\http.py", line 517, in response_wrap
    response = f(*args, **kw)
  File "c:\odoo 12.0\server\odoo\addons\web\controllers\main.py", line 966, in call_button
    action = self._call_kw(model, method, args, {})
  File "c:\odoo 12.0\server\odoo\addons\web\controllers\main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "C:\Odoo 12.0\server\odoo\api.py", line 749, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "C:\Odoo 12.0\server\odoo\api.py", line 736, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "c:\odoo 12.0\custom\odoo-saas-tools\saas_portal\wizard\config_wizard.py", line 177, in apply
    trial=self.trial)
  File "c:\odoo 12.0\custom\odoo-saas-tools\saas_portal\models\saas_portal.py", line 286, in create_new_database
    return self._create_new_database(**kwargs)
  File "c:\odoo 12.0\custom\odoo-saas-tools\saas_portal\models\saas_portal.py", line 387, in _create_new_database
    client.send_params_to_client_db()
  File "c:\odoo 12.0\custom\odoo-saas-tools\saas_portal\models\saas_portal.py", line 892, in send_params_to_client_db
    self.env['saas.config'].do_upgrade_database(payload, record)
  File "c:\odoo 12.0\custom\odoo-saas-tools\saas_portal\wizard\config_wizard.py", line 87, in do_upgrade_database
    state=state,
  File "c:\odoo 12.0\custom\odoo-saas-tools\saas_portal\models\saas_portal.py", line 104, in _request_server
    params = self._request_params(**kwargs)
  File "c:\odoo 12.0\custom\odoo-saas-tools\saas_portal\models\saas_portal.py", line 84, in _request_params
    'state': simplejson.dumps(state),
  File "C:\Odoo 12.0\python\lib\site-packages\simplejson\__init__.py", line 382, in dumps
    return _default_encoder.encode(obj)
  File "C:\Odoo 12.0\python\lib\site-packages\simplejson\encoder.py", line 298, in encode
    chunks = list(chunks)
  File "C:\Odoo 12.0\python\lib\site-packages\simplejson\encoder.py", line 696, in _iterencode
    for chunk in _iterencode_dict(o, _current_indent_level):
  File "C:\Odoo 12.0\python\lib\site-packages\simplejson\encoder.py", line 652, in _iterencode_dict
    for chunk in chunks:
  File "C:\Odoo 12.0\python\lib\site-packages\simplejson\encoder.py", line 652, in _iterencode_dict
    for chunk in chunks:
  File "C:\Odoo 12.0\python\lib\site-packages\simplejson\encoder.py", line 531, in _iterencode_list
    for chunk in chunks:
  File "C:\Odoo 12.0\python\lib\site-packages\simplejson\encoder.py", line 652, in _iterencode_dict
    for chunk in chunks:
  File "C:\Odoo 12.0\python\lib\site-packages\simplejson\encoder.py", line 716, in _iterencode
    o = _default(o)
  File "C:\Odoo 12.0\python\lib\site-packages\simplejson\encoder.py", line 273, in default
    o.__class__.__name__)
TypeError: Object of type datetime is not JSON serializable

**Comment by ilmir-k** [comment]
@therealmjk the errors appear because odoo saas has not been migrated to v12 yet

**Comment by gridworkz** [comment]
I've got a core set of working v12 modules here if that helps: https://github.com/gridworkz/odoo-saas-tools/tree/12.0

**Comment by therealmjk** [comment]
@gridworkz i tried yours but i have error when trying to install saas_portal

`
Error:
System Server Error

Traceback (most recent call last):
  File "C:\Users\Muhd Jibril Kazim\Documents\_LTG\odoo_www\odoo\odoo\tools\cache.py", line 88, in lookup
    r = d[key]
  File "C:\Users\Muhd Jibril Kazim\Documents\_LTG\odoo_www\odoo\odoo\tools\func.py", line 69, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\Muhd Jibril Kazim\Documents\_LTG\odoo_www\odoo\odoo\tools\lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: ('ir.model.data', <function IrModelData.xmlid_lookup at 0x00000226BDF529D8>, 'saas_portal.model_saas_portal_client')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Muhd Jibril Kazim\Documents\_LTG\odoo_www\odoo\odoo\tools\convert.py", line 757, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "C:\Users\Muhd Jibril Kazim\Documents\_LTG\odoo_www\odoo\odoo\tools\convert.py", line 649, in _tag_record
    f_val = self.id_get(f_ref)
  File "C:\Users\Muhd Jibril Kazim\Documents\_LTG\odoo_www\odoo\odoo\tools\convert.py", line 740, in id_get
    res = self.model_id_get(id_str, raise_if_not_found)
  File "C:\Users\Muhd Jibril Kazim\Documents\_LTG\odoo_www\odoo\odoo\tools\convert.py", line 746, in model_id_get
    return self.env['ir.model.data'].xmlid_to_res_model_res_id(id_str, raise_if_not_found=raise_if_not_found)
  File "c:\users\muhd jibril kazim\documents\_ltg\odoo_www\odoo\odoo\addons\base\models\ir_model.py", line 1391, in xmlid_to_res_model_res_id
    return self.xmlid_lookup(xmlid)[1:3]
  File "<decorator-gen-25>", line 2, in xmlid_lookup
  File "C:\Users\Muhd Jibril Kazim\Documents\_LTG\odoo_www\odoo\odoo\tools\cache.py", line 93, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "c:\users\muhd jibril kazim\documents\_ltg\odoo_www\odoo\odoo\addons\base\models\ir_model.py", line 1380, in xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % xmlid)
ValueError: External ID not found in the system: saas_portal.model_saas_portal_client

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Muhd Jibril Kazim\Documents\_LTG\odoo_www\odoo\odoo\http.py", line 654, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "C:\Users\Muhd Jibril Kazim\Documents\_LTG\odoo_www\odoo\odoo\http.py", line 312, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "C:\Users\Muhd Jibril Kazim\Documents\_LTG\odoo_www\odoo\odoo\tools\pycompat.py", line 87, in reraise
    raise value
  File "C:\Users\Muhd Jibril Kazim\Documents\_LTG\odoo_www\odoo\odoo\http.py", line 696, in dispatch
    result = self._call_function(**self.params)
  File "C:\Users\Muhd Jibril Kazim\Documents\_LTG\odoo_www\odoo\odoo\http.py", line 344, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "C:\Users\Muhd Jibril Kazim\Documents\_LTG\odoo_www\odoo\odoo\service\model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "C:\Users\Muhd Jibril Kazim\Documents\_LTG\odoo_www\odoo\odoo\http.py", line 337, in checked_call
    result = self.endpoint(*a, **kw)
  File "C:\Users\Muhd Jibril Kazim\Documents\_LTG\odoo_www\odoo\odoo\http.py", line 939, in __call__
    return self.method(*args, **kw)
  File "C:\Users\Muhd Jibril Kazim\Documents\_LTG\odoo_www\odoo\odoo\http.py", line 517, in response_wrap
    response = f(*args, **kw)
  File "c:\users\muhd jibril kazim\documents\_ltg\odoo_www\odoo\addons\web\controllers\main.py", line 966, in call_button
    action = self._call_kw(model, method, args, {})
  File "c:\users\muhd jibril kazim\documents\_ltg\odoo_www\odoo\addons\web\controllers\main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "C:\Users\Muhd Jibril Kazim\Documents\_LTG\odoo_www\odoo\odoo\api.py", line 749, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "C:\Users\Muhd Jibril Kazim\Documents\_LTG\odoo_www\odoo\odoo\api.py", line 736, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-61>", line 2, in button_immediate_install
  File "c:\users\muhd jibril kazim\documents\_ltg\odoo_www\odoo\odoo\addons\base\models\ir_module.py", line 74, in check_and_log
    return method(self, *args, **kwargs)
  File "c:\users\muhd jibril kazim\documents\_ltg\odoo_www\odoo\odoo\addons\base\models\ir_module.py", line 445, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "c:\users\muhd jibril kazim\documents\_ltg\odoo_www\odoo\odoo\addons\base\models\ir_module.py", line 561, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "C:\Users\Muhd Jibril Kazim\Documents\_LTG\odoo_www\odoo\odoo\modules\registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "C:\Users\Muhd Jibril Kazim\Documents\_LTG\odoo_www\odoo\odoo\modules\loading.py", line 421, in load_modules
    loaded_modules, update_module, models_to_check)
  File "C:\Users\Muhd Jibril Kazim\Documents\_LTG\odoo_www\odoo\odoo\modules\loading.py", line 313, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "C:\Users\Muhd Jibril Kazim\Documents\_LTG\odoo_www\odoo\odoo\modules\loading.py", line 222, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package, report=report)
  File "C:\Users\Muhd Jibril Kazim\Documents\_LTG\odoo_www\odoo\odoo\modules\loading.py", line 68, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind, report)
  File "C:\Users\Muhd Jibril Kazim\Documents\_LTG\odoo_www\odoo\odoo\tools\convert.py", line 801, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "C:\Users\Muhd Jibril Kazim\Documents\_LTG\odoo_www\odoo\odoo\tools\convert.py", line 864, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "C:\Users\Muhd Jibril Kazim\Documents\_LTG\odoo_www\odoo\odoo\tools\convert.py", line 754, in parse
    self.parse(rec, mode)
  File "C:\Users\Muhd Jibril Kazim\Documents\_LTG\odoo_www\odoo\odoo\tools\convert.py", line 763, in parse
    exc_info[2]
  File "C:\Users\Muhd Jibril Kazim\Documents\_LTG\odoo_www\odoo\odoo\tools\pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Muhd Jibril Kazim\Documents\_LTG\odoo_www\odoo\odoo\tools\convert.py", line 757, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "C:\Users\Muhd Jibril Kazim\Documents\_LTG\odoo_www\odoo\odoo\tools\convert.py", line 649, in _tag_record
    f_val = self.id_get(f_ref)
  File "C:\Users\Muhd Jibril Kazim\Documents\_LTG\odoo_www\odoo\odoo\tools\convert.py", line 740, in id_get
    res = self.model_id_get(id_str, raise_if_not_found)
  File "C:\Users\Muhd Jibril Kazim\Documents\_LTG\odoo_www\odoo\odoo\tools\convert.py", line 746, in model_id_get
    return self.env['ir.model.data'].xmlid_to_res_model_res_id(id_str, raise_if_not_found=raise_if_not_found)
  File "c:\users\muhd jibril kazim\documents\_ltg\odoo_www\odoo\odoo\addons\base\models\ir_model.py", line 1391, in xmlid_to_res_model_res_id
    return self.xmlid_lookup(xmlid)[1:3]
  File "<decorator-gen-25>", line 2, in xmlid_lookup
  File "C:\Users\Muhd Jibril Kazim\Documents\_LTG\odoo_www\odoo\odoo\tools\cache.py", line 93, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "c:\users\muhd jibril kazim\documents\_ltg\odoo_www\odoo\odoo\addons\base\models\ir_model.py", line 1380, in xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % xmlid)
odoo.tools.convert.ParseError: "External ID not found in the system: saas_portal.model_saas_portal_client" while parsing file:/c:/users/muhd%20jibril%20kazim/documents/_ltg/odoo_www/odoo/custom-addons/odoo-saas-tools/saas_portal/data/mail_template_data.xml:3, near
<record id="email_template_create_saas" model="mail.template">
            <field name="name">Send SaaS credentials to the buyer of the SaaS</field>
            <field name="email_from">${(object.user_id.email or '')|safe}</field>
            <field name="subject">Credentials:</field>
            <field name="partner_to">${object.partner_id.id}</field>
            <field name="model_id" ref="saas_portal.model_saas_portal_client"/>
            <field name="auto_delete" eval="True"/>
            <field name="lang">${object.partner_id.lang}</field>
            <field name="body_html">

            &lt;p&gt;Web:
            &lt;a href="${object.public_url}"&gt;${object.public_url}&lt;/a&gt;
            &lt;/p&gt;

            </field>
        </record>
`

**Comment by gridworkz** [comment]
Hi: Sure, I'll take a look. Making a fresh install now...

**Comment by therealmjk** [comment]
@gridworkz okay

**Comment by gridworkz** [comment]
Hi Kazim: Everything installed fine at my end. Could you give me the output
of:

git branch -a

Then try a "git pull" and make sure sure.pulling the HEAD. I had some
issues pulling the repo. I just want to make sure you've really got 12.0
version.

**Comment by therealmjk** [comment]
@gridworkz 

![image](https://user-images.githubusercontent.com/22877146/59032263-132e9980-8890-11e9-8ffb-6040f4d94b47.png)

**Comment by therealmjk** [comment]
@gridworkz i already closed this issue before u commented because i fix the problems actually just wanted to try urs and see. I have it working at the moment but i still have one problem i dont know if you can help?? Pls check this out https://github.com/it-projects-llc/odoo-saas-tools/issues/833

**Comment by gridworkz** [comment]
Hi Kazim: Looks like you've got everything correct. Which repo are you
using mine? You need to set the passwords for admin etc. when you create
the template. Also make sure they have access rights and also make sure
Technical / Settings is available on the user profiles. On Odoo v12 I need
to install the eCommerce module for some reason to get the Technical /
Settings on user profiles.

**Comment by therealmjk** [comment]
@gridworkz The problem is i can't even login my template from the plan

**Comment by gridworkz** [comment]
Ah, I see. What does the Odoo log say? (if anything). What error are you
getting when trying to login

**Comment by therealmjk** [comment]
@gridworkz i am getting this error https://github.com/it-projects-llc/odoo-saas-tools/issues/833

**Comment by gridworkz** [comment]
Hi Kazim: Is the portal module installed?

**Comment by therealmjk** [comment]
@gridworkz sorry for the late reply. Yes the portal module is installed

**Comment by gridworkz** [comment]
Hi Kazim: Did you try accessing the templatedb as superadmin? also are you
using my oauth_provider module?

**Comment by therealmjk** [comment]
@gridworkz right now i have only one user in my db which is the user created when creating the db so i guess thats the super admin. Yes i tried with your oauth_provider too

**Comment by gridworkz** [comment]
hmm you should have two user accounts created in the new templatedb 1)
admin 2) owner_template - I have a working setup online if you want to take
a look at it. You can email me dave@gridworkz.com and I'll send you the
access details....

**Comment by therealmjk** [comment]
@gridworkz no actually i can't also log in my template too. When i create a template from a new plan and log in template, i have same error. Can't also log in. I think it has to do with permissions but im not sure how to fix this

**Comment by gridworkz** [comment]
shoot me an email and I'll show you my setup.

**Comment by therealmjk** [comment]
@gridworkz Done.
