### ISSUE TITLE
error with the saas client module

### ISSUE THREAD

**Issue by ebukoz** [it-projects-llc/odoo-saas-tools#95]
once we have the saas client module installed or once it installed automatically on creating new client we encounter the error below and it does not enable us to open the settings menu.

Uncaught TypeError: Cannot read property 'push' of undefined
http://mic-db.thrivecloud.com.ng/web/content/264-cc12905/web.assets_backend.js:4046
Traceback:
TypeError: Cannot read property 'push' of undefined
    at OdooClass.dashboard.Dashboard.include.init (http://mic-db.thrivecloud.com.ng/web/content/264-cc12905/web.assets_backend.js:4046:234)
    at OdooClass.init (http://mic-db.thrivecloud.com.ng/web/content/261-a23fc50/web.assets_common.js:2535:616)
    at OdooClass.Class (http://mic-db.thrivecloud.com.ng/web/content/261-a23fc50/web.assets_common.js:2533:65)
    at Object.ir_actions_common.widget (http://mic-db.thrivecloud.com.ng/web/content/264-cc12905/web.assets_backend.js:3128:57)
    at Object.<anonymous> (http://mic-db.thrivecloud.com.ng/web/content/264-cc12905/web.assets_backend.js:3125:191)
    at Object.<anonymous> (http://mic-db.thrivecloud.com.ng/web/content/261-a23fc50/web.assets_common.js:650:681)
    at fire (http://mic-db.thrivecloud.com.ng/web/content/261-a23fc50/web.assets_common.js:644:299)
    at Object.self.add [as done](http://mic-db.thrivecloud.com.ng/web/content/261-a23fc50/web.assets_common.js:645:467)
    at Array.<anonymous> (http://mic-db.thrivecloud.com.ng/web/content/261-a23fc50/web.assets_common.js:650:649)
    at Function.jQuery.extend.each (http://mic-db.thrivecloud.com.ng/web/content/261-a23fc50/web.assets_common.js:473:767)

this error shows once you click on the settings menu. We installed the saas client module from the 9.0dev..

Thanks

**Comment by yelizariev** [comment]
please activate debug mode and send log again

**Comment by ebukoz** [comment]
Uncaught TypeError: Cannot read property 'push' of undefined
http://mic-db.thrivecloud.com.ng/saas_client/static/src/js/saas_dashboard.js:9
Traceback:
TypeError: Cannot read property 'push' of undefined
    at OdooClass.dashboard.Dashboard.include.init (http://mic-db.thrivecloud.com.ng/saas_client/static/src/js/saas_dashboard.js:9:28)
    at OdooClass.init (http://mic-db.thrivecloud.com.ng/web/static/src/js/framework/class.js:132:38)
    at OdooClass.Class (http://mic-db.thrivecloud.com.ng/web/static/src/js/framework/class.js:106:33)
    at Object.ir_actions_common.widget (http://mic-db.thrivecloud.com.ng/web/static/src/js/action_manager.js:726:24)
    at Object.<anonymous> (http://mic-db.thrivecloud.com.ng/web/static/src/js/action_manager.js:695:46)
    at Object.<anonymous> (http://mic-db.thrivecloud.com.ng/web/static/lib/jquery/jquery.js:3276:89)
    at fire (http://mic-db.thrivecloud.com.ng/web/static/lib/jquery/jquery.js:3119:58)
    at Object.self.add [as done](http://mic-db.thrivecloud.com.ng/web/static/lib/jquery/jquery.js:3165:49)
    at Array.<anonymous> (http://mic-db.thrivecloud.com.ng/web/static/lib/jquery/jquery.js:3275:77)
    at Function.jQuery.extend.each (http://mic-db.thrivecloud.com.ng/web/static/lib/jquery/jquery.js:383:58)

**Comment by yelizariev** [comment]
You have to use newer odoo 9.0 version
(since Nov 17 at least) https://github.com/odoo/odoo/commit/94d9658c7832943a6d85844a9d9cdbf32f1db12b

**Comment by ebukoz** [comment]
Thanks
